### ISSUE TITLE
format() not working within for loop

### ISSUE THREAD

**Issue by donnellyamanda** [moment/moment#3475] opened 2016-09-29 16:52 UTC
Hi, 

I'm receiving an error within a for loop. The following works correctly, as I hope:

```
 var theDate = $('.schedule').children('.theDate').text();
var when = moment(theDate).format('ddd h:mm A');
 $('.schedule').find('.day').html(when);
```
However, I would like to iterate this through a loop, as such : 
```
var numberEvents = $('.schedule').length;

for (var i = 0; i < numberEvents; i++){

  var $event = $('.event-' + i);
  var theDate = $event.children('.theDate').text();
  var when = moment(theDate).format('ddd h:mm A');
  $event.find('.day').html(when);

}
````

The error I'm getting in the console is: 

`jquery.min.js?ver=3.1.0:2 Uncaught TypeError: Cannot read property 'format' of null`

I have tried completely simplifying the loop, and even if I put the working code within the loop I get the same error. Thank you!

**Comment by icambron** [comment] 2016-09-30 13:31
I think you'll need to do a little more debugging. What's the value of `theDate` at each step of the loop? What does `moment(theDate)` return at each step? That sort of thing. It's probably also a good idea to create a jsFiddle that demonstrates the issue, which you can post here, in the Gitter chat, or on SO.

I'm going to close this since this is definitely not a bug in Moment (Moment doesn't even know it's in a loop), but feel free to mention me in this ticket and I'll try to help.

**Closed by icambron** 2016-09-30 13:31 UTC
Labels: Troubleshooting

**Comment by donnellyamanda** [comment] 2016-10-04 19:15
HI there, thank you! Actually I found the issue. The divs were dynamically generated in WordPress and I didn't realize that I was accidentally generating an empty one of the same criteria when a specific field wasn't filled. So fixed!! Thanks again for the great library.
