### ISSUE TITLE
Add jsnext:main in package.json

### ISSUE THREAD

**Issue by ulrik59** [moment/moment#3104] opened 2016-04-11 09:57 UTC
Using Rollup.js in my project,I am currently using directly the ES6 source files in moment.
The problem I have is that I need to manually create an alias for moment because of the `main` in `package.json` : 

``` js
rollup({
  ...
  plugins: [
    alias({
      'moment/src': '/node_modules/moment/src',
      moment: '/node_modules/moment/src/moment.js',
    }),
  ],
  ...
})
.then(() => {
  ...
});
```

``` js
import moment from 'moment';
let date = moment();
```

But Rollup.js can use a `jsnext:main` in `the package.json` in order to use ES6 code instead of ES5 (see https://github.com/rollup/rollup/wiki/jsnext:main).
Would it be possible to add these field to the `package.json` file ?

**Comment by icambron** [comment] 2016-04-12 06:46
See also #3095

**Comment by piuccio** [comment] 2016-06-22 10:28
Strictly speaking `jsnext:main` is now inside package.json. However when you try to use it, you'll end up having more problems.

I'm currently stuck on this
```
Error loading node_modules/moment/src/lib/locale/locales.js: 'import' and 'export' may only appear at the top level (4:0)
```

This is caused by [this line](https://github.com/moment/moment/blob/b135bf1a6d58ff94287f0a21455bfa6a1ddc7226/src/lib/locale/locales.js#L50).

rollup-babel trips up when there's a mix of import and require.

**Comment by icambron** [comment] 2016-06-22 19:23
Seems like the real problem is not exactly that it's mixing `require` and `import`; the problem is that it's mixing *static* and *dynamic* importing; our `import`s are meant to be compiled down to the right JS (or, plausibly, at runtime by a ES6-aware runtime) but the `require`s are supposed to (definitely, always) happen at runtime. Our code makes sure that line only gets hit in the right environment but of course Babel/Rollup doesn't know that. So you're stuck in this spot where Babel/Rollup is trying to spider every import when there's a subset we want to just leave alone and just stay JS.

I do know there are ways of telling Rollup that certain deps are external. IIRC, there's even a way of providing a plugin that examines each imported path and decides what to do with it. But I don't think any of that will help; Rollup isn't even in a spot to examine the required arg, which hasn't been constructed yet. It makes sense that it chokes before it gets to even thinking about what's being `require`ed.

I'm sort of surprised that Rollup-Babel doesn't simply ignore `require`s, since the point is to turn `import` into the appropriate require-like thing. Maybe there's a way to tell it to do that? Because barring that, I'm not sure how this is really solvable.

There is a project afoot to compile Moment with Babel/Rollup, in which case we'll have to tackle this problem internally too. @timrwood what was the plan for dynamically loading locales in the Babel world?

**Comment by montogeek** [comment] 2016-07-11 16:24
This was done on https://github.com/moment/moment/pull/3192 but the problem persists

**Comment by farwayer** [comment] 2016-11-09 13:13
Locales can't be imported with `jsnext:main`. This is because moment requires it by relative path (`require('./locale/' + name)`) but locales is at package root dir.

**Comment by tauren** [comment] 2016-12-07 06:53
I'm having the same problem as @farwayer, but it only happens when I am using `moment-timezone`:

```
import moment from 'moment-timezone'
```

I'm looking for suggestions on how to resolve the issue. Any ideas?

**Comment by masterkidan** [comment] 2018-04-17 23:28
Is there any plan to fix this? See that the issue has been open for more than a year, and it doesn't help with tree-shaking.

**Comment by marwahaha** [comment] 2020-05-18 08:49
duplicate of https://github.com/moment/moment/issues/3661

**Closed by marwahaha** 2020-05-18 08:49 UTC
Labels: Help Wanted, Loading
