### ISSUE TITLE
Inconsistent behavior when parsing w/ specified format and locale.

### ISSUE THREAD

**Issue by vjleblanc** [moment/moment#4298] opened 2017-11-10 17:13 UTC
**Description of the Issue and Steps to Reproduce:**
As of `2.19.1` parsing behavior seems to have changed. It seems that the `HH` hour field may not be parsing correctly.

**Environment:**
Node 8.2.x on OSX.

```js
console.log(moment('Sun Oct 29 00:52:21 +0000 2017', 'dd MMM DD HH:mm:ss ZZ YYYY', 'en').isValid()); // false
console.log(moment('Sun Oct 29 10:52:21 +0000 2017', 'dd MMM DD HH:mm:ss ZZ YYYY', 'en').isValid()); // true

```
On `2.18.1` I can confirm both above statements resolve as `true`.

**Comment by icambron** [comment] 2017-11-13 18:12
This is a bug, but it's a subtle one. The issue is that Moment is checking whether the date (12:52 on Oct 29) really is a Sunday and declaring it invalid if it isn't. The problem is that when it does that, it's already converted the time to a local time, which in your time zone is actually late Saturday night. It ought to make that check *before* it converts the time.

Someone will have to look at some diffs to see what change was responsible for that.

**Comment by icambron** [comment] 2017-11-13 19:08
I found #4227 which has more on it, so I'm closing this in favor of that.

**Closed by icambron** 2017-11-13 19:08 UTC
Labels: Bug
