### ISSUE TITLE
3 tests failed. locale:ja:calendar last week (1443.13) locale:ja:calendar last week (1443.14) locale:ja:calendar last week (1443.15) 

### ISSUE THREAD

**Issue by ShreyasSN** [moment/moment#5338] opened 2020-01-03 06:53 UTC
### Client info
```
Date String   : Fri Jan 03 2020 12:22:32 GMT+0530 (India Standard Time)
Locale String : 1/3/2020, 12:22:32 PM
Offset        : -330
User Agent    : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
Moment Version: 2.24.0
```

====

### locale:ja:calendar last week (1443.13) 

Today - 6 days current time

```javascript
// Expected 先週土曜日 12:22
// Actual   土曜日 12:22
"土曜日 12:22" === "先週土曜日 12:22"
```

====

### locale:ja:calendar last week (1443.14) 

Today - 6 days beginning of day

```javascript
// Expected 先週土曜日 00:00
// Actual   土曜日 00:00
"土曜日 00:00" === "先週土曜日 00:00"
```

====

### locale:ja:calendar last week (1443.15) 

Today - 6 days end of day

```javascript
// Expected 先週土曜日 23:59
// Actual   土曜日 23:59
"土曜日 23:59" === "先週土曜日 23:59"
```

**Comment by marwahaha** [comment] 2020-05-13 04:13
Thanks.
duplicate of https://github.com/moment/moment/issues/5328

**Closed by marwahaha** 2020-05-13 04:13 UTC
