### ISSUE TITLE
Should `defineLocale` also set the global locale?

### ISSUE THREAD

**Issue by colemars** [moment/moment#5537] opened 2020-05-13 21:07 UTC
Like I would expect 

```
import moment from 'moment';

moment.defineLocale('en-modified', {
  parentLocale: 'en',
  ...localeData
});

export default moment;
```

To **only** define a new locale option that I would then be able to access elsewhere. It's a bit misleading IMO that defining a locale **also** sets the locale.

**Comment by colemars** [comment] 2020-05-13 21:21
I don't really understand if it's even possible to have a full featured moment object used in the same place as another full featured moment object with a different locale.

**Comment by marwahaha** [comment] 2020-05-14 01:06
Not sure, I can chat with the other maintainers.
For now, I'll close as a duplicate of https://github.com/moment/moment/issues/5410 .

**Closed by marwahaha** 2020-05-14 01:06 UTC
