### ISSUE TITLE
1 test failed. relative time:custom rounding (2721.3) 

### ISSUE THREAD

**Issue by Rozhna** [moment/moment#3816] opened 2017-03-08 08:26 UTC
### Client info
```
Date String   : Wed Mar 08 2017 09:24:46 GMT+0100 (Västeuropa, normaltid)
Locale String : 2017-03-08 09:24:46
Offset        : -60
User Agent    : Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
Moment Version: 2.17.1
```

====

### relative time:custom rounding (2721.3) 

Round down towards the nearest day

```javascript
// Expected in 30 days
// Actual   in a month
"in a month" === "in 30 days"
```

**Comment by marwahaha** [comment] 2017-03-09 01:45
Thanks for making an issue.

This is a duplicate of #3801

**Closed by marwahaha** 2017-03-09 01:45 UTC
Labels: Unit Test Failed
