### ISSUE TITLE
Cannot resolve 'file' or 'directory' ./locale

### ISSUE THREAD

**Issue by ddjxie** [moment/moment#3872] opened 2017-03-28 19:44 UTC
**Description of the Issue and Steps to Reproduce:**
Node is unable to load moment's locales using Webpack because it cannot find the directory.

*Error*
```
WARNING in ./~/moment/min/moment-with-locales.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./locale in [project]/node_modules/moment/min
resolve file
resolve directory
  [project]/node_modules/moment/min/locale doesn't exist
 @ ./~/moment/min/moment-with-locales.js 271:16-43
```

*Two temporary fixes that can resolve the issue locally (choose one)*

1. In [project]/node_modules/moment/min/moment-with-locales.js in the function "loadLocale", line 271, change
```
require('./locale/' + name);
```
to
```
require('../locale/' + name);
```
2. Add a symbolic link to the directory
```
user@localhost:~/Workspace/[project]/node_modules/moment/min$ ln -s ../locale/
```

**Environment:**
Moment 2.18.1
Kubuntu 14.04 LTS 64-bit
Node.js 4.8.0 Argon LTS
Webpack 1.12.12

**Comment by icambron** [comment] 2017-04-01 17:38
Hmm, yeah, that path clearly looks wrong; that tilda shouldn't be there. I don't use Webpack, so I'm not able to help, but in order to assist whoever does, can you share enough setup steps to help clarify whether this is a configuration issue or something wrong in the build.

**Comment by marwahaha** [comment] 2017-04-03 04:45
This seems related (but not exactly the same as) https://github.com/moment/moment/issues/2979

**Comment by bjackson** [comment] 2017-05-27 03:07
@ddjxie Did you find a fix for this that didn't require altering the files in `node_modules`? I'm having this same issue.

**Comment by kashalkar** [comment] 2017-10-11 10:05
switching back to moment 2.18.1 also fixes the issue

**Comment by Domiii** [comment] 2017-10-11 14:43
@kashalkar's answer is the real solution here. Go back a version and wait for the devs to finally fix this single character typo in the next release :)

**Comment by icambron** [comment] 2017-10-11 18:32
This is a bug reported against 2.18.1. 2.19.0 was released two days ago, so you must be experiencing something else.

**Comment by cecotw** [comment] 2017-10-11 19:36
I am getting this with 2.19.0, but not with 2.18.1.

**Comment by Domiii** [comment] 2017-10-12 06:54
@icambron I had this on one system with `2.19.0`. And like @kashalkar and @cecotw, going back to `2.18.1` fixes it. IIRC I did not have the issue on another system.

**Comment by trisztan** [comment] 2017-11-15 15:14
I tried with 2.18.1, 2.19.1, 2.19.2 but 

Module not found: Error: Can't resolve './locale' in

**Comment by francisrod01** [comment] 2017-11-22 11:10
The same error, I run the version `^2.19.2`

**Comment by matveyok** [comment] 2017-12-18 14:20
Same here, using 2.18.1 not helped. Any suggestions?

**Comment by francisrod01** [comment] 2017-12-18 15:58
Maybe this solution can be help. https://github.com/moment/moment/issues/2979

**Comment by trisztan** [comment] 2017-12-18 16:16
I tryed but no

*Balogh Ferenc Levente*
*Egyéni Vállalkozó*


*+36 30 472 5776*

*baloghferenclevente@gmail.com <baloghferenclevente@gmail.com>*
*https://www.pcv.hu <https://www.pcv.hu/>*

2017-12-18 16:59 GMT+01:00 Francis Rodrigues <notifications@github.com>:

**Comment by jamesdh** [comment] 2018-12-07 20:05
This appears to be the same issue as #4216 and can probably be closed in favor of that one (since it has a much more exhaustive history to it)

**Comment by HugoPoi** [comment] 2019-01-02 15:33
I'm not sure this is a issue but how moment lib is construct, if you need to import in angular/typescript project you need to it like that
`import * as Moment from 'moment';`

**Comment by Hultner** [comment] 2019-06-08 19:44
Had this problem in react native for web, managed to get around it by importing moment like this.

```js
import moment from 'moment';
import 'moment/min/locales';
```

Fixed the web pack warnings for me and still works, other solutions didn't work in my case.

**Comment by marwahaha** [comment] 2020-05-20 09:35
closing as duplicate of #2979

but as mentioned, https://github.com/moment/moment/issues/4216 has a lot of other info.

Sorry this is a long-standing issue for some Moment.js users.

**Closed by marwahaha** 2020-05-20 09:35 UTC
Labels: Troubleshooting, Loading

**Comment by mattjohnsonpint** [comment] 2026-08-18 17:43
Please see https://github.com/moment/moment/issues/6092#issuecomment-5331841987
