### ISSUE TITLE
Weird utc convert for timezone: Kiritimati Island, UTC+14

### ISSUE THREAD

**Issue by MaksymKurylko** [moment/moment#5454] opened 2020-04-23 11:33 UTC
**Problem:** 
moment returns weird date for timezone: Kiritimati Island, UTC+14

**To reproduce:**

```
const date = new Date(1950, 3, 15);
const formatted = moment(date).utc(true).format();
console.log(formatted);

```
In any timezone, from UTC-12 to UTC+13, It outputs true date:

> 1950-04-15T00:00:00Z 

In timezone Kiritimati Island, UTC+14, It outputs weird date:

> 1950-04-14T23:55:00Z 

**PS**: I do not see such a behavior in native JS. In timezone: Kiritimati Island, UTC+14:
```
const dateISOStr = new Date(Date.UTC(1950, 3, 15)).toISOString();
console.log(dateISOStr); 
```
> 1950-04-15T00:00:00.000Z

**Comment by ashsearle** [comment] 2020-04-25 08:54
What environment are you running this in: which browser, node version, moment version etc, and are you using any plugins?

**Comment by MaksymKurylko** [comment] 2020-04-26 18:12
> What environment are you running this in: which browser, node version, moment version etc, and are you using any plugins?

browser: Google Chrome, Version 80.0.3987.163 (Official Build) (64-bit)
moment: "^2.24.0",
no plugins

But I don't think the issue is specific to my env, please, have a look:
[jsfiddle](https://jsfiddle.net/6exv1nfg/)
[stackblitz](https://stackblitz.com/edit/moment-js-playground-gxce9v?file=index.ts)

Just don't forget to switch to UTC+14 timezone.

**Comment by ashsearle** [comment] 2020-04-28 07:52
I don't see this in my environment: macOS Catalina, Safari, Chrome, Firefox, node 6/8/10/12/14

What O/S?

**Comment by MaksymKurylko** [comment] 2020-04-28 12:16
Windows 10

**Comment by marwahaha** [comment] 2020-09-15 07:19
perhaps a duplicate of https://github.com/moment/moment/issues/5534

**Closed by marwahaha** 2020-09-15 07:19 UTC
Labels: Fractional-Hour UTC Offset, Troubleshooting
