### ISSUE TITLE
Calls to moment.updateLocale increases the memory usage

### ISSUE THREAD

**Issue by inside** [moment/moment#4476] opened 2018-03-05 16:47 UTC
**Description of the Issue and Steps to Reproduce:**

Calling `moment.updateLocale('fr', config)` many times increases the memory usage
and is never reallocated.

Steps and a sample program to reproduce are described [in this
repository](https://github.com/inside/moment-memory-poc).

**Environment:**

Node.JS v8.9.4 on Ubuntu 16.04.4

This issue is probably also reproducible on the browser.

```js
console.log((new Date()).toString())
Mon Mar 05 2018 17:38:57 GMT+0100 (CET)

console.log((new Date()).toLocaleString())
2018-3-5 17:38:57

console.log((new Date()).getTimezoneOffset())
-60

console.log(navigator.userAgent)
undefined (because the demo to reproduce is only on Node.JS)

console.log(moment.version)
2.21.0
```

**Comment by ashsearle** [comment] 2018-03-08 19:39
Can you correct the issue title / description to refer to `updateLocale` instead of `setLocale`?

Looking inside moment I can see the problem is that updating a locale does a merge of the current config and the options you're overriding, then creates a parent pointer back to the unmerged config.

While I agree there's definitely a memory leak if you constantly update locales, I have to ask: what's the reason for updating the locale so much your suffering memory issues?  Is this a long running server app, or what?

**Comment by inside** [comment] 2018-03-08 21:40
I just corrected title and description, thanks for pointing out this.

To answer your question: the server renderer app we have was callling `moment.updateLocale` on every client request. The server memory was full in 2 days and a restart of the app was necessary to free the memory.

Calling this method on every request is not necessary and is a bad practice. The call is now made once on the app startup. Nevetheless, it think it should be safe to call this method many times.

**Comment by marwahaha** [comment] 2018-04-13 06:09
Is there a simple way to fix this issue? Is the parentLocale pointer useful?

If we can't change existing behavior, docs explaining this behavior would be appreciated.

**Comment by ashsearle** [comment] 2018-04-15 10:42
@marwahaha The only explanation I can find for current behaviour of creating a new Locale with a parentLocale pointer is to allow unit-tests to clean-up after themselves.  I've created a PR which still allows for this, while avoiding memory leak in the general case.

**Comment by ichernev** [comment] 2018-06-28 07:57
@inside I totally understand your point, but I'd side with "you're holding it wrong" :)

A few solutions:

1. You keep track of the localeConfig object manually, update it with the new stuff when needed, delete the old locale that it was associated with and set it as a brand new locale (to avoid memory buildup)

2. Currently updateLocale lets you "unupdate" it later on. So its like browsing history. Its just kept forever. There could be a flag that disables the history when updating a locale. I could merge a PR for that.

**Comment by macgyver** [comment] 2018-11-20 16:34
Ya'll, the capability to "unupdate" the locale is not documented and I really can't see an argument for keeping it around. `moment` is a global object with state, clients of it are required to manage the bits of state that they have access to (e.g. the bits that get modified by `updateLocale`). 

One (seemingly) sensible way to manage that state is to explicitly update the bits of it that matter for your purposes every time you call it - it's a bit verbose but it's a pretty obvious solution about how to reason about the code and to know for sure (using the documented public API) that the locale settings are as you wish them to be.

That's a pretty sane use-case which exhibits the memory leak, I don't think it's holding anything the wrong way. We all know that `moment` is not an immutable pure function library, if we cannot have the assurances that the object hasn't changed from side-effects, can we at least have the capability to ensure those settings manually without eventually consuming all system resources?

**Comment by kumarharsh** [comment] 2019-01-22 13:19
For what it's worth, the capability to "unupdate" the locale is documented: https://momentjs.com/docs/#/customization/

Just pass `null` as the second argument in the `moment.updateLocale()` method.

**Comment by marwahaha** [comment] 2020-09-15 21:37
This was merged in https://github.com/moment/moment/commit/ccd55f9b6b6ed9934e92fc2bc18964c35a2154a3


I checked out the reproducibility repository (thanks for this!). Within a minute or two I got to 50000 KB of RAM. When I updated to 2.28.0 RAM held steady around 41000 KB. It did still rise but extremely slowly. Many lines like this:
```
Program is using 41009 kilobytes of RAM.
Is running.
Program is using 41009 kilobytes of RAM.
Is running.
Program is using 41009 kilobytes of RAM.
Program is using 41009 kilobytes of RAM.
Is running.
Program is using 41009 kilobytes of RAM.
Is running.
Program is using 41009 kilobytes of RAM.
Program is using 41009 kilobytes of RAM.
```

**Closed by marwahaha** 2020-09-15 21:37 UTC
Labels: Documentation, Up-For-Grabs
