### ISSUE TITLE
The way moment() constructs changed in 2.11.0

### ISSUE THREAD

**Issue by alexbeletsky** [moment/moment#2871] opened 2016-01-07 10:44 UTC
I've upgraded to 2.11.0 and some of my tests start to fail. After investigation I've noticed that the way `moment()` contructs seems to be different, comparing to 2.10.0.

We use sinon to fake timer, simplified version of test

```js
// before
console.log('test, moment before fake', moment().toDate());

// clock fake
const futureTimeInMilliseconds = moment().add(2, 'days').valueOf();
const clock = sinon.useFakeTimers(futureTimeInMilliseconds);

// after
console.log('test, moment after fake', moment().toDate());
```

The output,

```plain
test, moment before fake Thu Jan 07 2016 11:36:22 GMT+0100 (CET)
test, moment after fake Thu Jan 07 2016 11:36:22 GMT+0100 (CET)
```

With 2.10.0 however, it gives

```plain
test, moment before fake Thu Jan 07 2016 11:36:22 GMT+0100 (CET)
test, moment after fake Thu Jan 09 2016 11:36:22 GMT+0100 (CET)
```

(+ 2 days, the behaviour my tests expects).

PS. If I construct moment as `moment(new Date())` it would give expected `Thu Jan 09 2016 11:36:22 GMT+0100 (CET)`. I found long time ago discussion on this topic, https://github.com/moment/moment/pull/451 could it be a potential regression issue?

**Comment by ichernev** [comment] 2016-01-07 19:01
This is a duplicate of  https://github.com/moment/moment/pull/2858 (to be merged soon).

**Closed by ichernev** 2016-01-07 19:01 UTC

**Comment by alexbeletsky** [comment] 2016-01-07 21:37
Thanks for the update. Great to hear and looking forward it's merged.
