### ISSUE TITLE
moment.js Uncaught SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by buptmuye** [moment/moment#2099] opened 2014-12-15 13:18 UTC
When I use moment.min.js, chrome gave me such error"Uncaught SyntaxError: Unexpected end of input moment.min.js:7"
Here is pieces of .html:
	<script src="/static/js/jquery.min.js"></script>
	<script src="/static/js/bootstrap.min.js"></script>
	<script src="/static/js/headroom.min.js"></script>
	<script src="/static/js/jQuery.headroom.min.js"></script>
	<script src="/static/js/template.js"></script>
	<script src="/static/js/moment.min.js"></script>
	<script src="/static/js/bootstrap-datetimepicker.min.js"></script>

I tried version 2.6 and 2.8.4 2.8.3, but met the same error.

**Comment by icambron** [comment] 2015-04-01 06:28
I'm closing this because it's old and there's no way to reproduce it. @buptmuye I suspect that either you have a bad copy of the file or something else is wrong with your JS environment. If you can provide a jsfiddle, perhaps we can help.

**Closed by icambron** 2015-04-01 06:28 UTC
