### ISSUE TITLE
fromNow short hand

### ISSUE THREAD

**Issue by MartyBolton** [moment/moment#3049] opened 2016-03-17 02:36 UTC
Is there a really simple suggestion where I can override all the relative past times to short hand?  I would think this is really useful for mobile.  I don't need a string a mile long for a mobile screen.

Hoping to change these to short hand, like 1m or 1d or 1w - I think some other small time social apps do this already.  I think someone already posted about similar thing n secongs ago should be just now.  This is a similar request.

How can I override this format to short hand using the component, or do I do my own string replace?
thanks

```
  _relativeTime : {
            future : 'in %s',
            past : '%s ago',
            s : 'a few seconds',
            m : 'a minute',
            mm : '%d minutes',
            h : 'an hour',
            hh : '%d hours',
            d : 'a day',
            dd : '%d days',
            M : 'a month',
            MM : '%d months',
            y : 'a year',
            yy : '%d years'
        },

using 

angular.module('app')
  .filter('fromNow', function() {
    return function(date) {
      return moment(date).fromNow();
    }
  });
```

**Comment by maggiepint** [comment] 2016-03-17 21:38
Assuming you are running 2.12.0, the following would do the trick:

```js
moment.updateLocale('en', {
    relativeTime : {
        future: "in %s",
        past:   "%s ",
        s:  "s",
        m:  "m",
        mm: "%d m",
        h:  "h",
        hh: "%d h",
        d:  "d",
        dd: "%d d",
        M:  "a mth",
        MM: "%d mths",
        y:  "y",
        yy: "%d y"
    }
});

moment().subtract(2, 'minutes').fromNow()
"2 m "
```
If you are running pre 2.12.0, it would be:
```js

moment.locale('en', {
    relativeTime : {
        future: "in %s",
        past:   "%s ",
        s:  "s",
        m:  "m",
        mm: "%d m",
        h:  "h",
        hh: "%d h",
        d:  "d",
        dd: "%d d",
        M:  "a mth",
        MM: "%d mths",
        y:  "y",
        yy: "%d y"
    }
});
```
You could replace my hastily done shorthand with whatever you wanted.

It would also be an option to create a new locale, something like "en-mobile", that inherited from the parent locale. Then when you were on desktop you could use long form, and when you were on mobile you could flip over.
The parentLocale feature is a 2.12.0 feature.

```js
moment.locale('en-mobile', {
parentLocale:'en',
    relativeTime : {
        future: "in %s",
        past:   "%s ",
        s:  "ssssssssssss",
        m:  "m",
        mm: "%d m",
        h:  "h",
        hh: "%d h",
        d:  "d",
        dd: "%d d",
        M:  "a mth",
        MM: "%d mths",
        y:  "y",
        yy: "%d y"
    }
});
```
Is that what you needed?

**Comment by MartyBolton** [comment] 2016-03-17 22:22
Hi Maggie - thanks!  I'll try that!   Thanks for the code example too and fast reply!
Marty

**Comment by maggiepint** [comment] 2016-03-17 22:26
Closing since I think the problem is solved.

**Closed by maggiepint** 2016-03-17 22:26 UTC

**Comment by rmisio** [comment] 2017-02-21 01:00
(I also posted this comment on #2781 - sorry for the spam)

I would really love to see this feature be implemented in the core codebase. These instagram style short abbreviations are pretty ubiquitous these days.

Yes, I agree, it is quite easy to customize for one language. But... if your app needs to support multiple locales, suddenly you need to handle customizing it in the all langs you support. It would be really nice to have the power of moment's community take that burden on.

**Comment by mikerockett** [comment] 2017-12-06 12:08
+1

Additionally, there are often times when you need long-hand and short-hand in different parts of the app… In those instances, updating locales seems a bit overkill… Or maybe that’s just me?

**Comment by ZainaliSyed** [comment] 2018-03-16 07:08
```

moment.updateLocale('en', {
    relativeTime : {
        future: "in %s",
        past:   "%s ",
        s:  "s",
        m:  "m",
        mm: "%d m",
        h:  "h",
        hh: "%d h",
        d:  "d",
        dd: "%d d",
        M:  "a mth",
        MM: "%d mths",
        y:  "y",
        yy: "%d y"
    }
});

```
**REFERENCE** 
### IMPLEMENTATION GUIDANCE 

[MomentJS change 'a day ago' to '1d'](https://stackoverflow.com/questions/46097321/momentjs-change-a-day-ago-to-1d/49043964#49043964)

**Comment by TheMangoTrain** [comment] 2022-11-09 14:57
Any movement on this?

I agree the strings are way too long for mobile.

I'm shying away from using the suggested locale trick, as ultimately I need everything: short form, long form AND multiple locales.
