### ISSUE TITLE
ISO-8601 allows comma-separated milliseconds, momentjs does not.

### ISSUE THREAD

**Issue by welch** [moment/moment#2596] opened 2015-09-02 21:38 UTC
the 8601 standard allows fractional seconds to be separated by dot or comma (search for 'decimal mark' in the wikipedia page you link in your docs). I see the comma variant in cassandra and elastic search logs.

**Comment by pietercolpaert** [comment] 2015-09-08 17:39
Duplicate of #2450

**Closed** 2015-09-08 17:54 UTC
