### ISSUE TITLE
Use appropriate syntax for es6 imports

### ISSUE THREAD

**Issue by thoughtsunificator** [moment/moment#5518] opened 2020-05-07 16:35 UTC
Line 7 of moment.js: 
``import { hooks as moment, setHookCallback } from './lib/utils/hooks';
As well as all the other imports.

Simply adding file extension ".js" as it is the [proper syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) would allow me to use moment js in the browser without the need of a bundler.

That is as long as moment.js is not using external npm packages which is the case according to the [package.json](https://github.com/moment/moment/blob/master/package.json).

**Comment by dasa** [comment] 2020-05-08 22:04
The files in `/dist` may work: https://github.com/moment/moment/blob/develop/CHANGELOG.md#2252

**Comment by marwahaha** [comment] 2020-05-18 04:24
duplicate of https://github.com/moment/moment/issues/4713 (We will not take this change).

**Closed by marwahaha** 2020-05-18 04:24 UTC
