### ISSUE TITLE
Modularize moment.js, make the core as light as possible

### ISSUE THREAD

**Issue by srcspider** [moment/moment#2373] opened 2015-05-13 11:38 UTC
I remember when moment was a "lightweight" library, right now at 12kb (gziped no less) for, what it's in most cases, just very very simple date manipulation.

A simple solution to this problem would be to modularize momentjs so at least for environments like browerify, webpack and such a minimal version can be obtained.

eg.

Regular usage can stay the same,

``` js
// get everything under the sun
var moment = require('moment');
```

Modular usage could look like this,

``` js
// get core, the core does nothing, no validation, no nothing
// it would only define a internal storage structure and the bare minimum
// methods for getting values out of it: day, month, year, etc (no "format" 
// functions or "fromNow" since you might not even want to use them)
var moment = require('moment/core');

// add plugins for all the stuff you need, if you ever want ALL of them you 
// just include the directory instead (node/browserify/webpack will pick up
// a index.js inside it that would have all the things)
moment.plugin([

    // if you know this is all the parsers you need this is all you add
    require('moment/plugins/parser/yyyy-mm-dd-time'),
    require('moment/plugins/parser/unixtime'),

    require('moment/plugins/validator/yyyy-mm-dd-time'),
    // if we don't use unixtime locally, only on server we dont care for that
    // when it comes to validation

    require('moment/plugins/fromNow'),
    require('moment/plugins/toUnixTime'),

    // with a modular structure we can add 3rd party stuff really easily
    require('moment-phpstyle-format'),
    require('moment-chained-functions-format')

]);

// lock in the configuration so that calling plugin method throw and exception
// this would be irreversible but you can get a unlocked version by calling copy
// this will force people to get a "copy" of the configuration before doing 
// anything stupid -- or help them find the mistake if they add it later
moment.lock();

// you now just include this file where you need it
module.exports = moment;
```

Let's pretend the above is in something like `lib/moment` and represents your default boilerplate configuration for it. Obviously you may eventually encounter situations where you need more advanced functions. If we add to the default boilerplate we unfortunately add to every other context that doesn't need it. This is a big bummer if we're trying to keep client size down with things like webpack code splitting. 

**However**, so long as the modular system is capable of being extending any time there's no problem whatsoeve. Ideally, to avoid subtle race condition bugs, we should be able to get a new "advanced" version as a separate instance:

``` js
// load boilerplate we defined previously
// we request a copy of the instance so no funny business happens
var moment = require('lib/moment').copy(); 

// we can also create a separate boilerplate if we re-use this a lot
moment.plugin(require('expensive-internationalization-timezone-nonsense'));
moment.lock(); // lock the new copy just in case its passed around

// moment instances should be able to do a quick copy between instances
// to ensure functionality, ie. moment(createdAt) could just swap plugin pointers
```

Now only the module that actually uses that feature pays the cost. If you use moment in 100 places and only 1 actually needs internationalization just that one place will ever pay for it. This applies to all functions, all the core needs to do is store a plain date object and some getters. Is everything you do just pass unix time from the server? you can just have unixtime parser. Do you only ever validate dates on the server? you can skip on any and all validation, etc. 

It's effectively as light as you building your own specialized helpers. And much like projects like gulp, postcss and so on the community can contribute easily to it though easily maintainable chunks.

And in this way, momentjs can, _once again_, be called "[lightweight javascript date library](https://web.archive.org/web/20111214102140/http://momentjs.com/)".

**Comment by naartjie** [comment] 2015-06-12 12:04
> right now at 12kb (gziped no less)

Are you using the version from CDN or npm? My size increase is more like `48kb` gzipped. #2416

**Comment by srcspider** [comment] 2015-06-12 12:13
@naartjie 

You'll want to use `webpack`'s ignore plugin (sorry cant recall name of the top of my head) to exclude locale information. That should bring it down to something more reasonable.

`48kb` gzip is indeed pretty crazy, my largest entry point (react + various util functions + application code for full rendering) sits at around `50kb` gzip. I've switched to just using unix timestamps and completely custom functions to process those into a format as needed... a bit sad, would love to use a date manipulation library but just can't take a +100% initial load javascript bump. It's obviously even worse on subsequent incremental loads (caused by `require.ensure`) since those average at `10kb` gzip as it's mostly application specific code, so should initial load avoid dates but one of those require dates then that's a 6x size increase.

**Comment by naartjie** [comment] 2015-06-12 16:59
Thanks for the rundown @srcspider, I have read about IgnorePlugin before, but I didn't click that it was applicable for these kinds of situations, so it helps to match theory and practical together :+1: 

> Does anyone need a library that gets bigger and bigger?

Don't you want to edit that line out? It might seem a little too brash, where as I think your general tone of the issue is very helpful, and you have a valid point. Plus you seem to know how this should all go down, I think a PR would go down well, I hear they're looking for [help](https://github.com/moment/moment#contributing). ;-)

**Comment by naartjie** [comment] 2015-06-15 16:08
I think it would be great to have the option to require a version **with** or **without** locales, that would be great for a start, and probably not too massive a refactor. I could have a stab at a PR. What say you @srcspider, do you think that would be useful to anyone else for a start.

I know it's a :+1: from me, but I'm not sure if there would be any other takers out there.

**Comment by srcspider** [comment] 2015-06-16 08:31
@naartjie not to be the bearer of bad news but would probably recommend waiting on one of the owners to give their thoughts on this before putting any considerable effort in. No point in pushing only to be shot down (or never approved). However if you need it yourself right now, by all means.

> Plus you seem to know how this should all go down, I think a PR would go down well, I hear they're looking for help. ;-)

Sadly I'm very much on the fence on ES6. It doesn't integrate with my current workflows, and can't see any advantage to the various recommendations of ES6 workflows I've encountered (and by "no advantage" what I mean is they're far far inferior in resulting size, architecture and just a lot more unnecessarily complex in general).

*It's hard to get exited to contributing to a "Port to ES6" when it's, overall, just a worse thing (for me).*

**Comment by ichernev** [comment] 2015-06-25 05:47
The port to es6 is supposed to benefit development, not users. There are packaged versions of moment, with and without locales, uploaded to npmjs.

About making a small core that is extensible - that is going to be a big step back in usability for most users. If you feel like it patch the src/moment to include what you want and transpile.

I'm closing this for now. If a moment without locales is not bundled properly feel free to reopen.

**Comment by naartjie** [comment] 2015-06-25 15:43
> There are packaged versions of moment, with and without locales, uploaded to npmjs

@ichernev I tried looking, and all I found was [moment](https://www.npmjs.com/package/moment) and [moment-timezone](https://www.npmjs.com/package/moment-timezone), could you point me to the version of moment without locales in npmjs. 

I actually asked in #2416 for this, and it seems like using the IgnorePlugin is a hack/workaround, if there is already a packaged version without locales.

Thanks.

**Comment by ichernev** [comment] 2015-06-29 14:53
Aaah, I see. Npmjs is historically used for server side, where you don't care about size. But for other build tools that go on top of it, I guess we shall add another target `moment-core` or something like this.

**Comment by naartjie** [comment] 2015-06-29 14:56
That would be great, thanks @ichernev. It will make integrating with tools like webpack a breeze (without needing the likes of IgnorePlugin).

I see you've reopened this one, so I'm going to close #2416 again ;-)

**Comment by fresheneesz** [comment] 2015-07-15 07:40
@ichernev I use npm for both frontend and backend, and I think this has become much more common.  I'm also a bit concerned with loading in a giant library just for the use of a couple nice date manipulation apis. +1 for a lean-core via npm, and an easy way to optionally add locales / peripheral functionality with the default being exclusion (unless explicitly included).

**Comment by rey-wright** [comment] 2015-07-16 19:21
+1 definitely

**Comment by jeffbski** [comment] 2015-08-04 22:13
+1

**Comment by seethroughtrees** [comment] 2015-08-27 23:09
would love this as well.

**Comment by dbrugne** [comment] 2015-09-03 12:40
+1

**Comment by jhubert** [comment] 2015-09-21 19:34
One of the first (and best) optimizations we did was remove moment.js from our client side app. I would love to use moment.js more frequently but the additional page weight just isn't worth it for the basic date manipulation we do.

So, I'm a big +1 on this as well.

**Comment by rey-wright** [comment] 2015-09-24 23:04
@jhubert I'm actually starting to consider that. What did you replace moment with? It's one of the largest things in my app.

**Comment by jhubert** [comment] 2015-09-25 05:38
@rey-wright I was really only using it for formatting, so I just wrote a few functions that [formatted the dates exactly as I needed them](http://stackoverflow.com/questions/3552461/how-to-format-a-javascript-date) and used them throughout the site. It's nothing elegant, but it's extremely fast and light.

**Comment by rey-wright** [comment] 2015-09-28 14:07
@jhubert yeah we were doing that but... I really wish moment would be setup better...but now it's like Moment is one of the biggest pieces of our app...

So yeah we might eventually go back to this method as well. Thanks for the insight.

**Comment by mindeavor** [comment] 2015-10-07 15:18
+1. Moment.js looks great, but the 12kb makes it not worth the include (that's bigger than the framework we use!)

**Comment by DerekDomino** [comment] 2015-11-19 10:49
tests.js file could be removed from the npm package. This file amounts to 63% of the total npm package size. A dedicated development npm package could could include this tests.js file.

**Comment by fresheneesz** [comment] 2015-11-19 21:48
@DerekDomino The point of modularizing moment.js is for two reasons:

* Less code for browsers to download
* Easier to maintain many smaller packages than one large one

Removing a tests file doesn't accomplish either of those goals, and in fact doing what you suggest would make it harder to develop moment. And if you're for some reason having browsers forced to download the tests.js code, something else is going wrong.

**Comment by vsimonian** [comment] 2015-11-19 23:31
@fresheneesz While yes, the suggestion doesn't fix the main problem, why would excluding a test file from the npm package make it harder to develop moment? It isn't the same as removing tests from the repository, and, generally, test code is not meant to be packaged.

**Comment by fresheneesz** [comment] 2015-11-20 00:48
Oh, just the npm package? I guess it wouldn't then. Still don't think its a road worth traveling.

**Comment by iagopiimenta** [comment] 2015-12-06 19:22
:+1:

**Comment by Aweary** [comment] 2016-01-25 16:11
@ichernev has there been any work done on this?

**Comment by niksy** [comment] 2016-01-25 18:07
I’ve also been looking for this, but in the meantime you can try https://date-fns.org/. It doesn’t have full Moment.js functionality, but it covers a lot of standard use cases.

**Comment by Zequez** [comment] 2016-02-02 14:58
I like the solution [`lodash`](https://github.com/lodash/lodash) uses, if you look it's branches you can see they have a special [`x.y.z-npm` branch](https://github.com/lodash/lodash/tree/4.2.0-npm), and inside they have all the utilities separated in their own files in the root directory. This allows you to just `import { whatever } from 'lodash'` without importing the whole library.

**Comment by haoxins** [comment] 2016-02-02 15:18
> This allows you to just import { whatever } from 'lodash' without importing the whole library.

@Zequez If I use `webpack` for front-end, still including all the libs.

**Comment by Zequez** [comment] 2016-02-02 15:25
@haoxins Sorry, yes, there I corrected it with the correct syntax, you have to import from `lodash/functionName`. Not the ideal, as you need a statement for each function. But modular enough I guess.

**Comment by naartjie** [comment] 2016-02-02 15:40
Definitely an improvement on the current workaround: i.e. exclusions in
webpack.

**Comment by reywright** [comment] 2016-03-16 15:20
@niksy awesome suggestion, I'm going to take a look at it today.

**Comment by fxck** [comment] 2016-05-18 21:45
any update on this?

**Comment by joshwcomeau** [comment] 2016-06-20 11:47
+1 I'm very much in support of a lodash-style solution. Users unconcerned with bundle sizes can still just `import moment from 'moment'`, but I'd like to be able to do something like `import moment from 'moment/core'`. 

The webpack solution is working for me, but it's still a pretty big bundle for what I need it for (simple date formatting/calculation).

**Comment by andrewmclagan** [comment] 2016-07-04 13:31
I feel there are many dev's who avoid moment for its size, there are alternatives coming in at less then 10%

**Comment by srcspider** [comment] 2016-07-04 15:15
@andrewmclagan there's worse then that. How would you feel if a library you wanted to use pulled moment in when you weren't looking? ;)

**Comment by andrewmclagan** [comment] 2016-07-05 04:04
haha don't worry thats exactly whats happening to me right now...

**Comment by mattgrande** [comment] 2016-07-05 12:48
@andrewmclagan: Can you recommend a good datetime library that comes in at less than 10% of Moment's size?

**Comment by avindra** [comment] 2016-07-05 13:30
@mattgrande : https://github.com/date-fns/date-fns takes a lodash-like approach to the modularity problem

**Comment by mattgrande** [comment] 2016-07-05 13:36
Thanks, I'll check it out.

**Comment by andrewmclagan** [comment] 2016-07-13 11:14
Yeah also using date fns

**Comment by mattgrande** [comment] 2016-07-15 13:48
So checking into date-fns, moment.min.js (the current version that includes all comments for some reason) is 57.3KB; The last version without comments was 45.6. Meanwhile, date-fns is 56.9 KB, only 0.4KB difference.

**Comment by anaibol** [comment] 2016-07-17 21:17
![selection_164](https://cloud.githubusercontent.com/assets/3210177/16903112/92c40a32-4c74-11e6-8539-c35cb83fa8a0.png)
Moment is the most heavyweight library in my stack!

**Comment by maggiepint** [comment] 2016-07-17 22:06
@anaibol how are you building that? Does it include locale files? 
It's really odd to me that one person is reporting 135k and another 57.3. Something else is going on here.

**Comment by okonet** [comment] 2016-07-18 08:05
@mattgrande I think the point of `date-fns` is to not bundle the whole library. Using tools like webpack or rollup with tree shaking you can only bundle the modules you're using in the application. This isn't possible with the current moment.js and that's exactly why this issue exists. So this comparison isn't valid to me.

**Comment by newraina** [comment] 2016-07-18 08:24
@okonet using webpack@2 (with tree shaking) also bundle all modules in moment.js.

**Comment by anaibol** [comment] 2016-07-18 08:45
@maggiepint: building moment with webpack@2 and "new webpack.ContextReplacementPlugin(/moment[\/\\]locale$/, /fr/)," and using it with "import moment from 'moment'"

**Comment by okonet** [comment] 2016-07-18 10:24
@newraina I know it does. This issue exists for that reason. Am I missing something you're trying to say?

@anaibol I use this to exclude locales in webpack:

```js
new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/) // Ignore all optional deps of moment.js
```

**Comment by srcspider** [comment] 2016-07-18 11:31
@mattgrande
> So checking into date-fns, moment.min.js (the current version that includes all comments for some reason) is 57.3KB; The last version without comments was 45.6. Meanwhile, date-fns is 56.9 KB, only 0.4KB difference.

This was already pointed out by @okonet but to put into perspective, I resorted to just writing my own functions to achieve the same thing and making sure everything works only with timestamps and the **overhead of date related functions when used in a webpack build is measured in `Bytes` not `Kilobytes`** for most bundles (use `require.ensure` a lot so it's all incrementally loaded too).

**Comment by davidcalhoun** [comment] 2016-08-03 02:14
Thanks @okonet, that worked pretty well for me.  Went from 420kb to 249kb (171kb diff)

**Comment by petermikitsh** [comment] 2016-08-13 15:01
Using @okonet's advice is good enough to get by for now. I was able to reduce my build size by about 140kb (953kB -> 807kB). Thanks!

**Comment by akinnee-gl** [comment] 2016-08-16 19:02
Yes please

**Comment by Haraldson** [comment] 2016-08-18 08:22
Any news on this? Is the core team considering something along the lines of lodash-style way of importing just the stuff you need?

**Comment by ichernev** [comment] 2016-08-18 16:56
We're thinking about it. Its coming after immutability, maybe :)

**Comment by framerate** [comment] 2016-08-25 19:02
<img width="628" alt="screen shot 2016-08-25 at 11 53 29 am" src="https://cloud.githubusercontent.com/assets/74291/17982224/c8a3fa9e-6abb-11e6-9c19-d4c62b67edf5.png">

You guys are complaining about 145Kb... :(

**Comment by akinnee-gl** [comment] 2016-08-25 19:12
Yes we are.

**Comment by srcspider** [comment] 2016-08-26 09:06
@framerate 

Are those the sizes on disk? On network everything *should* be gziped. The disk size does play out, but it's a consideration of "how much javascript browser has to load before first render" (smaller is better) rather then a network consideration.

Bellow show maximum gzip; depending on your server settings it might look very different.

`libs.js` is the commutative shared libraries as generated by webpack 
(actual disk size is 267K; mostly react -- babel adds some bloat to everything too)
```sh
# gzip-size libs.js | pretty-bytes
75.82 kB
```

Random common place page (signup.js) entry point.
```sh
# gzip-size signup.js | pretty-bytes
4.95 kB
```

Between pages, partial js download happens (require.ensure). The following is the largest one,
```sh
# gzip-size partial.4.e4d6ff3506d1ded07d0f.js | pretty-bytes
4.96 kB
```

moment.min.js
```sh
# curl -L -o moment.min.js http://momentjs.com/downloads/moment.min.js
# gzip-size moment.min.js | pretty-bytes
20.22 kB
```
4x page, 4x partials, and 1/4 of ALL other dependencies combined in size? The functionality moment provides just doesn't justify it. The library should be practically invisible when looking at the sizes.

Lodash is actually very similar. If I were to include the entire thing it actually looks like this,

```sh
# curl -L -o lodash.min.js https://cdn.jsdelivr.net/lodash/4.15.0/lodash.min.js
# gzip-size lodash.min.js | pretty-bytes
23.45 kB
```
But I explicitly require the functions I need so it doesn't even show up at all. Because really even if your library has a ton of functionality, nobody actually uses everything on every single page.

**Comment by framerate** [comment] 2016-08-30 21:47
@srcspider Yeah, but this is using via npm + webpack with locales (other than en) stripped out using the techniques/hacks in this thread.

**Comment by vojtatranta** [comment] 2016-12-15 01:01
@framerate sorry for an off-topic question, but what's the name of that module you use to analyze sizes of packages in the build? That fancy table you shown - I am now working on build optimization and this would be really handy to me. Thanks!

**Comment by framerate** [comment] 2016-12-15 01:04
@vojtatranta No Problem! It's `webpack-dashboard`

https://github.com/FormidableLabs/webpack-dashboard

**Comment by jeffbski** [comment] 2016-12-15 18:26
@vojtatranta Also check out https://github.com/robertknight/webpack-bundle-size-analyzer it is pretty easy to use just 

```
webpack --json | webpack-bundle-size-analyzer
```

and it spits the details in the console.

**Comment by vojtatranta** [comment] 2016-12-16 11:22
@jeffbski yeah I am using it but sad thing is that it does not show the size packages in minified build and it does not even show how the package will be deduped

**Comment by ilionic** [comment] 2016-12-25 22:57
@vojtatranta check this one https://github.com/th0r/webpack-bundle-analyzer Nice visualisation, also showing min and gzip sizes

**Comment by dmitriid** [comment] 2017-01-02 14:04
In our app:

```
webpack --json | webpack-bundle-size-analyzer
```

Before ignoring locales:

```
> cat profile.json | webpack-bundle-size-analyzer
moment: 466.96 KB (20.5%)
jquery: 260.93 KB (11.5%)
iconv-lite: 199.46 KB (8.76%)
moment-timezone: 188.54 KB (8.28%)
```

after ignoring locales:

```
> cat profile.json | webpack-bundle-size-analyzer
jquery: 260.93 KB (13.4%)
iconv-lite: 199.46 KB (10.2%)
moment-timezone: 188.54 KB (9.68%)
lodash: 141.27 KB (7.25%)
moment: 137.34 KB (7.05%)
```

Note: webpack-bundle-size-analyzer returns sizes _before_ any minification/uglification etc. is applied.

However, we can look at the actual output size:

```
> NODE_ENV=production npm run webpack

... with locales ...
app.js  1.08 MB

... no locales ...
app.js  925 kB
```

Locales do add a very significant chunk to the overall size.

**Comment by caesarsol** [comment] 2017-02-10 11:56
What about this issue?

I reverted to using the extra-light [`dateformat`](https://www.npmjs.com/package/dateformat) because of all the unneeded clutter this library bundles...

**Comment by adi518** [comment] 2017-02-11 20:43
Hmm yea. Always wanted to use moment.js, but the payload, oh the payload is heavy.

**Comment by reywright** [comment] 2017-02-14 17:46
@caesarsol look into date-fns. I was using that library then transitioned to this one... using it in production

**Comment by dmitriid** [comment] 2017-02-14 18:01
Use:
- `new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/),` in your webpack config, or:
- lighter alternatives like date-fns or dateformat

If you need i18n/l10n though:

- `new webpack.IgnorePlugin()` with anything that's *not* your locales, or:
-  (how we do ended up doing it) load required locale in a `<script>` tag separately (it may require tweaking locale code etc.)

**Comment by ksloan** [comment] 2017-02-24 21:53
this module exposes moment without the locales https://github.com/ksloan/moment-mini

**Comment by powmedia** [comment] 2017-02-28 22:00
Switching to moment-mini was easy and shaved 226kB off the build size

**Comment by pke** [comment] 2017-03-10 23:30
momenjs even without the locales still comes in at 140kb atm. For simple date formatting, that's way to much. Switching to something else now.

**Comment by wiesson** [comment] 2017-03-22 13:24
@pke - Whats your alternative?

**Comment by fxck** [comment] 2017-03-22 13:26
@wiesson https://date-fns.org/

**Comment by pke** [comment] 2017-03-22 13:39
Indeed date-fns is the way to go. Remember though, moment started as 4.3kb package too back in the days.

**Comment by wmertens** [comment] 2017-03-22 15:35
I think that if moment.js was split into a file-per-function like lodash, and then with the help of something like the lodash webpack plugin, it could be tree shaken so only the used functions remain.

**Comment by pke** [comment] 2017-03-22 17:55
True, but date-fns already provides all that

**Comment by pke** [comment] 2017-03-22 17:55
True, but date-fns already provides all that

**Comment by reywright** [comment] 2017-03-24 19:30
@pke it doesn't matter what size date-fns ends up being, as long as you can specifically require certain things.

**Comment by halt-hammerzeit** [comment] 2017-04-11 11:37
The current ES6 export is not really an ES6 export.
See my PR showing the ES6 way of exporting:
https://github.com/moment/moment/pull/3905
Using `./src` is possible when no `ES6` features are used (default arguments, const, spreads, etc), otherwise it would be `./es6-build` folder.

**Comment by ichernev** [comment] 2017-04-30 22:52
Anybody who wants to actually make a dent at this issue (excluding the webpack, all-locales-together, 300k issue), should reorganize the code and put the stuff that s/he thinks is splittable in folder(s), and show what the gains will be.

Here's currently how much each file contributes http://iskren.info/moment-size.html

Keep in mind that concepts are intertwined, so for example week support, locale support, and generic parsing support (I list these because they're IMHO some of the biggest things in moment) sometimes all go in the same file, and one can not really split them, because they're not orthogonal, so out of those 3, maybe only one can be split out (driving pieces of the other 2 with it). My inner feeling tells me splitting each of those will cut max 20% off the size, and you can do it only once, so the gains will not be huge.

**Comment by pke** [comment] 2017-05-01 07:08
Sounds all very fine. Someone might give it a try. I've moved over to date-fns and left momentjs behind. Got to finish some production app, and need to squeeze every byte. Good luck!

**Comment by ovangle** [comment] 2017-06-29 07:26
Until I had a deep dive into the code in the last couple of days, I would have been 100% +1 on this. But now I think that the libary is not structured to support plugin functionality in any meaningful way and would need a complete redesign (something like date-fns) to support it.

The problem lies in the fact that the library treats it's namespace like an `Object`. This is a problem, because a plugin effectively has to "extend" the namespace in order to contribute a function to it. But the library also assumes that it's a singleton, so only one of these "subclasses" can really be instantiated at the one time. It's slightly more nuanced than that (the reason is that there is no way to indroduce "static" plugins -- ones which (apart from their dependency graph) are not sensitive on the order they're loaded), but I think the subclassing metaphor is the easiest way to describe it.

I tried decoupling `duration` from the rest of the library, since it seemed like the easiest thing to decouple (even if it wasn't the biggest feature). It sort of worked (or at least it looked promising), but then I tried decoupling `locale`, and I realised that a plugin system would never work with the code structured the way it is.

It's certainly possible to do something like `rxjs 5` did for when they rewrote their library to be more modular, but it would require a _lot_ of breaking changes and it would take a lot of developer hours.

And I think the webpack people here who are having problems with the `300kb` bundle size of moment would agree that we need `3.0` quicker than that in order to make the breaking changes necessary in order to fix _that_ problem (see my rants at #4025).

There are also plenty of refactorings which could be made for 3.0 which would reduce the bundled size without requiring functionality to be split out into separate modules...

**Comment by maggiepint** [comment] 2017-06-29 11:11
@ovangle, thanks for taking time to truly understand this issue. As we've pointed out on this thread, this ask is extremely non-trivial for this code - probably nothing less than a couple weeks of dev time from someone on the core team. 

For the webpack bundle size specifically, I think we would be reasonably able to take your changes described in the other issue. Headed over there to discuss.

**Comment by mesqueeb** [comment] 2017-06-29 12:19
I use the JS date functions from the [Quasar framework](http://beta.quasar-framework.org/components/handling-js-date.html). It can do treeshaking easily like so:
```` js
// we import all of `date`
import { date } from 'quasar'
// destructuring to keep only what is needed
const { addToDate } = date
````
Is this not yet possible with momentjs?

**Comment by pke** [comment] 2017-06-29 13:23
Maybe moment.js had its moment and its time to head to something new more compatible with webpack and small bundle sizes aka date-fns. I am out of here. Good luck :)

**Comment by ovangle** [comment] 2017-06-29 15:03
@mesqueeb

> There are also plenty of refactorings which could be made for 3.0 (or even 2.19/2.20) which would reduce the bundled size without requiring functionality to be split out into separate plugins...

Making the moment namespace itself static and allowing tree shaking to do the work of removing unused functionality than completely decoupling the code in the short term... then at least _some_ of moment would a valid target for tree shaking.

**Comment by maggiepint** [comment] 2017-06-29 15:16
I could see making the namespace static. I actually really want to change
moment() to moment.local() for API design purposes. People get confused.

**Comment by petermikitsh** [comment] 2017-06-29 18:48
I've had good success transitioning to [date-fns](https://github.com/date-fns/date-fns). I cut my bundle size substantially because I was only using the momentjs `format` function, of which `date-fns` has pretty much a drop-in replacement.

**Comment by codeofsumit** [comment] 2017-09-13 20:26
...damn
![image](https://user-images.githubusercontent.com/2399810/30398992-8f177e9a-98d2-11e7-826a-903cf392d9a8.png)

**Comment by fwchen** [comment] 2017-09-17 03:33
+1 too big

**Comment by codeofsumit** [comment] 2017-09-17 10:02
@petermikitsh thanks for the suggestion. Switched as well and it works like a charm!

**Comment by maggiepint** [comment] 2017-10-12 00:09
This is probably not the answer to prayers those on this thread wanted - however we do have what I will call a 'moment labs' project going on that is significantly smaller. It is not a compatible API, but it is properly modularized and comes from @icambron of the moment team. I invite interested parties to try it out and give feedback: http://isaaccambron.com/luxon/docs/

**Comment by ldrick** [comment] 2017-10-20 07:59
Thanks to all, I came across the same situation trying to bundle moment with webpack and could build on all proposals a quite acceptable way at least for me:
1. Use uncrompressed sources of momentjs.
2. Bundle only required locales.

Basicly it is just combining these ideas:
1. https://webpack.js.org/configuration/resolve/#resolve-alias
2. https://webpack.js.org/plugins/context-replacement-plugin/#content-callback

These are the relevant parts in my webpack.config.js.
```javascript
const path = require("path");
const webpack = require("webpack");

module.exports = () => {
    return {
        // ...
        resolve: {
            // Use src Moment.js to be optimized and packed.
            alias: {
                moment$: "moment/src/moment",
            },
        },
        // ...
        plugins: [
            // Switch context for Moment.js locales.
            new webpack.ContextReplacementPlugin(/^\.\/locale$/, context => {
                // Don't touch anything else then "moment".
                if (!/\/moment\//.test(context.context)) {
                    return;
                }
                // Working with "moment/src/moment" instead of "moment" requires
                // redirecting "./locale" back to "../../locale".
                Object.assign(context, {
                    // Want all locales, enable this line.
                    // regExp: /^\.\/\w+/,
                    // Just use some locales, enable this line.
                    // regExp: /de|fr|hu/,
                    // Don't use any locales except default "en".
                    regExp: undefined,
                    request: "../../locale",
                });
            }),
            // ...
        ],
        // ...
    };
};
```

**Comment by jfroffice** [comment] 2017-10-20 15:13
+1 to tackle this bundle size problem and ES6 compatibility otherwise moment is already a dead library.

**Comment by davidcalhoun** [comment] 2017-11-21 22:09
I'm not 100% sure how to explain the context in which this is an issue, but it may help someone else.  Right now I have a package which depends on `moment.js` which has a dependency on a different package that depends on `moment.js`.

Both of these packages are build with webpack and include this line:

```js
plugins: [
  new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/)
]
```

However it looks like what's being consumed is the result of `moment.js`'s own Grunt task, which outputs locales to a module defined as `moment/min/locales`, which won't match the regexp above.

You will need something like this instead:

```js
plugins: [
  new webpack.IgnorePlugin(/^moment\/min\/locales$/)
]
```

Another workaround that seems to work is to define `moment/min/locales` as an external:

```js
externals: {
  'moment/min/locales': 'momentLocales'
}
```

**Comment by MickL** [comment] 2018-01-16 15:32
I love moment.js but yes 130kb without locales is way too much for using 1-2 functions out of it. Tree shaking is a MUST HAVE as of today. Will move to date-fns, too.

**Comment by revmischa** [comment] 2018-03-01 16:47
<img width="669" alt="screen shot 2018-03-01 at 18 46 02" src="https://user-images.githubusercontent.com/245131/36857308-e3b5823e-1d80-11e8-9d9a-c27eca32fd47.png">

This is what I see after running everything through UglifyJS

**Comment by davidgoli** [comment] 2018-03-13 18:07
👍 Thanks to this thread for introducing me to [date-fns](https://date-fns.org/)! Moment.js is out, modularity is in!

**Comment by revmischa** [comment] 2018-03-13 18:31
oh yeah, i found a solution:
```
    new webpack.ContextReplacementPlugin(
      /moment[\/\\]locale$/,
      /en|de|fr|es|pl|ua|ru/
    ),
```

**Comment by garygreen** [comment] 2018-03-22 13:37
Thanks @revmischa - this doesn't just work for Moment but also is a good alternative to Webpack's `IgnorePlugin` which I could never get working. Cheers dude 😄

**Comment by amarzavery** [comment] 2018-04-26 23:52
I want to be able to only use moment.js for `duration`? It will be so awesome if I can only require/import the duration module from moment. In web pack after following the above recommendations I still have to take ~60KB of minified moment.js just for validating the duration format. 

Can we please modularize moment? If that is not possible then is there another way to tell web pack to not take the whole library but specific functions and bring source code that only touches those functions.

**Comment by davidgoli** [comment] 2018-04-26 23:57
@amarzavery take a look at https://date-fns.org/ - it's very lightweight & modular and should support the functionality you want.

**Comment by amarzavery** [comment] 2018-04-26 23:59
@davidgoli - Thanks for responding quickly. Here is the [open issue for duration](https://github.com/date-fns/date-fns/issues/284) on date-fns. It is not yet supported.

**Comment by davidgoli** [comment] 2018-04-27 00:12
I'm not sure what all your use cases are, but there *is* limited duration support in date-fns, though not as a first-class concept necessarily. If that's still not what you need, take a look at https://moment.github.io/luxon/docs/class/src/duration.js~Duration.html

**Comment by amarzavery** [comment] 2018-04-27 00:38
Thanks for pointing me to Luxon. This looks promising to me. I will give it a try.
I am primarily looking at following scenarios w.r.t duration:
- serialize a duration object to ISO8601 format
- deserialize the received duration to a Duration object that the user can play with.
- validate whether a given duration object or string adheres to the ISO8601 duration format.

**Comment by baona95** [comment] 2018-06-26 14:23
I'm at a point searching for "slim" moment.js in Google and it leads me to this, so I've found out date-fns, it's a great alternative since I only used 2-3 methods from momentjs.

**Comment by anasanzari** [comment] 2018-06-27 07:42
+1

**Comment by indefinitelee** [comment] 2018-07-18 21:57
can't personally vouch for it but have read about Day.Js as an alternative
https://github.com/iamkun/dayjs

**Comment by mistrykaran91** [comment] 2018-07-24 16:20
I have a folder structure src/app/modules/user-management, I would to exclude the user-management folder in build, I have tried using IgnorePlugin but unable to achieve it, any help will be appreciated. Please.

**Comment by WizardCM** [comment] 2018-09-02 23:12
Just adding my voice, this should definitely be a core focus. Moment is a fantastic library with lots of useful features, but keeping things small is important too.

**Comment by stevemao** [comment] 2018-09-11 00:54
For those who'd like to transition from momentjs to a modern approach, please check out https://github.com/you-dont-need/You-Dont-Need-Momentjs

**Comment by changhuixu** [comment] 2018-09-12 15:01
@stevemao 
big thumb up to https://github.com/you-dont-need/You-Dont-Need-Momentjs

**Comment by MickL** [comment] 2018-09-12 16:03
This issue is now 3 1/2 years old and nothing happened. This is officially the end of moment.js, rest in peace and greet jQuery if you see it.

**Comment by imkimchi** [comment] 2018-09-18 01:48
ggwp

**Comment by janbaykara** [comment] 2018-09-25 10:18
It's depressing, because Moment could have followed D3 in modularising whilst maintaining its position as the go-to date library.

**Comment by mmalomo** [comment] 2019-02-05 20:07
I need this from years ago. I can not believe it is not done yet.
Im changing to moment-mini for the _moment_

https://github.com/ksloan/moment-mini

**Comment by xxyuk** [comment] 2019-02-19 06:02
`Day.Js` is a nice alternative to me

⏰ Day.js 2KB immutable date library alternative to Moment.js with the same modern API

https://github.com/iamkun/dayjs

**Comment by anaibol** [comment] 2019-03-14 15:37
https://inventi.studio/en/blog/why-you-shouldnt-use-moment-js

**Comment by nephi5** [comment] 2020-03-09 20:07
Hi, very interested still in this feature. Any progress made?

**Comment by Carniatto** [comment] 2020-03-11 10:43
@xxyuk is easy to find smaller libs but try to do i18n with these libraries for an example. I'd love to keep using moment but the size is definitely an issue.

**Comment by Carniatto** [comment] 2020-03-12 11:05
@nephi5 @riafowler Since this issue seems to be abandoned, you probably want to check this: https://github.com/you-dont-need/You-Dont-Need-Momentjs

**Comment by renet** [comment] 2020-06-09 07:57
@ichernev Almost every experienced developer I talk to now recommends not using moment.js anymore. The reactions on many threads regarding this topic are pretty clear.

Can you please give us a feedback if you consider (or even already work on) a modularized moment.js package? It seems like you're ignoring this thread - please let us know, if there's a change for a modularized version, or not. Thanks!

**Comment by stevemao** [comment] 2020-06-09 08:05
@renet see https://github.com/you-dont-need/You-Dont-Need-Momentjs

**Comment by MickL** [comment] 2020-06-09 08:30
With date-fns do we really need moment.js anymore?

**Comment by jeffbski-rga** [comment] 2020-06-09 15:01
I typically recommend date-fns these days. I like the fp form myself.

**Comment by marwahaha** [comment] 2020-09-14 23:46
See https://momentjs.com/docs/#/-project-status/

As mentioned before, the moment build without locales is of comparable size to date-fns.

**Closed by marwahaha** 2020-09-14 23:46 UTC
Labels: Enhancement, rewrite

**Comment by MickL** [comment] 2020-09-15 06:17
Instead of solving something, just close the issue 👍🏻

**Comment by tomastan** [comment] 2020-09-15 06:36
I think @marwahaha explained things pretty well in Project status section. At least it is good to know there is no reason to wait for this functionality in Moment.

**Comment by csvan** [comment] 2020-09-16 17:44
@MickL moment.js is effectively dead, there is nothing to solve.

https://www.theregister.com/2020/09/15/moment_js_javascript_library_future/

We are migrating to https://github.com/iamkun/dayjs instead. Almost fully API-compatible with moment and extremely lightweight.

**Comment by LeoEatle** [comment] 2020-09-17 07:15
For webpack project, use this: https://github.com/jmblog/how-to-optimize-momentjs-with-webpack

**Comment by baoanhng** [comment] 2020-09-17 19:05
The project status page effectively explains all the thing.
https://momentjs.com/docs/#/-project-status/

You should move to other libraries if moment.js is not suitable.

**Comment by vugar005** [comment] 2021-08-23 10:54
For anyone in Angular you can use this [simple approach](https://github.com/moment/moment/issues/2416#issuecomment-826097116) to handle this without Extra webpack plugins.
