### ISSUE TITLE
Adding months is confusing

### ISSUE THREAD

**Issue by hendrikswan** [moment/moment#2616] opened 2015-09-17 09:05 UTC
When adding months to a moment instance, it automatically take you to the start of the resulting month. 

In other languages and environments like SQL, when you add a month to a date, it would stay on the same day of the month but move x months into the desired direction. 

For example, let's say I've got a date of `2015-09-17 09:01:15.461Z`. And I want to go 3 months into the past, so I do this: `moment('2015-09-17 09:01:15.461Z').add(-3, 'months').toDate();`. 

I would expect the result to be `2015-06-17 09:01:15.461Z`, but instead it's `2015-06-01 09:01:15.461Z`. 

Why did it go to the first of the month? It doesn't work like that if you do direct month manipulation in JS, or any other languages that I've worked with. 

Is this behaviour by design, or is it a bug? If it's by design, is there a way to override this behaviour?

**Comment by hendrikswan** [comment] 2015-09-17 09:12
I guess one could do something like this (working with current date), but it feels hacky: 

`moment().add(-3, 'months').add(moment().date() -1, 'days').toDate();`

**Comment by stewart42** [comment] 2015-09-17 09:41
I agree, I also expected the same behaviour as described above

**Comment by mj1856** [comment] 2015-09-17 22:02
Sorry, but I can't reproduce this.  What version of moment are you running, and in what browser?

Chrome 45 on Windows with the latest 2.10.6:

![image](https://cloud.githubusercontent.com/assets/1396388/9947188/1637e590-5d4d-11e5-8ad2-7fbd2da064c0.png)

**Comment by mj1856** [comment] 2015-09-17 22:04
@hendrikswan - that's not a good workaround.

**Comment by hendrikswan** [comment] 2015-09-18 13:56
@mj1856 Damn! I was testing it in robomongo, where I had moment loaded and was busy massaging some data. I think robomongo relies on spidermonkey as it's JS engine. 

Sorry, I should've tried running it in node or a browser to give you more information.

**Comment by mj1856** [comment] 2015-09-18 15:33
Let me know if you can reproduce the problem.  I'll close the issue until then.

Thanks.

**Closed by mj1856** 2015-09-18 15:33 UTC
Labels: Troubleshooting
