### ISSUE TITLE
Deprecation warning: moment().add(period, number) is depreciated. Although using correct format: moment().add(number, period)

### ISSUE THREAD

**Issue by MarcErdmann** [moment/moment#2823] opened 2015-12-17 15:18 UTC
This is the code:

	keystone.list('Bewerbung').model.find( function(err, bewerbungen) {
		bewerbungen.forEach( function(bewerbung) {
			if (moment(Date.now()).isAfter(moment(bewerbung.createdAt).add(14,'d'))) {
			bewerbung.state = 'geschlossen';
			};
		});
	});

and I get an error executing it:

deprecation warning: moment().add(period, number) is depreciated. Use moment().add(number, period) instead.

I am using moment 2.10.3 and as you can see keystone.js. My node.js version is 5.1.1.

Can anybody help me please?

**Comment by icambron** [comment] 2015-12-21 00:18
I'm not able to reproduce this. Can you post a JSFiddle showing the problem?

**Comment by MarcErdmann** [comment] 2015-12-23 00:07
I'm sorry I don't know how JSFiddle works..

Is moment.js fully compatible with node.js @ 5.1.1? Because I get the following errors when I try to npm install:

npm warn couldn't install optional dependency: Unsupported
npm engine qunit@0.7.7 wanted node>=0.6.0 < 5.0
npm depreceated esperanto@0.7.5: Esperanto is depreceated...
npm depreceated lodash@0.9.2: is no longer maintained
npm depreceated lodash@1.0.2: is no longer maintained

and karma-qunit @0.1.8 requires qunitjs..

Does anybody know something about that errors?

**Comment by icambron** [comment] 2015-12-23 02:54
It's fully supported, but the compile/dev tooling for it might not be. If you need to bump the version of qunit to make that work, that's fine (and ignore those deprecation warnings).

**Comment by icambron** [comment] 2015-12-23 02:55
On, JSFiddle, a small, self-contained Node script is fine too. I just need something really simple that I can run and see the behavior

**Comment by jbruni** [comment] 2016-03-03 12:34
I am also getting the same deprecation warning, although I am using the recommended arguments order.

**Comment by icambron** [comment] 2016-03-03 18:54
I'm happy to help, but I really need a reproducible example.

**Comment by maggiepint** [comment] 2016-04-01 00:17
Closing. Happy to reopen if you wish.

**Closed by maggiepint** 2016-04-01 00:17 UTC
Labels: Troubleshooting
