### ISSUE TITLE
Parsing a number with 7 characters using moment.ISO_8601 is returning true

### ISSUE THREAD

**Issue by ValterSantosMatos** [moment/moment#3717] opened 2017-01-17 11:07 UTC
Hi there,

Quite simple to reproduce, parsing a number with 7 characters using moment.ISO_8601 is returning true.

Examples:
```js
moment(7000000, moment.ISO_8601, true).isValid(); // true
moment("7000000", moment.ISO_8601, true).isValid(); // true
moment(7000000, moment.ISO_8601, false).isValid(); // true
```
I run directly on the moment.js website

Version
Chrome Version 55.0.2883.95 (64-bit) on OSX

**Comment by mj1856** [comment] 2017-01-17 22:20
Weird.  But reproducible.  Thanks for finding it!

**Comment by marwahaha** [comment] 2017-01-31 15:30
I did some digging. This is since part of the ISO 8601 spec seems to include Ordinal Dates (`YYYY-DDD` or `YYYYDDD`). MomentJS can handle this, including if `YYYYDDD` is a 7-digit number. There still is a bug:  
* When the day is set to zero (as shown in the example) for either `YYYYDDD` or `YYYY-DDD`, the parser evaluates as Valid and sets the day to January 1st.

**Comment by icambron** [comment] 2017-02-08 05:13
Good find @marwahaha. Do you have a suggested fix?

**Comment by marwahaha** [comment] 2017-02-09 08:30
Unfortunately I couldn't figure it out when I looked at it.

Probably, the expected result should be an invalid date.

**Comment by maggiepint** [comment] 2017-02-28 01:32
Closing in favor of #3787

**Closed by maggiepint** 2017-02-28 01:32 UTC
Labels: Bug
