### ISSUE TITLE
Locale returning 'zh-cn' - Chinese (Simplified,) as default locale in 2.18.1

### ISSUE THREAD

**Issue by Gerras** [moment/moment#4116] opened 2017-08-11 17:54 UTC
**Some Info**
I am running karmajs as a testing framework and for some of the specs momentjs is using zh-cn as the default locale.

my package.json file contains: 
"moment": "2.18.1"

`moment.locale()` will return "zh-cn".

when running `moment().format("LL");` I get 2017年6月1日.

setting `moment.locale("en"); fixes the problem.`

**Comment by marwahaha** [comment] 2017-12-11 06:13
Does this happen for all users of Karma?

**Comment by marwahaha** [comment] 2017-12-20 03:00
@Gerras are you still running into this issue in 2.20.1 ?

**Comment by Gerras** [comment] 2017-12-20 16:42
I just checked and the issue is still occurring in 2.20.1
It happens for all of the karma tests that use moment.

**Comment by Gerras** [comment] 2018-01-31 21:05
I think I found out what is causing this. In our project we import all of the moment locales we use separately in a utlis folder. The last import that we do is "moment/locale/zh-cn", if I reorder these imports then whichever is last is the default moment locale.

**Comment by marwahaha** [comment] 2018-04-04 08:13
Cool. That seems like intended behavior - whatever locale (i.e. `zh-cn`) to `moment.locale` (i.e. `moment.locale("zh-cn")` will set the locale.

I will close this for now. Please re-open if you still have issues.

**Closed by marwahaha** 2018-04-04 08:13 UTC
Labels: Troubleshooting
