### ISSUE TITLE
Can't resolve './locale'

### ISSUE THREAD

**Issue by sarazhang123** [moment/moment#5472] opened 2020-04-28 09:14 UTC
**Describe the bug**

When I configure `mainFields` of webpack, it outputs errors.

**To Reproduce**

- Install moment@2.24.0
- Modify webpack config file

    ```js
    {
      resolve: {
        mainFields: ['module', 'jsnext:main', 'browser', 'main'],
      },
    }
    ```
- Use webpack to build bundles
- Output some errors on console

    ```
    WARNING in ./node_modules/moment/src/lib/locale/locales.js
    Module not found: Error: Can't resolve './locale' in 
    '/home/user/workspace/portal/h5v2/node_modules/moment/src/lib/locale'
    @ ./node_modules/moment/src/lib/locale/locales.js
    @ ./node_modules/moment/src/lib/locale/locale.js
    @ ./node_modules/moment/src/moment.js
    @ ../modules/seed/h5v2/main.js
    ```

**Expected behavior**

Webpack build successfully.

**Screenshots**

![image](https://user-images.githubusercontent.com/8096659/80469479-30ba9500-8973-11ea-8436-46a2918919a6.png)

I modified the highlight line below, webpack build successfully.

![image](https://user-images.githubusercontent.com/8096659/80557421-7aee5580-8a09-11ea-9ab9-1b138200d3a1.png)

I think https://github.com/moment/moment/blob/develop/src/lib/locale/locales.js#L78 has some problem.

**Comment by Alanscut** [comment] 2020-04-29 02:25
@sarazhang123 Can you provide a complete example on [stackblitz](https://stackblitz.com/edit)? This a helps a better positioning solution :).

**Comment by nerdroid23** [comment] 2020-04-29 05:49
I also encountered this issue, it happens when I load the new version from the `src` directory
I am working on windows 10, with `webpack:4.36.1`

**Comment by MohsinGhani** [comment] 2020-05-01 18:50
Hello Guys!
I faced the same issue from last few hours and finally I have resolved it through changing moment version.

**Reason:**
_moment release the new version 17 hours ago from 2.24.0 to 2.25.0_

**Solution:**
Step 1: change the versions
- "moment": "2.24.0",
- "moment-timezone": "^0.5.28",

Step 2: If you are using yarn please add resolutions in your package.json file like this
"dependencies" {
 "moment": "2.24.0",
 "moment-timezone": "^0.5.28"
},
"resolutions": {
    "moment": "2.24.0"
 },

Thank You.

**Comment by sezginriggs** [comment] 2020-05-01 19:17
Continues with 2.25.1 too.

**Comment by likhvar** [comment] 2020-05-01 19:27
Same problem over here with 2.25.1!

**Comment by clabough** [comment] 2020-05-01 20:00
WARNING in ./node_modules/moment/src/lib/locale/locales.js
Module not found: Error: Can't resolve './locale'

v2.25.1

**Comment by DaveCole** [comment] 2020-05-01 20:06
All I had to do was update my react project to moment 2.25.1 from 2.4.0 and moment-timezone 0.5.28 from 0.5.26 and the issue presented itself...  I had updated to the react-scripts 3.4.1 from 3.3.0 and react/react-dom 16.13.1 from 16.12.0 at the same time.  What's killing me is that reverting the package.json back and blowing away node_modules and reinstalling didn't fix the issue, now I'm stuck...

**Comment by lucacri** [comment] 2020-05-01 20:13
Same problem for me with 2.25.1

**Comment by mhmtyasr** [comment] 2020-05-01 20:16
How to fix it. Nobody explains.Just waiting.

**Comment by ChrisEddy** [comment] 2020-05-01 20:16
Same issue.

**Comment by tinyfly** [comment] 2020-05-01 20:17
Downgrading to 2.24.0 fixed it for me.

**Comment by MohsinGhani** [comment] 2020-05-01 20:22
> Hello Guys!
> I faced the same issue from last few hours and finally I have resolved it through changing moment version.
> 
> **Reason:**
> _moment release the new version 17 hours ago from 2.24.0 to 2.25.0_
> 
> **Solution:**
> Step 1: change the versions
> 
> * "moment": "2.24.0",
> * "moment-timezone": "^0.5.28",
> 
> Step 2: If you are using yarn please add resolutions in your package.json file like this
> "dependencies" {
> "moment": "2.24.0",
> "moment-timezone": "^0.5.28"
> },
> "resolutions": {
> "moment": "2.24.0"
> },
> 
> Thank You.

Hello @sezginriggs @tinyfly @ChrisEddy @mhmtyasr @lucacri please look it.

**Comment by miguelmota** [comment] 2020-05-01 20:22
Downgrading to the previous minor version (`2.24.0`) works as usual:

```bash
npm install --save --save-exact moment@2.24.0
```

**Comment by agrohs** [comment] 2020-05-01 21:13
Related to: https://github.com/moment/moment/issues/5489 (which somehow seems to have been closed)

**Comment by agrohs** [comment] 2020-05-01 23:25
How can we make sure this works with moment-timezone???

**Comment by agrohs** [comment] 2020-05-01 23:26
https://github.com/moment/moment-timezone/issues/837

**Comment by fransPR** [comment] 2020-05-02 00:14
> 
> 
> Hello Guys!
> I faced the same issue from last few hours and finally I have resolved it through changing moment version.
> 
> **Reason:**
> _moment release the new version 17 hours ago from 2.24.0 to 2.25.0_
> 
> **Solution:**
> Step 1: change the versions
> 
>     * "moment": "2.24.0",
> 
>     * "moment-timezone": "^0.5.28",
> 
> 
> Step 2: If you are using yarn please add resolutions in your package.json file like this
> "dependencies" {
> "moment": "2.24.0",
> "moment-timezone": "^0.5.28"
> },
> "resolutions": {
> "moment": "2.24.0"
> },
> 
> Thank You.

Yes, the problem is the version, Thank for your answer.

**Comment by rhuffy** [comment] 2020-05-02 00:48
I am seeing a similar issue when trying to build my react project on Github Actions CI. No warnings were emitted when building locally. Downgrading to `2.24.0` solved the issue.

**Comment by linxiaowu66** [comment] 2020-05-02 02:43
same issue with 2.25.1

**Comment by yuanshengbug** [comment] 2020-05-02 02:59
> 大家好！
> 最近几个小时我都遇到了同样的问题，最后我通过更改时间版本解决了它。
> 
> **原因：**
> _在17小时前将新版本从2.24.0发行到2.25.0_
> 
> **解决方案：**
> 步骤1：更改版本
> 
> * “ moment”：“ 2.24.0”，
> * “ moment-timezone”：“ ^ 0.5.28”，
> 
> 步骤2：如果您使用的是yarn，请在package.json文件中添加分辨率，例如
> “ dependencies” {
> “ moment”：“ 2.24.0”，
> “ moment-timezone”：“ ^ 0.5.28”
> }，
> “ resolutions” ：{
> “ moment”：“ 2.24.0”
> }，
> 
> 谢谢。
不行啊

**Comment by m2mathew** [comment] 2020-05-02 04:22
2.25.1 presents the "locale" issue, as others have stated. When I use exactly `2.24.0` it works correctly.

**Comment by B2D1** [comment] 2020-05-02 05:14
same problem happened in v2.25.1，then I try to add
```json
"dependencies" {
  "moment": "2.24.0",
},
"resolutions": {
  "moment": "2.24.0"
},
```

**Comment by B2D1** [comment] 2020-05-02 05:14
same problem happened in v2.25.1，then I try to add
```json
"dependencies" {
  "moment": "2.24.0",
},
"resolutions": {
  "moment": "2.24.0"
},
```

**Comment by rrrix** [comment] 2020-05-02 07:09
I went with this bandaid:
```json
  "dependencies: {
      "moment": "^2 <2.25 || ^2 >2.25",
  }
```
This avoids forever version pinning to `moment@2.24.0` until the end of time, with the assumption (hope?) that this gets fixed by the time `moment@2.26.0` rolls out, and if not then it'll remind me to check this thread :) tip: try [semver.npmjs.com](https://semver.npmjs.com/)!

**Comment by yuanshengbug** [comment] 2020-05-02 07:13
Thanks, that's it




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "B2D1"<notifications@github.com&gt;; 
发送时间: 2020年5月2日(星期六) 中午1:15
收件人: "moment/moment"<moment@noreply.github.com&gt;; 
抄送: "喜欢一个人"<383028387@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [moment/moment] Can&#39;t resolve &#39;./locale&#39; (#5472)





 
same problem happened in v2.25.1，then I try to add
 "dependencies" {   "moment": "2.24.0", }, "resolutions": {   "moment": "2.24.0" },

**Comment by scottgale** [comment] 2020-05-02 08:02
I'm really surprised this was released with this broken.  It breaks everyone's web pack.  Is there an instance for someone where this works properly?  Are we not testing web pack builds?

**Comment by tonix-tuft** [comment] 2020-05-02 09:12
I can confirm what others have stated, `2.25.1` breaks with `Can't resolve './locale'` warning. Downgrading to `2.24.0` works, but binds projects to a specific version of moment...

**Comment by sarazhang123** [comment] 2020-05-02 09:42
The root cause is version 2.24.0 only has `main` and `jsnext:main` fields in package.json, but 2.25.1 has `main`, `jsnext:main` and `module` fields. Webpack has default `mainFields` config includes  `module` and `main`. When import moment, in 2.24.0, use entry file of `main` field, but in 2.25.1, use `module` field and then the warning occurs. In other words, the  bug existed all the time and exposed until 2.25.0 was released.

```
{
  "version": "2.24.0",
  "main": "./moment.js",
   "jsnext:main": "./src/moment.js",
}
```

```
{
  "version": "2.25.1",
   "main": "./moment.js",
    "jsnext:main": "./src/moment.js",
    "module": "./src/moment.js",
}
```

**Comment by tonix-tuft** [comment] 2020-05-02 09:59
@sarazhang123 This is indeed a workaround, not real fix, as far as I am concerned.
Consumers of a package shouldn't really care about tweaking their module bundler's config in order to make a package work... At least the package provides some additional features which require changing the config.

Just to know, where did you put these lines:

```js
{
  "version": "2.25.1",
   "main": "./moment.js",
   "jsnext:main": "./src/moment.js",
   "module": "./src/moment.js",
}
```

?

Will wait for a `minor` or `patch` version of `moment` fixing this.

**Comment by tinyfly** [comment] 2020-05-02 13:50
@tonix-tuft You don’t put that anywhere, that is just Showing you what is in moment’s own package.json. The temporary fix is to downgrade to 2.24.0

**Comment by tonix-tuft** [comment] 2020-05-02 15:38
@tinyfly Yeah, I screwed it up 😆 . Didn't understand what @sarazhang123 meant, now I got it.

**Comment by J1445** [comment] 2020-05-02 18:16
This project is great and awesome but  releases from moment is absolutely not cool :( . I made a mistake by allowing the moment to pick up latest version in master now. I don't have access to change it back in master  and I badly regret my behavior of doing so because I didn't knew moment never  used to run test build for edge cases like this

**Comment by adjilla** [comment] 2020-05-02 18:20
> Hello Guys!
> I faced the same issue from last few hours and finally I have resolved it through changing moment version.
> 
> **Reason:**
> _moment release the new version 17 hours ago from 2.24.0 to 2.25.0_
> 
> **Solution:**
> Step 1: change the versions
> 
> * "moment": "2.24.0",
> * "moment-timezone": "^0.5.28",
> 
> Step 2: If you are using yarn please add resolutions in your package.json file like this
> "dependencies" {
> "moment": "2.24.0",
> "moment-timezone": "^0.5.28"
> },
> "resolutions": {
> "moment": "2.24.0"
> },
> 
> Thank You.

Thank you, you save my day 👍

**Comment by yosiawan** [comment] 2020-05-03 09:15
I ran into similar issue with my React app. It started showing up about 1 - 2 days ago. The app was running fine in production env when one of our user reports that it stops working in iOS. After checking it for myself, this is the error message that I got:
```
Uncaught Error: Cannot find module './locale'
    at 2.b2c08f26.chunk.js:2
    at Object.<anonymous> (2.b2c08f26.chunk.js:2)
    at c ((index):1)
    at Module.455 (main.845efadd.chunk.js:1)
    at c ((index):1)
    at Object.295 (main.845efadd.chunk.js:1)
    at c ((index):1)
    at t ((index):1)
    at Array.r [as push] ((index):1)
    at main.845efadd.chunk.js:1
```

I have tried using v 2.18 and v. 2.24 with no luck. 
I also noticed that this only happens in the following environment:

- MacOS
-- Safari (Version 13.0.5 (15608.5.11))
-- Chrome (Version 80.0.3987.149 (Official Build) (64-bit))

-iOS
-- Safari 
-- Chrome 

Linux Manjaro 
-- Chrome

These are my dependencies
```
"dependencies": {
    "@livechat/ui-kit": "^0.4.0-5",
    "@material-ui/core": "^4.5.2",
    "@material-ui/icons": "^4.5.1",
    "@material-ui/lab": "^4.0.0-alpha.39",
    "@sentry/browser": "^5.5.0",
    "analytics-js-without-segment": "^1.0.0",
    "apollo-boost": "^0.4.3",
    "apollo-client": "^2.6.4",
    "apollo-link-error": "^1.1.12",
    "apollo-link-retry": "^2.2.15",
    "apollo-link-ws": "^1.0.18",
    "apollo-upload-client": "^11.0.0",
    "clsx": "^1.0.4",
    "date-fns": "^1.30.1",
    "graphql": "^14.5.4",
    "graphql-tag": "^2.10.1",
    "lodash": "^4.17.15",
    "moment": "^2.18.0",
    "prop-types": "^15.7.2",
    "react": "^16.12.0",
    "react-apollo": "^3.1.3",
    "react-dom": "^16.12.0",
    "react-infinite-scroller": "^1.2.4",
    "react-linkify": "^1.0.0-alpha",
    "react-router": "^5.1.2",
    "react-router-dom": "^5.1.2",
    "react-toastify": "^5.5.0",
    "react-window": "^1.8.5",
    "subscriptions-transport-ws": "^0.9.16",
    "uuid": "^3.3.3"
  },
  "devDependencies": {
    "@apollo/react-testing": "^3.1.0",
    "@testing-library/react": "^9.3.0",
    "@types/apollo-upload-client": "^8.1.3",
    "@types/date-fns": "^2.6.0",
    "@types/enzyme": "^3.9.3",
    "@types/enzyme-adapter-react-16": "^1.0.5",
    "@types/jest": "23.3.13",
    "@types/lodash": "^4.14.144",
    "@types/material-ui": "^0.21.6",
    "@types/node": "10.12.18",
    "@types/prop-types": "^15.7.3",
    "@types/react": "^16.9.2",
    "@types/react-dom": "^16.9.0",
    "@types/react-infinite-scroller": "^1.2.1",
    "@types/react-linkify": "^1.0.0",
    "@types/react-router": "^5.1.3",
    "@types/react-router-dom": "^4.3.5",
    "@types/uuid": "^3.4.5",
    "enzyme": "^3.10.0",
    "enzyme-adapter-react-16": "^1.14.0",
    "enzyme-to-json": "^3.3.5",
    "node-sass-chokidar": "^1.3.5",
    "npm-run-all": "^4.1.5",
    "react-scripts": "^3.3.0",
    "redux-devtools-extension": "^2.13.8",
    "tslint": "^5.14.0",
    "typescript": "^3.7.2"
  },
```
PS: Will update with more info when available

**Comment by steven-r** [comment] 2020-05-03 09:49
> The root cause is version 2.24.0 only has `main` and `jsnext:main` fields in package.json, but 2.25.1 has `main`, `jsnext:main` and `module` fields. Webpack has default `mainFields` config includes `module` and `main`. When import moment, in 2.24.0, use entry file of `main` field, but in 2.25.1, use `module` field and then the warning occurs. In other words, the bug existed all the time and exposed until 2.25.0 was released.
> 
> 2.24.0 package.json
> 
> ```
> {
>   "version": "2.24.0",
>   "main": "./moment.js",
>   "jsnext:main": "./src/moment.js",
> }
> ```
> 
> 2.25.1 package.json
> 
> ```
> {
>   "version": "2.25.1",
>    "main": "./moment.js",
>    "jsnext:main": "./src/moment.js",
>    "module": "./src/moment.js",
> }
> ```
> 
> One of workaround is use `resolve.alias` of webpack to change the entry file when import moment.

This doesn't really help if the bundle engine is encapsulated inside other packages (e.g. react-script). 

Maybe it's a good idea to move release magic with breaking changes towards a new major release...

**Comment by mrFANRA** [comment] 2020-05-03 10:07
Some problem ... downgraded to 2.24.0 =(

**Comment by Sravan-Nayini** [comment] 2020-05-03 10:47
facing the same issue. Latest moment version causing  issues in many websites . moment team please fix it asap.

**Comment by chandra-devs** [comment] 2020-05-03 13:13
These steps worked for me

```
npm install --save-dev npm-force-resolutions

add in package.json
 "resolutions": {
    "moment": "2.24.0"
 }
```
Add to "scripts" node in package.json
```
"preinstall": "npx npm-force-resolutions"
Type npm install
```

**Comment by NathanChannon** [comment] 2020-05-03 13:19
I also have an open ticket for this. If you're able to use Yarn, then using package.json "resolutions" is your way out.

If you're using npm, then you can use this npm-force-resolutions to accomplish the same result, but beware you must reference momentjs in the dependencies if you weren't already.

**Comment by guifeliper** [comment] 2020-05-04 08:47
> Hello Guys!
> I faced the same issue from last few hours and finally I have resolved it through changing moment version.
> 
> **Reason:**
> _moment release the new version 17 hours ago from 2.24.0 to 2.25.0_
> 
> **Solution:**
> Step 1: change the versions
> 
> * "moment": "2.24.0",
> * "moment-timezone": "^0.5.28",
> 
> Step 2: If you are using yarn please add resolutions in your package.json file like this
> "dependencies" {
> "moment": "2.24.0",
> "moment-timezone": "^0.5.28"
> },
> "resolutions": {
> "moment": "2.24.0"
> },
> 
> Thank You.


What solved for me was:
1. rm -rf node_modules
2. change manually the package.json with the quote comment.  (dependencies and resolutions)
3. yarn install.

**Comment by ichernev** [comment] 2020-05-04 12:38
2.25.2 should address this. You might need to change your webpack configuration if you don't want the locale files to be auto-bundled.

**Closed by ichernev** 2020-05-04 12:38 UTC

**Comment by cjmaynar** [comment] 2020-05-04 13:57
I'm continuing to see issues this morning. The build succeeds with no errors that I can see, however my application is not loading and the console is reporting:

![image](https://user-images.githubusercontent.com/1915800/80973547-8668c480-8ded-11ea-8717-71137ea187fe.png)

I'm using 

```
"moment": "^2.25.2",
"moment-timezone": "^0.5.28",
```

I've deleted my node_modules and package-lock.json file to do a fresh install

**Comment by AielloChan** [comment] 2023-02-18 12:22
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/7900765/219865387-788e2601-1a17-40a0-895f-d367f9a313c5.png">

Because of moment's dynamic require locate files, the require statement still use relative path, even in mermaid, thus can't find './locate' files.

Mermaid shouldn't pack "moment" in its dist file! Just keep require node_modules module.

**Comment by abramovks** [comment] 2023-04-07 01:58
import like this solved for me

"moment": "^2.29.4"

import * as moment from 'moment'
import 'moment/locale/ru'
moment.locale('ru')

**Comment by dimaslanjaka** [comment] 2023-09-25 07:25
i was changed aliasesRequire in `moment/min/moment-with-locales.js` from

```js
            require('./locale/' + name);
            // because defineLocale currently also sets the global locale, we
            // want to undo that for lazy loaded locales
```

to

```js
            require('moment/locale/' + name);
            // because defineLocale currently also sets the global locale, we
            // want to undo that for lazy loaded locales
```

and now works without error `No Module ./locale` while compiling and on production
