### ISSUE TITLE
Make code samples on momentjs.com selectable

### ISSUE THREAD

**Issue by laggingreflex** [moment/moment#3718] opened 2017-01-18 07:25 UTC
**Description of the Issue and Steps to Reproduce:**

On the website, momentjs.com, there are handy little code samples like `moment().format('LT')` that I like to select one of them quickly to paste it in my code. 

But when I select it, the javascript running on the page that updates the time every second, makes you lose the selection.

![moment](https://cloud.githubusercontent.com/assets/2523987/22054742/322ca0ea-dd7d-11e6-93ba-6d9479d95a3d.gif)

**Comment by maggiepint** [comment] 2017-01-18 11:54
Dupe of moment/momentjs.com#158

Pull request welcome on that one given it's existed since 2014 :-)

**Closed by maggiepint** 2017-01-18 11:54 UTC
