### ISSUE TITLE
Diff month for months with a different number of days

### ISSUE THREAD

**Issue by MaxAnikin** [moment/moment#3029] opened 2016-03-10 10:57 UTC
Hello,

I am trying to get diff in months between months with a different number of days. 
Let's say "Jan, 31, 2016" and "Feb, 29, 2016". Both dates are last days in the months. 

End even more. You will get "Feb, 29, 2016" date if you use "add" function and add exact 1 month to the "Jan, 31, 2016". But current version displays strange diff resutls.

A have prepared two fiddles:
1. v2.12.0 - https://jsfiddle.net/Maksym_Anikin/q94s0w92/2/ - this version displays strange results
2. v1.7.2 - https://jsfiddle.net/Maksym_Anikin/r489ync9/7/ - this version works as expected!

Issues:. 
1. Current version returns different results if you switch start and end dates which is incorrent. Both variants should return the same number.
2. When you run diff starting from the "Feb, 29, 2016" it returns 0. Which is incorrect. Should be 1 since you got this date by adding 1 month. Logically you must get diff results equal to 1.

**Comment by mj1856** [comment] 2016-03-10 17:13
Yes, date math is weird.  Months aren't a discrete unit of time.  Consider:

```javascript
moment("2016-01-31").add(1, 'month').subtract(1, 'month').format('YYYY-MM-DD')
//  outputs: "2016-01-29"
```

For the `diff` function, the order of the dates is important, and is called out [in the docs](http://momentjs.com/docs/#/displaying/difference/).   You should not expect the same results if the dates are in reverse order.

However, I think I'll agree with you about one part of this:

```javascript
moment("2016-02-29").diff("2016-01-29", "months")  // 1
moment("2016-02-29").diff("2016-01-30", "months")  // 0, should be 1
moment("2016-02-29").diff("2016-01-31", "months")  // 0, should be 1
```

Because of the variability of the length of a month, the end of the month should probably be special case in the `diff` function.

Note that we're already doing this with regard to years being variable length, so IMHO, we should be consistent.

```javascript
moment("2016-02-29").diff("2015-02-28", "years") // 1
```

**Comment by diegoavidal** [comment] 2016-05-31 15:55
Yep, today some tests failed because this issue
When I add one month in a date, and after that compare with diff method, the result is unexpected
Example:
`var date = moment('2016-05-31').add(1,'month');
date.diff(moment('2016-05-31'), 'month'); // 0, should be 1`

**Comment by Plopsi** [comment] 2016-10-07 12:45
There are more issues ie. with diff:

```javascript
moment('2016-09-30').diff(moment('2016-12-31'), 'month', true)  //-3.032258064516129 -> correct
moment('2016-12-31').diff(moment('2016-09-30'), 'month', true)  //3 -> not correct
```

**Comment by philwhln** [comment] 2017-05-12 21:38
We're also hitting this across our sites.

```
moment('2017-11-30T15:00:00-07:00').diff(moment('2017-05-31T15:00:00-07:00'), 'months')
```

Should equal `6`, but equals `5`.

**Comment by Xtigyro** [comment] 2017-07-12 18:30
Hi folks - is there any fix for this or a workaround?

`var curr_month_day = moment();
                        var prev6_month_start = moment().subtract(6, 'months').startOf('month');
                        var prev6_month_end = moment().subtract(6, 'months').endOf('month');
                        var Dur_prev6_month_start = moment.duration({ from: curr_month_day, to: prev6_month_start });
                        var Dur_prev6_month_end = moment.duration({ from: curr_month_day, to: prev6_month_end });`

This code returns absolutely messed up start and end of Jan 2017 (currently) because it appears that the different number of days in Feb is the root cause in this case.

**Comment by Xtigyro** [comment] 2017-07-13 09:25
Folks - I found a workaround though I completely removed the lines of 'Moment.js' and I started using just a bit 'Date.js' and normal JavaScript.

This is the fix:

`var curr_month_day = new Date (), y = curr_month_day.getFullYear(), m = curr_month_day.getMonth(), d = curr_month_day.getDate();
                    console.log(m)

                    var prev6_month_begin = new Date(y, m - 6).clearTime().moveToFirstDayOfMonth();
                    var prev6_month_end = new Date(y, m - 6).clearTime().moveToLastDayOfMonth();
                    console.log(prev6_month_begin)
                    console.log(prev6_month_end)
                    var timeDiff = Math.abs(curr_month_day.getTime() - prev6_month_begin.getTime());
                    var Dur_prev6_month_start = Math.ceil(timeDiff / (1000 * 3600 * 24));
                    console.log(Dur_prev6_month_start);

                    var timeDiff = Math.abs(curr_month_day.getTime() - prev6_month_end.getTime());
                    var Dur_prev6_month_end = Math.ceil(timeDiff / (1000 * 3600 * 24));
                    console.log(Dur_prev6_month_end);`

**Comment by janudewangga** [comment] 2019-05-25 08:57
`Math.ceil(moment(datetime1).diff(moment(datetime2), 'months', true))`

**Comment by ichernev** [comment] 2020-04-27 02:30
I know this is very touchy subject, but:
1) it does NOT have special handling for years, it's just that there are 4 possible cases, and it on of it it "breaks":
```
> moment("2015-02-28").diff("2012-02-29", "years", true) 
2.997122302158273
> moment("2015-02-28").diff("2012-02-29", "years") 
2
```
2) changing floor to ceil is not going to work:
```
> moment("2015-02-28").diff("2016-02-29", "years", true) 
-1.0028776978417266
```
Not to mention that basically everything will be broken now -- a range slightly higher than a month will be considered as 2 months, and not just months, but everything.

3) The only thing which might make sense it to set specific thresholds for rounding up (like if its above .95 round up),  which will be approximate to 1 day. Of course this will break in cases like Jan-15 to Feb-14, but then again we have a floating point which you can abuse all the way you want.

This is the simplest explanation I can give:
* [1st Feb - 1st Mar] is 1 month
* [1st Feb - X (any date in Feb)] + [X - 1st Mar] is 1 month

From the above two the current formula follows. It tries to be locally linear. It can't be globally linear because months themselves are not linear (1st Feb to 1st Mar being 1 month is not the same as 1st Mar to 1st Apr being 1 month). Also any changes made will break even local linearity.

The above holds for any start/end dates `a`, `b` such as `a.add(1, 'month') == b`.

**Closed by ichernev** 2020-04-27 02:30 UTC
Labels: Bug, Up-For-Grabs
