### ISSUE TITLE
1 test failed. relative time:custom rounding (2721.3) 

### ISSUE THREAD

**Issue by jdforsythe** [moment/moment#3823] opened 2017-03-10 21:15 UTC
### Client info
```
Date String   : Fri Mar 10 2017 16:15:34 GMT-0500 (Eastern Standard Time)
Locale String : 3/10/2017, 4:15:34 PM
Offset        : 300
User Agent    : Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
Moment Version: 2.17.1
```

====

### relative time:custom rounding (2721.3) 

Round down towards the nearest day

```javascript
// Expected in 30 days
// Actual   in a month
"in a month" === "in 30 days"
```

**Comment by icambron** [comment] 2017-03-12 13:34
Thanks for posting this. Closing as a duplicate of #3801

**Closed by icambron** 2017-03-12 13:34 UTC
