### ISSUE TITLE
isValid returns true if param is `undefined`

### ISSUE THREAD

**Issue by lucasjorge944** [moment/moment#4947] opened 2019-01-14 19:34 UTC
**Describe the bug**
The function to validate the `date` returns `false` when the `date` is `undefined`.

**To Reproduce**
`const date = undefined;
console.log(moment(date).isValid()) // returns true
`

**Expected behavior**
It is expected that when the `date` is undefined the returns is `false`

**Comment by marwahaha** [comment] 2019-01-17 09:11
duplicate of https://github.com/moment/moment/issues/1639

**Closed by marwahaha** 2019-01-17 09:11 UTC
