### ISSUE TITLE
Executing `isValid ()` gets strange results!

### ISSUE THREAD

**Issue by Alanscut** [moment/moment#5464] opened 2020-04-26 09:41 UTC
**Describe the issue**
Executing `isValid ()` gets strange results, I am not sure if this is a bug.

**To Reproduce**
```javascript
import moment from 'moment';

console.log('YYYY-MM-DD', moment('2012-05-5', 'YYYY-MM-DD', true).isValid())   // false
console.log('YYYY-MM-DD', moment('2012-05-5', 'YYYY-MM-D', true).isValid())   // true
console.log('YYYY-MM-D', moment('2012-05-05', 'YYYY-MM-D', true).isValid()); // true
console.log('YYYY-MM-D', moment('2012-05-05', 'YYYY-MM-DD', true).isValid()); // true
```

**Desired result**
```
console.log('YYYY-MM-DD', moment('2012-05-5', 'YYYY-MM-DD', true).isValid())   // false
console.log('YYYY-MM-DD', moment('2012-05-5', 'YYYY-MM-D', true).isValid())   // true
console.log('YYYY-MM-D', moment('2012-05-05', 'YYYY-MM-D', true).isValid()); // false
console.log('YYYY-MM-D', moment('2012-05-05', 'YYYY-MM-DD', true).isValid()); // true
```

**Moment-specific environment**

Please run the following code in your environment and include the output:
```javascript
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)

Sun Apr 26 2020 17:37:18 GMT+0800 (中国标准时间)
VM177:2 2020/4/26 下午5:37:18
VM177:3 -480
VM177:4 Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36
2.24.0
```

**Comment by marwahaha** [comment] 2020-05-12 12:56
duplicate of #5314

**Closed by marwahaha** 2020-05-12 12:56 UTC
