### ISSUE TITLE
IE11 moment js date formatting for mm/dd/yyyy gives a correct date for invalid input 45/45/1

### ISSUE THREAD

**Issue by kunchamwarp** [moment/moment#3972] opened 2017-05-23 10:35 UTC
**Description of the Issue and Steps to Reproduce:**
moment('45/45/1', 'MM/DD/YYYY').format('MM/DD/YYYY') returns a valid date instead of NAN

*Please include the values of all variables used.*

**Environment:**
*Internet Explorer 11 on Windows 7, Please see the screenshot.
![ie11-date](https://cloud.githubusercontent.com/assets/11211219/26350659/9bcd075e-3fd1-11e7-9c56-d1c8b2649950.PNG)

'45/45/1' result in 10/15/0004 which is valid date.

*Both the browser and the OS are important to us, particularly if you have an unsual environment like an IOT application.*

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
Tue May 23 2017 16:34:13 GMT+0530 (India Standard Time)
console.log((new Date()).toLocaleString())
‎5‎/‎23‎/‎2017‎ ‎4‎:‎34‎:‎29‎ ‎PM
console.log( (new Date()).getTimezoneOffset())
-330
console.log( navigator.userAgent)\
Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3; rv:11.0) like Gecko
console.log(moment.version)
2.0.0
```

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Comment by neroux** [comment] 2017-05-23 11:04
Duplicate of #3949

**Comment by kunchamwarp** [comment] 2017-05-23 11:23
More Details are available here.

**Comment by neroux** [comment] 2017-05-23 11:37
> More Details are available here in this issue for reference.

It would be better to add those details to the original issue.

**Comment by kunchamwarp** [comment] 2017-05-23 12:39
@neroux updated it original issue. But the issue is closed. is there any way we can open the issue.

**Comment by mj1856** [comment] 2017-05-23 19:27
There's nothing wrong.  Update to current version and all works.

**Closed by mj1856** 2017-05-23 19:27 UTC
