### ISSUE TITLE
Cannot update momentjs:moment meteor package

### ISSUE THREAD

**Issue by admeister** [moment/moment#3123] opened 2016-04-18 18:51 UTC
When performing meteor update I get the following message:

```
=> Errors while upgrading packages:           
                                              
While checking for momentjs:moment@2.13.0:
error: No compatible binary build found for this package. Contact the package
author and ask them to publish it for your platform.
```

I am on OS X 10.11.4

**Comment by eduk79** [comment] 2016-04-18 19:20
Having the same problem! Just updated to Meteor 1.3.2.2

**Comment by mlecoq** [comment] 2016-04-18 20:24
+ 1 !

**Comment by zenonn37** [comment] 2016-04-19 10:29
+1

**Comment by maggiepint** [comment] 2016-04-19 11:51
Closing this as a duplicate of #3130. We haven't forgotten you, I promise. We just don't need two issues.

**Closed by maggiepint** 2016-04-19 11:51 UTC

**Comment by De-Lac** [comment] 2016-04-19 12:57
+1
