### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by nue1000** [moment/moment#4968] opened 2019-01-23 06:28 UTC
(node:12712) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated
I got a warning when I run moment,how can i fix it.thanks.

**Comment by marwahaha** [comment] 2019-01-24 07:41
Thanks for opening this request.

It's a warning, so you can still use moment. It's a duplicate of https://github.com/moment/moment/issues/4639 .

Anyone is welcome to fix this: it's "Up-for-Grabs".

**Closed by marwahaha** 2019-01-24 07:41 UTC

**Comment by nue1000** [comment] 2019-01-25 07:44
Thank you for the reply. I am a new here,there's a long way for me to go.
