### ISSUE TITLE
"undefined" in ukrainian locale

### ISSUE THREAD

**Issue by Torondor27** [moment/moment#3978] opened 2017-05-25 14:48 UTC
When i'm set localization to "uk", in drop down menu i got "undefined" instead of month name. Got this bug in datetimepicker, in datepicker all works fine
(sorry for my english)

Environment: Node.JS v7.8.0 on Ubuntu 16.0.4

console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)

Result:
Thu May 25 2017 17:49:38 GMT+0300 (EEST)
5/25/2017, 5:49:38 PM
-180
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36
2.10.3

**Comment by icambron** [comment] 2017-05-28 17:12
You'll need to whittle this down to some code that uses Moment directly. For example, if you open the JS console on [this page)(http://momentjs.com/docs/), you'll get this:

```js
moment().locale('uk').locale(); //=> "uk"
moment().locale('uk').format("MMMM") //=> "травень"
moment().locale('uk').format("MMM") //=> "трав"
```

Can you demonstrate the issue with something similar?

It's possible that your locales aren't loaded (i.e. you're not using a build of Moment that even has Ukrainian or some similar problem). You're also using a pretty old version of Moment. In any case, the information you've provided isn't enough to help.

**Comment by Torondor27** [comment] 2017-05-29 13:54
Thanks for reply! I'm using such old version of moment because it's build in version in  [laravel backpack](https://github.com/Laravel-Backpack), but i think it's not problem of this package because moment locales are included by link. Here my output of code your provided:

`moment().locale('uk').locale(); //=> "uk"`
`moment().locale('uk').format("MMMM") //=> "undefined"`
`moment().locale('uk').format("MMM") //=> "трав"`

**Comment by icambron** [comment] 2017-05-29 16:51
That's odd. I grabbed 2.10.3 and ran that code. It worked as expected. You can see it here: https://jsfiddle.net/wcwjvq4y/. So there must be something odd going on with your environment. I'm not sure how else to help, since I can't reproduce it.

**Comment by icambron** [comment] 2017-06-14 17:25
Closing for age.

But a though occurred to me: are you sure the locales you're linking to are from the same version of Moment?

**Closed by icambron** 2017-06-14 17:25 UTC
Labels: Troubleshooting
