### ISSUE TITLE
moment returnning null for "3/30/2017 14:55:10.60"

### ISSUE THREAD

**Issue by Godrules500** [moment/moment#4174] opened 2017-09-15 15:12 UTC
moment("3/30/2017 14:55:10.60") returns null, but moment("3/30/2017 14:55:10.60", "MM/DD/YYYY") returns the correct amount.

environment : Java Rhino

I am working in an ERP system called netsuite and have a REST api that is using moment. When it calls the above, it is returning null.

**Comment by icambron** [comment] 2017-09-15 15:17
It does not return `null`; it returns a Moment object that's marked as invalid. It also prints a deprecation warning that you should read.

**Comment by Godrules500** [comment] 2017-09-15 16:08
Mine is actually returning null. I do have an update though, it is in Java Rhino environment

**Comment by icambron** [comment] 2017-09-15 21:24
Hmm, OK, can you provide a reproduceable example? And what version of Moment are you running?

**Comment by icambron** [comment] 2017-09-19 22:26
It's possible there's a Rhino-specific issue here, but since I don't know anything about Rhino, I'm not sure how to help. Perhaps SO can help?

I'm going to close this for age. If you find you need to patch Moment, of course we'll take a PR.

**Closed by icambron** 2017-09-19 22:26 UTC
