### ISSUE TITLE
moment.d.ts is not compatible with 'none' module compiler option

### ISSUE THREAD

**Issue by zVolodymyr** [moment/moment#3663] opened 2016-12-15 15:15 UTC
I have web application that doesn't use any kind of modules, tsconfig.json -> `compilerOptions { "module": "none" }`. I tried to use declaration file from package with it, but always get `error TS2304: Cannot find name 'moment'`.

**Steps to reproduce:**

create application folder 
add typescript config and set `compilerOptions { "module": "none" }` in  tsconfig.json
add moment package via npm
add `main.ts` with some "moment" code (example:` console.log(moment.version)` )
try build with tsc 
error TS2304 occurred

copy moment.d.ts to application folder
try build with tsc 
error TS2304 occurred

add `///<reference path='./moment.d.ts'/>`
try build with tsc 
error TS2304 occurred

**Environment:**
npm: 3.10.9
typescript: 2.1.4
moment: 2.17.1

**Notes:**
Declaration file from the typings works well, and moment it's the only package why I'm still using typings in my project. I checked what the difference is and difference is how they export moment. Instead of `export moment` they use `declare module "moment" { export moment; }`

**Comment by Venryx** [comment] 2016-12-28 11:11
What worked for me is to replace the ```export = moment;``` line in the d.ts file with ```export default moment;```.

This fixes the "module has no default export" error for me in the files which use the module (by means of ```import moment from "moment";```), and provides full intellisense.

In contrast, the solution at the very end of the post above provides the intellisense, but causes a "declaration or statement expected error" error for me inside the moment.d.ts file itself.
*==========
So we must be using different versions of TypeScript, or a different module import scheme, since my errors/solutions are different.

My TypeScript: 2.1.4
My .tsconfig:
```
{
    "compilerOptions": {
        "target": "es2015",
        "allowJs": true,
        "jsx": "react",
        "noImplicitAny": false,
        "moduleResolution": "node",
        "watch": true,
        //...
    },
    // ...
}
```

**Comment by strohhut** [comment] 2017-01-17 15:22
For googlers: Changing `export = moment;` in the declaration to

```
declare module "moment" {
    export = moment;
}
```
works. (OP forgot the equals char)

**Comment by maggiepint** [comment] 2017-02-09 03:01
Given the staleness, I'm going to assume that the comment answered your question. Let me know if it didn't.

**Comment by strohhut** [comment] 2017-02-09 10:27
@maggiepint I don't think that this issue is a question. I think that moment`s declaration file should be changed so that it can work without any module system.

**Comment by zVolodymyr** [comment] 2017-02-09 11:09
I'm not looking for answer, because I mentioned the same in Notes section. I would like to see this changes in moment's declaration.

**Comment by Karankang007** [comment] 2017-03-21 20:33
This issue is still not fixed. Why is this bug closed?

**Comment by marwahaha** [comment] 2017-03-22 03:09
I'll re-open this, but the solution needs to be Typescript 1.x compatible and non-breaking.

For Moment.js 3.x (coming soon!) we will support Typescript 2.x and can do some breaking changes.

**Comment by marwahaha** [comment] 2017-03-29 07:00
Closing this as it is a duplicate of #3763 which has more traffic . We still do need a fix!

**Closed by marwahaha** 2017-03-29 07:00 UTC
Labels: TypeScript
