### ISSUE TITLE
TypeError: config._d.getTime is not a function. (In 'config._d.getTime()', 'config._d.getTime' is undefined)

### ISSUE THREAD

**Issue by lc3t35** [moment/moment#5011] opened 2019-02-19 22:23 UTC
**Describe the bug**

This error pops up : `TypeError: config._d.getTime is not a function. (In 'config._d.getTime()', 'config._d.getTime' is undefined)`

- node_modules/moment/moment.js:238:47 in Moment
- node_modules/moment/moment.js:3202:26 in clone
- node_modules/moment/moment.js:3332:22 in toISOString

**To Reproduce**
no idea yet how to reproduce ...

**Expected behavior**
It should work as previously with version 2.23.0

**Screenshots**
![img_0580](https://user-images.githubusercontent.com/921372/53051892-9bce2900-349d-11e9-8ca8-1b0c9d64c67f.PNG)

**Smartphone (please complete the following information):**
 - Device: iPhone5S
 - OS: ios 11.4.1

**Moment-specific environment**

"moment": "2.24.0" within expo sdk22 app

**Additional context**
`
TypeError: config._d.getTime is not a function. (In 'config._d.getTime()', 'config._d.getTime' is undefined)

This error is located at:
    in FameMore (at connectAlert.js:11)
    in ConnectedAlert (at withNavigation.js:17)
    in withNavigation(ConnectedAlert) (created by Connect(withNavigation(ConnectedAlert)))
    in Connect(withNavigation(ConnectedAlert)) (at FameTop.js:122)
    in RCTView (at View.js:44)
    in FameTop (at withNavigation.js:17)
    in withNavigation(FameTop) (at connectAlert.js:11)
    in ConnectedAlert (created by Connect(ConnectedAlert))
    in Connect(ConnectedAlert) (at FamePensees.js:41)
    in RCTView (at View.js:44)
    in FamePensees (created by Connect(FamePensees))
    in Connect(FamePensees) (at FameHomeView.js:309)
    in RCTView (at View.js:44)
    in CellRenderer (at VirtualizedList.js:687)
    in RCTScrollContentView (at ScrollView.js:852)
    in RCTScrollView (at ScrollView.js:977)
    in ScrollView (at VirtualizedList.js:1062)
    in VirtualizedList (at FlatList.js:662)
    in FlatList (at FameHomeView.js:475)
    in RCTView (at View.js:44)
    in FameHomeView (at connectAlert.js:11)
    in ConnectedAlert (created by Connect(ConnectedAlert))
    in Connect(ConnectedAlert) (at ReactMeteorData.js:88)
    in ReactMeteorDataComponent (at Home.js:339)
    in RCTView (at View.js:44)
    in KeyboardAvoidingView (at Home.js:333)
    in RCTView (at View.js:44)
    in Container (at Home.js:330)
    in Home (at connectAlert.js:11)
    in ConnectedAlert (at withNavigation.js:17)
    in withNavigation(ConnectedAlert) (created by Connect(withNavigation(ConnectedAlert)))
    in Connect(withNavigation(ConnectedAlert)) (at SceneView.js:17)
    in SceneView (at CardStack.js:466)
    in RCTView (at View.js:44)
    in AnimatedComponent (at Card.js:12)
    in Card (at PointerEventsContainer.js:39)
    in Container (at CardStack.js:498)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in CardStack (at CardStackTransitioner.js:67)
    in RCTView (at View.js:44)
    in Transitioner (at CardStackTransitioner.js:19)
    in CardStackTransitioner (at StackNavigator.js:41)
    in Unknown (at createNavigator.js:13)
    in Navigator (at createNavigationContainer.js:226)
    in NavigationContainer (at AppWithNavigationState.js:66)
    in App (created by Connect(App))
    in Connect(App) (at app/index.js:242)
    in RCTView (at View.js:44)
    in AlertProvider (at app/index.js:241)
    in Provider (at app/index.js:240)
    in AppContainer (at ReactMeteorData.js:88)
    in ReactMeteorDataComponent (at withExpoRoot.js:22)
    in RootErrorBoundary (at withExpoRoot.js:21)
    in ExpoRootComponent (at renderApplication.js:34)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in AppContainer (at renderApplication.js:33)

Moment
    moment.js:238:47
clone
    moment.js:3202:26
toISOString
    moment.js:3332:22
send
    socket.js:15:38
<unknown>
    ddp.js:44:25
process
    queue.js:21:32
push
    queue.js:16:4
method
    ddp.js:108:27
_default
    Call.js:9:29
componentDidMount
    FameMore.js:37:18
commitLifeCycles
    ReactNativeRenderer-dev.js:12144:10
commitAllLifeCycles
    ReactNativeRenderer-dev.js:13496:8
invokeGuardedCallbackImpl
    ReactNativeRenderer-dev.js:92:15
invokeGuardedCallback
    ReactNativeRenderer-dev.js:306:36
commitRoot
    ReactNativeRenderer-dev.js:13702:8
completeRoot
    ReactNativeRenderer-dev.js:15269:13
performWorkOnRoot
    ReactNativeRenderer-dev.js:15197:21
performWork
    ReactNativeRenderer-dev.js:15090:24
performSyncWork
    ReactNativeRenderer-dev.js:15047:14
batchedUpdates$1
    ReactNativeRenderer-dev.js:15315:21
batchedUpdates
    ReactNativeRenderer-dev.js:2616:31
_receiveRootNodeIDEvent
    ReactNativeRenderer-dev.js:2711:17
receiveTouches
    ReactNativeRenderer-dev.js:2787:28
__callFunction
    MessageQueue.js:349:47
<unknown>
    MessageQueue.js:106:26
__guard
    MessageQueue.js:297:10
callFunctionReturnFlushedQueue
    MessageQueue.js:105:17
`

**Comment by lc3t35** [comment] 2019-03-03 11:51
I have now the code that generates this error 
```
moment(latestExpiresDate).isAfter(moment())
```
with latestExpiresDate as undefined ...

**Comment by niftylettuce** [comment] 2019-06-19 08:39
I've managed to reproduce this as well on my end... and I also found the source of the bug... and I also patched it and submitted a pull request https://github.com/moment/moment/pull/5145.

This bug occurs during `console.log`, `util.inspect`, or a `JSON.stringify` call on a moment object with an invalid date (e.g. as @lc3t35 mentioned above <https://github.com/moment/moment/issues/5011#issuecomment-469015425> and provided an example).

The error is due to the `isValid` method returning false positives when `m._d == 'Invalid Date'` or simply when `m._d` is not a valid Date instance.

Here was the fix if you want to hardcode a test on your end:

> `vim ./node_modules/moment/moment.js`

```diff
    function isValid(m) {
+      if (!isDate(m._d)) {
+        m._isValid = false;
+        return m._isValid;
+      }
        if (m._isValid == null) {
            var flags = getParsingFlags(m);
            var parsedParts = some.call(flags.parsedDateParts, function (i) {
                return i != null;
            });
```

I've published `@ladjs/moment` in the meanwhile until https://github.com/moment/moment/pull/5145 is merged and a version bump is released to npm.

Thanks!

**Comment by ichernev** [comment] 2020-04-27 18:00
I'm having a hard time reproducing this problem. Does it reproduce on all environments?
```
> moment(undefined).isAfter(moment())
false
> moment(null).isAfter(moment())
false
```

**Comment by marwahaha** [comment] 2020-06-18 09:41
@lc3t35 could you provide another example? We could not reproduce the one listed.

Does 2.26.0 solve your issue?

**Comment by opravil-jan** [comment] 2020-06-18 17:32
Hello. the new version did not solved the issue.

**Comment by marwahaha** [comment] 2020-06-18 20:48
@opravil-jan - can you post another example? We cannot reproduce it.

**Comment by marwahaha** [comment] 2020-09-15 02:29
I will close this. Please re-open if you have another test case.

**Closed by marwahaha** 2020-09-15 02:29 UTC
Labels: Troubleshooting

**Comment by carchrae** [comment] 2021-06-25 01:23
@marwahaha - i'm not sure who this falls on, but i encountered a similar problem.  i suspect it is due to firebase logger's `removeCircular` method which somehow puts moment.js into a bad state. 

https://github.com/firebase/firebase-functions/blob/master/src/logger.ts#L33

**Comment by carchrae** [comment] 2021-06-25 01:41
i think i have a fix for this, pr coming

**Comment by carchrae** [comment] 2021-06-25 02:02
although this would stop the crash i am seeing, i don't think it is the correct result, since there should be a valid date in there.  it is probably better to have moment blow up.
 
 https://github.com/moment/moment/commit/1ca8689dc4623ba4498835039f51f7e077b51f61

**Comment by Michelle-Bettencourt** [comment] 2023-02-02 19:42
Is there a solution for this yet? I only get it when I try to use  var pdf = require('pdf-parse')
