### ISSUE TITLE
fromNow() produces wrong output for yearly intervals ("a year ago" and "2 years ago")

### ISSUE THREAD

**Issue by okristensen-imshealth** [moment/moment#5101] opened 2019-05-10 17:33 UTC
`fromNow()` is outputing the incorrect output in the yearly lengths of time. From my testing it seems like the end of the "a year ago" interval is on day 545 _not_ 547 like the [docs](https://momentjs.com/docs/#/displaying/fromnow/) states. Similarily, the start of the "2 years ago" interval is on day 546 _not_ 548.

You can find examples below that showcase where the one interval ends and the other one begins. This was tested out in Chrome, Safari and Firefox and they all show the same results.

``` javascript
// 47170799 = (545 days + 23 hours + 59 minutes + 59 seconds) 
moment().subtract(47170799, 'second').fromNow(); // a year ago
```

```javascript
// 47170800 = (546 days + 0 hours + 0 minutes + 0 seconds)
moment().subtract(47170800, 'second').fromNow(); // 2 years ago
```

Similar rounding issues can be found with different units (minutes, hours, days)
```javascript
// 786179 = (545 days + 22 hours + 59 minutes + 0 seconds)
moment().subtract(786179, 'minute').fromNow(); // a year ago
```

```javascript
// 786180 = (545 days + 23 hours + 0 minutes )
moment().subtract(786180, 'minute').fromNow(); // 2 years ago
```

```javascript
// 13102 = (545 days + 22 hours)
moment().subtract(13102, 'hour').fromNow(); // a year ago
```

```javascript
// 13103 = (545 days + 23 hours)
moment().subtract(13103, 'hour').fromNow(); // 2 years ago
```

```javascript
moment().subtract(545, 'day').fromNow(); // a year ago
```

```javascript
moment().subtract(546, 'day').fromNow(); // 2 years ago
```

```javascript
console.log((new Date()).toString()) //Fri May 10 2019 11:12:35 GMT-0600 (Mountain Daylight Time)
console.log((new Date()).toLocaleString()) // 5/10/2019, 11:12:35 AM
console.log((new Date()).getTimezoneOffset()) // 360
console.log(navigator.userAgent) // Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:66.0) Gecko/20100101 Firefox/66.0
console.log(moment.version) // 2.24.0
```

**Comment by harkue** [comment] 2019-11-15 08:41
It seems be fixed in the lastest code. I can't reproce it at [https://jsfiddle.net/bvpr0863/1/](https://jsfiddle.net/bvpr0863/1/)

**Comment by marwahaha** [comment] 2020-05-18 08:00
I also cannot reproduce.
Please re-open if you still have concerns.

**Closed by marwahaha** 2020-05-18 08:00 UTC
Labels: Troubleshooting
