### ISSUE TITLE
Incorrect moment validation on 2.11.0

### ISSUE THREAD

**Issue by MarshallOfSound** [moment/moment#2861] opened 2016-01-04 20:52 UTC
A bug has appeared in `2.11.0` regarding moment validation.  In this case a perfectly valid date is returned as invalid.

```js
moment('25-May-2015', 'DD-MMM-YYYY', true).isValid() // Returns false
```

This code returned `true` in 2.10.6
I've only been able to replicate this issue using `MMM` as part of the date string, so possibly the bug is there

**Comment by icambron** [comment] 2016-01-04 21:19
This is probably the same as #2841

**Comment by mj1856** [comment] 2016-01-05 19:03
Not the same.  The example in #2841 shows `true` in the description, but returns `false` under 2.11.0

**Comment by alexdiliberto** [comment] 2016-01-06 16:51
Also seeing this in my applications The two digit date ```moment('Jan-01-49', 'MMM-DD-YY', true).isValid();``` returns ```false``` as well only for ```2.11.0```

Very simple reproduction showing some valid dates next to the "invalid" bugs. This JSBin should console.log true for all four dates

http://jsbin.com/qepelowoqa/2/edit?html,js,console

**Comment by ichernev** [comment] 2016-01-06 21:36
It is indeed the same as #2841, caused by addition of gd locale, more precisely -- adding `-` as a "word" character.

Closing in favor of #2841.

**Closed by ichernev** 2016-01-06 21:36 UTC
Labels: Bug, High Priority
