### ISSUE TITLE
Follow Semantic Versioning principles

### ISSUE THREAD

**Issue by mj1856** [moment/moment#2516] opened 2015-07-27 17:36 UTC
We're using the `MAJOR.MINOR.PATCH` versioning scheme, but we're not fully following the principles of [Semantic Versioning](http://semver.org/).  Specifically, we're incrementing the *patch* number when introducing new functionality, instead of the *minor* number.

The most recent change should have been labeled `2.11.0`, not `2.10.5`.

**Comment by ichernev** [comment] 2015-07-31 05:05
I somewhat agree. We should try to be backwards compatible, and we do try. As for the features -- it depends on how major / minor they are. 2.10 was made for the es6 change -- no actual features / bugs were fixed. It was just a big jump and I wanted to note that.

We should also probably split the patch release from the feature release -- if we have 10 bugfixes and 10 features -- first release a patch and then a major. But we always have at least a small feature, that means a new major every month. It will blend bigger releases with smaller ones, so not sure. And I'm counting on 3.0 to do some format changes, so don't want to use it up for other stuff :)

**Comment by ichernev** [comment] 2015-07-31 05:06
@mj1856 the NPR was a bug, and it was caused by a refactoring, which might happen in a minor (no new features). It was our fault, but still marking it as a minor (not patch) wouldn't have fixed it :)

**Comment by mj1856** [comment] 2015-07-31 21:13
Agreed on the NPR bug. :)

**Closed** 2015-09-21 05:26 UTC
Labels: Build/Release
