### ISSUE TITLE
Duration of 1 year converted to milliseconds becomes 11 month 30 days

### ISSUE THREAD

**Issue by evil-shrike** [moment/moment#3209] opened 2016-06-03 13:10 UTC
It seems good:

```
moment.duration(moment.duration(1,'y').asMilliseconds()).asDays()
365
moment.duration(1,'y').asDays()
365
```

But:

```
var d_new = moment.duration(moment.duration(1,'y').asMilliseconds());
dnew.months()
11
d_new.days()
30
```

At first I thought that's because the current year is leap. But the same thing for months:

```
moment.duration( moment.duration(1,'M').asMilliseconds() ).asMonths()
0.9856465225158627
```

**Comment by icambron** [comment] 2016-06-07 01:54
I agree that `month -> ms` and `ms -> month` should be symmetrical, whatever the number is.

I'm less sure that `year -> ms -> month/day` giving you 11/30 is wrong. I think it's just a weird rounding thing.

**Comment by maggiepint** [comment] 2016-06-07 02:40
@icambron do we want to consolidate all of these floating point rounding sadness bugs into one ticket and up-for-grabs it? I know there's at least one other.

**Comment by icambron** [comment] 2016-06-07 03:27
Yeah, I was thinking that too, but I think there are just those two.

**Comment by ichernev** [comment] 2016-06-12 08:00
This is a feature. When you covert to months and years, the anchor point is year 0, which is leap. The problem is that when you convert something huge, leap years (and days) start making a difference, so by following the rule we essentially declare starting from year 0 (which other year to start from?).

Same goes for months/days -- bubbling assumes you're 1st Jan year 0. One month is the whole of January, which is 31 days, which is more than the average number of days per month, so you get less than a month, because you start with 1/12 of a year, which is 1 generic month.

I'm accepting pull requests that don't break all existing unit tests.

**Comment by evil-shrike** [comment] 2016-06-13 09:06
@icambron I'm afraid I quite don't understand from your reasoning why we have 0.98 for 1 month after converting to milliseconds. It's not huge. We got milliseconds for 1 month as it's treated as January so it's 31 days, then these milliseconds we added to the anchor - 1st of January of 0 year. We should get 1 month but we're getting 0.98...
It seems that we just have two different algorithms in these two cases: when we're converting months/years to milliseconds and when we're converting milliseconds back to months/years. One of them use the anchor and the other doesn't not (just my guess).

**Comment by evil-shrike** [comment] 2016-09-20 17:13
Hi.

# Proposal
Duration by default is normalized to milliseconds. And that milliseconds are treated as an interval from 1900-01-01. It actually doesn't mean much how it's implemented till we start working with years/month/weeks ("calendar entities"). 
For example this will allow to keep symmetrical conversion months/days->seconds/ms->months/days.
```
> moment.duration( moment.duration(1,'M').asMilliseconds() ).asMonths()
1
> moment.duration(moment.duration(1,'y').asMilliseconds()).asMonths();
12
> moment.duration(moment.duration(1,'y').asMilliseconds()).asYers();
365
```
There're corner cases indeed.
moment.duration(0).add(30, 'days').asMonths();
Someone may expect a result of "1". At least because it was that before.

As I understand Duration tries to keep original parts so currently if we create a Duration of 1 month and add it to a date, we'll get +1 month:
```
var month = moment.duration(1, 'M');
var dt = moment("2016-02-01"); // 1st Feb
var dt.add(month);
```
return 2016-03-01.
But if we downgrade that Duration to seconds/milliseconds, then adding it to a date adds 30 days actually:
```
moment("2016-02-01").add(moment.duration(m.asMilliseconds()))
```
We'll get 2nd of March (not the 1st as in the previous example).

If according to the proposal we start treating a Duration of 1M as milliseconds from 1900-01-01 then even after downgrade we can extract info that it was 1M.
```
moment("2016-02-01").add(moment.duration(m.asMilliseconds()))
```
would return 2016-03-01.

How would it understand that?
Well, we'd take a value in milliseconds passed in Duration constructor and add it to 1900-01-01. Then we'd see that the result date is more that a month, and we'll extract integer number of them (as months part) and so on.

If someone doesn't want conversion of its duration to years/months and want to keep as milliseconds than actually he/she doesn't need Duration, he/she can extract ms from Duration and add it to a Moment directly. Right?
So I can't see any drawbacks in this change.

What do you think?

**Comment by marwahaha** [comment] 2018-03-05 23:25
I'm going to close this as a duplicate of #2688 but link the proposal in a comment on that thread.

**Closed by marwahaha** 2018-03-05 23:25 UTC
Labels: Bug
