### ISSUE TITLE
startOf week 53 and 1 returns same day.

### ISSUE THREAD

**Issue by dermike** [moment/moment#2662] opened 2015-10-09 12:37 UTC
I'm hoping this is me doing something wrong than a bug. I've built an app that gets the date of the first day of a week only knowing week number and year. 

```js
moment([2015]).startOf('isoWeek').week(53).add(0, 'day').format('D/M')
-> 28/12
```
```sh
moment([2016]).startOf('isoWeek').week(1).add(0, 'day').format('D/M')
-> 28/12
```
The second should report 4/1

moment('2016-01-01').isoWeek() gives 53
and moment('2016-01-04').isoWeek() gives 1 as expected.

Bug in startOf, or just me?

**Comment by mj1856** [comment] 2015-10-13 17:06
Unfortunately, it's a bit of both.  The relevant bugs are already reported in #2496 and #2033.

But also, in your code:

- You are using locale-specific week numbers, but then ask for the start of the ISO week.  I would expect the same numbering scheme to be used for both.  Either use `startOf('week')`, or use `.isoWeek(1)`.
- You should apply the week number before moving to the start of the week.
```javascript
moment([2015]).week(1).startOf('week').format('L') // 12/28/2014
moment([2016]).week(1).startOf('week').format('L') // 12/27/2015
```
- However, due to the bugs mentioned earlier, ISO weeks wont always be correct:
```javascript
moment([2015]).isoWeek(1).startOf('isoWeek').format('L') // 12/29/2014 - correct
moment([2016]).isoWeek(1).startOf('isoWeek').format('L') // 12/29/2014 - incorrect (should be 12/28/2015)
```
- Keep in mind that the week a year begins in is the week that contains Jan 1st.  The start of *that* week might be at the end of the prior year.  That's as designed.
- `add(0, 'day')` doesn't do anything.  You might as well remove it.

**Comment by mj1856** [comment] 2015-10-13 17:07
Closing in favor of #2033.

**Closed by mj1856** 2015-10-13 17:07 UTC
