### ISSUE TITLE
1 test failed. relative time:custom rounding (2721.3) 

### ISSUE THREAD

**Issue by benblue** [moment/moment#3804] opened 2017-03-03 18:33 UTC
### Client info
```
Date String   : Fri Mar 03 2017 10:31:40 GMT-0800 (PST)
Locale String : 3/3/2017, 10:31:40 AM
Offset        : 480
User Agent    : Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8
Moment Version: 2.17.1
```

====

### relative time:custom rounding (2721.3) 

Round down towards the nearest day

```javascript
// Expected in 30 days
// Actual   in a month
"in a month" === "in 30 days"
```

**Comment by benblue** [comment] 2017-03-03 18:34
Trying to help.

**Comment by marwahaha** [comment] 2017-03-09 01:45
Thanks for making an issue.

This is a duplicate of #3801

**Closed by marwahaha** 2017-03-09 01:45 UTC
Labels: Unit Test Failed
