### ISSUE TITLE
3000ms results as 2.9999999999999996 seconds

### ISSUE THREAD

**Issue by balasphilip** [moment/moment#2973] opened 2016-02-18 15:30 UTC
```javascript
var durationInMs = moment.duration(3000, "milliseconds");
durationInMs.as('seconds') // -> 2.9999999999999996
```

**Comment by mj1856** [comment] 2016-02-18 18:04
Can't reproduce in the current version.  What version of moment are you running?

**Comment by balasphilip** [comment] 2016-02-19 08:31
2.8.0

**Comment by mj1856** [comment] 2016-02-24 05:22
Closing since I can't repro in current version.  Consider upgrading.

However, there is a similar issue in #2978 worth watching.

Thanks.

**Closed by mj1856** 2016-02-24 05:22 UTC
Labels: Troubleshooting
