### ISSUE TITLE
locale is returning chinese by default  

### ISSUE THREAD

**Issue by victorhazbun87** [moment/moment#2808] opened 2015-12-11 16:57 UTC
I did not changed the default locale which is supposed to be **'en'** but for some reason is **'zh-tw'**.

# Some info

### In my bower.json:

     "moment": "~2.10.6"

### When calling: moment.locale();

     zh-tw

### Finally when running: moment().format("MMM Do YY"); 

     12月 11日 15

**Comment by victorhazbun87** [comment] 2015-12-11 17:00
I was forced to do the following in order to load en by default: 

    moment.locale('en');

**Comment by julesongithub** [comment] 2016-01-02 10:06
I've just noticed this as well with the cloudfare CDN but not the script copied form the moment website.

**Comment by mj1856** [comment] 2016-01-11 00:58
This looks like #2367, which was fixed in 2.10.4.  I cannot reproduce it in 2.10.6 that you said you were using.  (The current version is 2.11.1)

Please verify your version of moment.  Closing for now.  I'll reopen if you can reproduce in the current version.  Thanks.

**Closed by mj1856** 2016-01-11 00:58 UTC
