### ISSUE TITLE
1 test failed. relative time:custom rounding (2721.3) 

### ISSUE THREAD

**Issue by aaronddickson** [moment/moment#3818] opened 2017-03-08 21:49 UTC
### Client info
```
Date String   : Thu Mar 09 2017 10:49:01 GMT+1300 (NZDT)
Locale String : 09/03/2017, 10:49:01
Offset        : -780
User Agent    : Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
Moment Version: 2.17.1
```

====

### relative time:custom rounding (2721.3) 

Round down towards the nearest day

```javascript
// Expected in 30 days
// Actual   in a month
"in a month" === "in 30 days"
```

**Comment by marwahaha** [comment] 2017-03-09 01:45
Thanks for making an issue.

This is a duplicate of #3801

**Closed by marwahaha** 2017-03-09 01:45 UTC
Labels: Unit Test Failed
