### ISSUE TITLE
Some Time's PM value is coming as AM

### ISSUE THREAD

**Issue by anilking** [moment/moment#5212] opened 2019-08-28 07:45 UTC
Im using moment js for date functionality.

 Old code is:
moment(" 2019/08/28 22:00", 'YYYY/MM/DD HH:mm').format('h:mm A'); 
O/P: 10 PM.  it's working fine. later I changed code is like below.

New code is: 
scheduleDate = moment("2019-08-23");
dateFormat = moment(scheduleDate).format('YYYY/MM/DD');
moment(dateFormat + " " + "22:00", 'YYYY/MM/DD HH:mm').format('h:mm A');
O/P: 10 AM. but value is wrong.

above issue is coming as intermediate. Please help is there any wrong in new code.

Thanks in advance!.

**Comment by EmilSchaetzle** [comment] 2019-09-11 20:34
I can't reproduce your error. If i run the following:
```
var moment = require('moment');
scheduleDate = moment("2019-08-23");
dateFormat = moment(scheduleDate).format('YYYY/MM/DD');
console.log(moment(dateFormat + " " + "22:00", 'YYYY/MM/DD HH:mm').format('h:mm A'));
```
it is returning
```
10:00 PM
```
Can you post the whole code or at least the function?

**Comment by wmonecke** [comment] 2019-09-21 12:25
Happening to me aswell!

**Comment by EmilSchaetzle** [comment] 2019-09-21 12:56
@wmonecke If i execute
```
var moment = require("./moment.js");
console.log(moment({
  year: 2019,
  month: 9,
  day: 20,
  hours: 16,
  minutes: 24,
}).format('h:mm A'));
```
it logs `4:24 PM`.
Im using Kubuntu 19 with node 9.11.2. Localization is set to german.

**Comment by Srinivasan-Natarajan** [comment] 2019-11-12 09:41
<img width="357" alt="Screenshot 2019-11-11 at 4 48 14 PM" src="https://user-images.githubusercontent.com/56440779/68660138-9b5f4c00-055e-11ea-833e-a25e48ca5ac0.png">
issue persist  if we change locale

**Comment by harkue** [comment] 2019-11-15 02:07
Can't reproduce. It works fine for me with belowing code:
```js
const moment = require("moment");

function print() {
  console.log(
    moment({
      year: 2019,
      month: 9,
      day: 20,
      hours: 16,
      minutes: 24
    }).format("h:mm A")
  );
}

console.log(moment.locale());
print();

// change locale
moment.locale("zh-cn");
console.log(moment.locale());
print();
/* output:
en
4:24 PM
zh-cn
4:24 下午
*/
```

**Comment by Srinivasan-Natarajan** [comment] 2019-11-15 03:26
Please give like below after changing locale
moment(‘02:00 PM’,[h:mm A]).format(‘HH:mm’)

**Comment by EmilSchaetzle** [comment] 2019-11-16 22:06
I finally can reproduce it with the "hu" locale.
```
const moment = require("./moment.js");

moment.locale('hu');
console.log(moment('02:00 PM', ["h:mm A"]).format("HH:mm"));
/* output:
02:00
*/
```

**Comment by EmilSchaetzle** [comment] 2019-11-16 22:18
I run an automated test on this and it seems like these locales are affected:
```
af
ar-ly
az
be
dv
el
eo
gom-latn
he
hu
hy-am
id
ja
jv
ko
lo
ml
mn
ms-my
ms
ru
sd
si
sq
ss
te
tg
th
tzl
ug-cn
uk
ur
vi
zh-cn
zh-hk
zh-tw
```

**Comment by harkue** [comment] 2019-11-18 03:28
> I finally can reproduce it with the "hu" locale.
> 
> ```
> const moment = require("./moment.js");
> 
> moment.locale('hu');
> console.log(moment('02:00 PM', ["h:mm A"]).format("HH:mm"));
> /* output:
> 02:00
> */
> ```

I don't think it is a bug.  If you want `14:00` on `hu` locale case, you would use:
```js
// `DU` instead of `PM`
console.log(moment('02:00 DU', ["h:mm A"]).format("HH:mm")); // 14:00
```

**Comment by EmilSchaetzle** [comment] 2019-11-18 15:06
@harkue thanks, you're right. The "issue" seems to be trying to parse "02:00 PM" while using a local that does not use this representation (as "hu" does with "02:00 DU"). This can be fixed by parsing the string using the "en" locale and formatting it using the "hu" locale. The following code should work:
```
const moment = require("./moment.js");

moment.locale('en');
var time = moment('02:00 PM', ["h:mm A"])
moment.locale('hu');
console.log(time.format("HH:mm"));
/* output:
14:00
*/
```

**Comment by harkue** [comment] 2019-11-19 00:59
@EmilSchaetzle That's all right.

BTW, go back to the question, I can't reproduce too. I also get this value:
```
10:00 PM
```
Maybe it need more information about the new code. @anilking

**Closed** 2020-05-12 13:53 UTC
