### ISSUE TITLE
isAfter() returns `true` when given an `undefined` or `null` variable

### ISSUE THREAD

**Issue by coreyzev** [moment/moment#2697] opened 2015-10-24 06:09 UTC
When using the isAfter method I provided the first argument with a variable. If the variable is `null` or `undefined` I expected a return result of `false`, but instead I got `true`.

example:

``` javascript
var day = null;
moment().isAfter(day);
// => true

day = moment().subtract(1, 'days');
moment().isAfter(day);
// => true
```

I realize this is because if you pass nothing into a query method, it assumes "today". But that was not my expected interaction with it. Since I was in fact not passing in "nothing".

expected results:

``` javascript
var day = null;
moment().isAfter(day);
// => false

day = moment().subtract(1, 'days');
moment().isAfter(day);
// => true
```

**Comment by mj1856** [comment] 2015-10-24 18:33
Sorry, I can't reproduce this in the current version of moment.js.

![image](https://cloud.githubusercontent.com/assets/1396388/10712054/03f4e0fa-7a43-11e5-94e7-278344f9fad4.png)

**Comment by coreyzev** [comment] 2015-10-26 06:46
Thanks @mj1856 , looks like I'm on 2.9.0. Sorry!

**Comment by coreyzev** [comment] 2016-06-29 19:22
I can now recreate this with a better understanding, (cc: @mj1856 )

while `null` works as expected...

moment treats `undefined` as a new moment: http://stackoverflow.com/a/33003021

So when you drop it in, it treats it like a new date. 

here's why: 

![screen shot 2016-06-29 at 12 16 49 pm](https://cloud.githubusercontent.com/assets/2052536/16465419/6df2daba-3df3-11e6-8a6b-075b7ee88b83.png)

I hope you can see where this causes frustration. If I have a variable dropping into a comparative moment function, and for some reason that variable equals `undefined`, it's still coming back true. 

If it IS purposeful to have `moment(undefined)` succeed, then can you explain why? Or at least add a catch to the comparators to return false or fail when they get an `undefined`.

**Comment by maggiepint** [comment] 2016-06-29 19:55
See #3180

**Comment by coreyzev** [comment] 2016-06-29 20:18
Thank you @maggiepint, you gave me exactly the comment I needed to prove my point.

In @icambron's comment: https://github.com/moment/moment/issues/3180#issuecomment-219203972

They say: 

>  It really is the case that JS is supposed to work by making `foo()` and `foo(undefined)` equivalent. That's why foo's first parameter gets bound to undefined when you don't provide it

And they show the example:

```
new Intl.NumberFormat().format(1) //=> "1"
new Intl.NumberFormat(undefined).format(1); //=> "1", just like above
new Intl.NumberFormat("ar").format(1) //=> "١", how this arg is meant to be used
new Intl.NumberFormat(null).format(1); //error
```

and as such, I give you this proof of code failure: 

```
moment().isSame()
=> false
moment().isSame(undefined)
=> true
```

What's odd, is I just realized that I get this, which seems like a bug: 
```
moment().isSame()
=> false
moment().isSame()
=> true
```

Comparators should NOT default to creating a moment when nothing is passed. That's a "proof", not a function.

**Comment by coreyzev** [comment] 2016-06-29 20:22
If you do not want to change `moment(undefined)` resolving, then at least change the comparators automatically converting the date that gets put in into a moment, and see my issue for reasons why THIS ticket is not the same as #3180. 

For example you should consider adding a line at the top of the function: 

```
export function isAfter (input, units) {
    if (!input) return false; // check for an undefined or false input
    var localInput = isMoment(input) ? input : createLocal(input);
    if (!(this.isValid() && localInput.isValid())) {
        return false;
    }
    units = normalizeUnits(!isUndefined(units) ? units : 'millisecond');
    if (units === 'millisecond') {
        return this.valueOf() > localInput.valueOf();
    } else {
        return localInput.valueOf() < this.clone().startOf(units).valueOf();
    }
}
```

Even better, you could add that 2nd line above to `createLocalOrUTC` and this would be solved in SO many places. It'd make MUCH more sense in `localInput`, because then the `isValid()` would be checking for it.

**Comment by icambron** [comment] 2016-06-29 21:01
Right, you're just seeing inconsistent results from whether or not `isSame()` creation of the current date happens on the same millisecond or not. So, all this stuff about `undefined` aside, the question is just whether `isSame()` without args should compare with the current time or not.

It's the way most Moment functions work, but I'm sympathetic to the point that maybe it's not appropriate for comparison functions. My preferred way to change that would be a bit narrower:

```js
if (isUndefined(input)) {
  return false;
}
```

Three questions:

 * Is `isSame()` a legit use case?
 * Does this create confusion because so many Moment functions do create Moments by default?
 * How big of a breaking change is this? i.e how many people use `m.isSame()` to mean is this `m` the same as the current millisecond, independent of whether that's a good idea or not?

**Comment by coreyzev** [comment] 2016-06-29 21:38
#### one 

My actual useCase is `isAfter()`, and If you need me to, I can show more of my exact code. It's going into a pull request for ChiperSoft/Kalendae though, so I'd like to not have to be checking for undefined every time I use `isAfter()`

For example: 

```javascript
// ...
addSelected : function (date, draw) {
		date = moment(date, this.settings.format).hours(12);

		if (!!this.endDate && date.isAfter(this.endDate, 'day')) return false;
        // ...
```
---

#### two 

I dont think it'd create confusion, mostly because your docs say: 

> `moment().isSame(Moment|String|Number|Date|Array);`

It does not mention a null value, I'd rarely expect to see it used. 

--- 

#### three

I think it's definitely a worthwhile breaking change. 

https://github.com/search?utf8=%E2%9C%93&q=moment+%22.isSame%28%29%22&type=Code&ref=searchresults

I could not find an example of it being used like you're concerned about. 

I did find this: `console.log(moment('2009-05-16').isBefore(moment()));`

In which someone instantiates a new moment, which I think *IS* in fact the expected pattern for most people.

**Comment by icambron** [comment] 2016-06-30 00:57
Sorry, on 1, I meant is there a legit use for `someMoment.isAfter()` all by itself. I doubt there's one that isn't improved in clarity by `someMoment.isAfter(moment())`, but I wanted to leave it out there.

**Comment by haxxxton** [comment] 2017-02-03 01:31
This appears to not have been resolved yet in 2.17.1. I guess my understand would be to have the `.isBefore()` and `.isAfter()` function return the same output as `new Date() > undefined` and `new Date() < undefined`.

```
new Date() > undefined; // => false
new Date() < undefined; // => false

new moment().isBefore(undefined); // => false
new moment().isAfter(undefined); // => true
```

My use case for this is while upgrading a timepicker to use momentjs, where it looks for the value of an element attribute (undefined if not found) and compares it to the currently set time. 

If my two cents can weigh in on what @icambron asked regarding the use of `someMoment.isAfter()` all by itself, I personally cant see a place you'd want to use this with the intention of comparing it to "now" without having to specify `moment()` in the function.

Any news on its progress?

**Comment by sebcharrot** [comment] 2017-08-06 12:19
Hey, I found this while looking into fixing issue 4096. 

I've submitted a Pull Request which always returns false if the param is undefined, for functions isBefore, isAfter, and isSame. 

https://github.com/moment/moment/pull/4104

Not sure what the process is, but happy to discuss the fix.

**Comment by Morgantheplant** [comment] 2017-11-22 18:52
ran into some unexpected results with `isAfter`/`isSameOrAfter`:

<img width="352" alt="screen shot 2017-11-22 at 10 43 59 am" src="https://user-images.githubusercontent.com/6319250/33144500-290ee58a-cf72-11e7-9393-4e56b56a6bb9.png">

and `isBefore`/`isBeforeOrAfter`:

<img width="341" alt="screen shot 2017-11-22 at 10 31 41 am" src="https://user-images.githubusercontent.com/6319250/33144503-2d46b22c-cf72-11e7-9dfe-b206b430bbdf.png">
<img width="367" alt="screen shot 2017-11-22 at 10 48 57 am" src="https://user-images.githubusercontent.com/6319250/33144734-dc1c1ef4-cf72-11e7-9b73-b77bee6eba57.png">

In the console on the momentjs website

**Comment by marwahaha** [comment] 2020-05-17 11:58
closing in favor of https://github.com/moment/moment/issues/5285 , which is something we can do in a major version change

**Closed by marwahaha** 2020-05-17 11:58 UTC

**Comment by coreyzev** [comment] 2020-05-17 20:56
Glad to see it finally get fixed. Thanks.
