### ISSUE TITLE
Invalid ISO string for durations with mixed sign

### ISSUE THREAD

**Issue by balagge** [moment/moment#3960] opened 2017-05-12 15:59 UTC
Creating durations with mixed signs work as expected when used in calculations. However, the string representation is incorrect.

Following example shows two different ways to create such a mixed-sign duration (by subtracting and by directly parsing an ISO duration)

```javascript
var moment = require('moment');

    // Create duration of 3 months MINUS 2 days:

var a = moment.duration(3, 'M');
var b = moment.duration(2, 'd');
var c = a.subtract(b);

console.log(c.toString(), c.toISOString()); // P3M2D P3M2D -- ERROR! should be P3M-2D

    // Different method: parse an ISO duration directly

var d = moment.duration('P3M-2D');

console.log(d.toString(), d.toISOString()); // P3M2D P3M2D -- ERROR! should be P3M-2D

    // however, both work as excpected when used:

console.log(moment.utc("2017-01-01").add(c).toISOString()) ;  // 2017-03-30T00:00:00.000Z -- correct: 3 month minus 2 days added
console.log(moment.utc("2017-01-01").add(d).toISOString()) ;  // 2017-03-30T00:00:00.000Z -- correct: 3 month minus 2 days added

    // so the bug is probably in toString() / toISOString() only
```

**Comment by maggiepint** [comment] 2017-05-13 17:14
The short answer to this is that this isn't supported. @mj1856 wants to check the ISO spec to see if this is even valid - he'll get to it soon.

**Comment by icambron** [comment] 2017-05-18 18:20
Seconding @maggiepint and @mj1856 - why are there dashes? It's certainly not an error to not provide them in our `toISOString()` output as you suggest in the first section, and it would be news to me that they would be a valid part of a duration string at all. But I haven't actually dug through the spec, so...maybe it's a valid alternate format? If so, we'd add support for it in parsing, though we will certainly keep the non-dash version as the `toISOString()` output, since that's both valid and widely used.

**Comment by mj1856** [comment] 2017-05-23 18:24
I checked the ISO-8601 spec thoroughly.  It explicitly defines a duration as non-negative, in section 2.1.6.

However, I am finding that there are other APIs that allow for this, but there are inconsistencies.  Looking at .NET:

```csharp
System.Xml.XmlConvert.ToString(TimeSpan.FromHours(-1))  // "-PT1H"
NodaTime.Period.FromHours(-1).ToString()                // "PT-1H"
```

Noda-Time also allows for mixed formats as asked in the question:
```csharp
PeriodBuilder b = new PeriodBuilder();
b.Months = 3;
b.Days = -2;
Period p = b.Build();
p.ToString() // "P3M-2D"
```

As I don't see this in the spec at all, I'm wondering if other APIs out there do this and we should support it, at least partially.  We don't keep track of individual parts (AFAIK), so we couldn't round-trip something like `"P3M-2D"`, but we could give back something approximate, like `"P2M28D"` assuming a 30-day month (yuck).

@balagge - what are you using on your back-end to generate strings like this?

@jonskeet - Was this something you modeled from elsewhere for NodaTime, or am I missing something in the spec?

**Comment by mj1856** [comment] 2017-05-23 18:26
@icambron - One assumes the dashes are for negatives, so `"P3M-2D"` would read as "three months, less two days".

**Comment by balagge** [comment] 2017-05-23 18:59
First, ssing negative durations, including durations with "mixed signs" (like the example: "(plus) 3 months minus 2 days" **has been supported since 2.13.0.**. So the question is not whether this is, or should be supported.

See http://momentjs.com/docs/#/durations/creating/

And below it says:

> As of 2.13.0, mixed negative and positive signs are supported when parsing durations.
>
> `moment.duration('PT-6H3M')`

**Comment by balagge** [comment] 2017-05-23 19:01
And, as the original post says, there is no problem with parsing (or creating in any other way) such durations.

The bug is simply formatting the iso string. As I have also written in the OP, such durations **work as excpected** in any other scenario (except the string output).

**Comment by balagge** [comment] 2017-05-23 19:06
parsing probably implemented here: #2408

PR #2955

**Comment by balagge** [comment] 2017-05-23 19:07
So the current issue is only about formatting.

**Comment by mj1856** [comment] 2017-05-23 19:18
Oh. Ok - well, then I guess we've already decided on supporting these. lol.

Testing, and yes - parsing seems to work:

```js
moment.duration('P3M2D').asDays() // 93
moment.duration('P3M-2D').asDays() // 89
```

But as you said, formatting does not:
```js
moment.duration('P3M2D').toISOString()  // "P3M2D"
moment.duration('P3M-2D').toISOString() // "P3M2D"
```

The negatives appear to be persisted on the internal fields (`_days`, etc.), so it is just an issue with formatting.  Looks to be caused by liberal use of `abs` in [/src/lib/duration/iso-string.js](https://github.com/moment/moment/blob/develop/src/lib/duration/iso-string.js)

**Comment by balagge** [comment] 2017-05-23 19:19
@mj1856: FYI to earlier question:

 moment.js is plugged into a math environment ( https://github.com/josdejong/mathjs ) where it supports date calculations. The application uses math.js to parse input, build formula executable code and date/time calculation requests are processed by moment.js.

In my use case these "mixed sign durations" do not get created from parsing ISO strings. I included that as an example only, and to show in two different ways that such durations **actually work** and are **currently supported**. Instead, the source formula uses predefined constants like "year", "month", etc. which represent moment.js durations and can manipulate them like " 3 year + 2 month - 3 day" etc. These are not actual examples but show the concept. 

Such durations are very useful in calculations involving date-time arithmetic. mixing positive and negative components can occur as the user determines the formula and it is awkward to say (e.g.) that "d1 = 3 month" is valid, "d2 = 2 day" is valid, "d3 = -d2" is valid, **however** "d4 = d1 + d3" is not (because it creates a duration with  "mixed sign")

**Comment by mj1856** [comment] 2017-05-23 19:21
@balagge  - Thanks for the explanation. :)


Marked as "up-for-grabs".  To potential implementer:  please be sure to include unit tests that validate various forms of negative durations can survive the round trip between parsing and `toISOString`.

**Comment by jskeet** [comment] 2017-05-23 19:33
Yikes, well caught. One thing I haven't spotted here is "negative everything" cases. For example, how does one represent negative "2 months and one day"? Is it P-2M-2D? Is there a format such as -P2M2D which implies "negate everything"? Noda Time uses "P-2M-2D" as the format for this - does Moment do the same?

**Comment by balagge** [comment] 2017-05-23 20:03
Well, I was too early to announce that the parsing / creation of such durations is OK.

There is something strange going on:

```'use strict';

/* jshint node: true */

var moment = require('moment');
var a = moment.duration(3, 'M');
var b = moment.duration(2, 'd');

	// 3 months + 2 days

var c = moment.duration(a).subtract(b);

console.log(c.days(), c.months())          // 29 2
console.log(c.toString(), c.toISOString()) // P3M2D P3M2D

	// 3 months - 2 days

var d = moment.duration(a).add(b);

console.log(d.days(), d.months())          // 2 3
console.log(d.toString(), d.toISOString()) // P3M2D P3M2D

	// 2 months + 29 days

var e = moment.duration(2,'M').add(moment.duration(29, 'd'));

console.log(e.days(), e.months())          // 29 2
console.log(e.toString(), e.toISOString()) // P2M29D P2M29D

```
What happens here is beyond my understanding. See the second operation (concerning variable `d` above) first. This looks like the 3 months and 2 days are added correctly.

Now look at the operation concerning variable `c`, which is constructed as "3 months minus 2 days".
It seems first that this duration is actually converted to "2 months and 29 days", because it prints 29 as "days" and "2" as months. However, that is not the case, as can be seen from the `toString()` and `toISOString()` printouts.

Final part with `e` confirms this. it prints 29 for `days()` and 2 for `months()` (same as `c`), but it is not the same duration, because the string output is different.

What is going on? There is something wrong with the internal state as well, it seems.

**Comment by balagge** [comment] 2017-05-23 20:10
@jskeet:
Seems like there **is** "negative everything", so moment.js places "global negative sign" in front of the "P" character if all components are negative:

```
console.log(moment.duration(-3, 'M').add(-2, 'd').toString()) // -P3M2D
```

**Comment by balagge** [comment] 2017-05-23 20:25
@mj1856:
You are right, I can confirm that ISO does explicitly state that duration components are positive.

unfortunately I have an old (1988) version at hand, so the section numbers changed.

I also wonder if the latest version still contains this, and if the extensions (8601-2) contains reference to negative durations. These are quite natural, or so they seem to me.

**Comment by balagge** [comment] 2017-05-23 20:35
Another related issue #2166

**Comment by balagge** [comment] 2017-05-23 20:35
This problem runs deeper than I thought...

**Comment by balagge** [comment] 2017-05-23 20:43
There is a conceptual problem of how a duration is represented internally, and there is a problem with the `bubble()` method. First the internal representation should be fixed, with parsing, cloning, `add()`, `subtract()`. Then the external formatting.

Conceptually, a moment.js duration object is internally defined as a triplet (ms, days, months).

See comment by @ichernev in #2166.

See the source of `clone()` for durations. It basically clones based on the content of these fields.

Now this concept may seems strange at first, but it is sensible, because:
- ms, s, min, h are freely convertable to each other
- d (and actually week as well) are also always convertable
- M, Q, Y are also convertable
- however: ms, s, min, h **are not convertable to days**, because of DST (and maybe leap seconds as well)
- however: days **are not convertable to months**, because of the different lengths of months.

Hence the three components: ms, day, and month. All method implementations should respect this, but it seems this is not the case.

**Comment by balagge** [comment] 2017-05-23 20:47
No matter how a duration object has been created, it must internally be resolved to these 3 numbers.

The `bubble()` method, however, does not respect this, because it converts everything to milliseconds (but only if the 3 main properties have differing signs):

```javascript
// if we have a mix of positive and negative values, bubble down first
    // check: https://github.com/moment/moment/issues/2166
    if (!((milliseconds >= 0 && days >= 0 && months >= 0) ||
            (milliseconds <= 0 && days <= 0 && months <= 0))) {
        milliseconds += absCeil(monthsToDays(months) + days) * 864e5;
        days = 0;
        months = 0;
    }
 ```

**Comment by balagge** [comment] 2017-05-23 20:54
This is wrong because the distinction between days and sub-day component is lost, as well as the distinction between months and sub-month components.

To me it seems that issue #2166 is invalid, the request is really is based on not understanding calendar durations. The very point of durations is that we do NOT want to convert everything to milliseconds. If I want to do that, I can easily do it with multiplications / additions in the client code. 1 year is not the same as 365 days (or any number of days), that is the very point of durations....

I am relatively new here, so I do not know how to handle this.... But I strongly beleive that the changes in #2166 should be reversed.

**Comment by balagge** [comment] 2017-05-23 21:19
In addition to the main representation (ms, days, months) there is a secondary representation in `_data`, which expresses the duration in a more "friendly" format, like (example)
```javascript
{_data:
  { milliseconds: 0,
     seconds: 0,
     minutes: 0,
     hours: 0,
     days: 2,
     months: 3,
     years: 0 },
}
```
This is confusing because the `bubble()` method, which is invoked from the constructor, calculates these from the three main properties mentioned above, and also "carries over" stuff from sub-day to day, sub-month to month component.

For example, a duration constructed as 10 000 000 seconds will be represented as:

```javascript
{ _milliseconds: 10000000000,
  _days: 0,
  _months: 0,
  _data: 
   { milliseconds: 0,
     seconds: 40,
     minutes: 46,
     hours: 17,
     days: 23,
     months: 3,
     years: 0 },
}

Here it is plain to see that this is really a duration of 10 000 000 000 milliseconds, but it is converted to days and months as well, which is wrong because we do not know the number of milliseconds in a day and we do not know the number of days in a month.

**Closed** 2017-10-09 22:48 UTC
Labels: Bug, Up-For-Grabs
