### ISSUE TITLE
Non-Intl Subset build

### ISSUE THREAD

**Issue by SlexAxton** [moment/moment#2247] opened 2015-03-01 22:47 UTC
Hiya,

This is somewhat related to #2167 .

I'd love a build of moment that does all the stuff that moment does, minus any formatting. There's so much useful parsing and `.add` type functionality that I don't want to get rid of moment in my project, however, I'm moving to the standardized `Intl.DateTimeFormat` stuff in recent apps.

It could be that the formatting code doesn't take up much of th 12KB gzip/minified file size of moment (sans locales), but if it would save a few KB, it could be worth doing a build without formatting, since I think more and more, people will be moving to the built in browser functionality.

Thanks!

**Comment by ichernev** [comment] 2015-08-11 15:41
This patch will take some time. Also we'll add support for Intl in the future :) PRs welcome for both

**Comment by maggiepint** [comment] 2016-04-01 01:37
I'm going to close this as what amounts to a duplicate of #2373. I think it makes sense to consolidate these.

**Closed by maggiepint** 2016-04-01 01:37 UTC
