### ISSUE TITLE
Typescript instructions in docs just results in error

### ISSUE THREAD

**Issue by jeremypeters** [moment/moment#5449] opened 2020-04-22 11:26 UTC
Following the Typescript instructions (https://momentjs.com/docs/#/use-it/typescript/) results in the error:

`TS2349: This expression is not callable.
    Type 'typeof moment' has no call signatures.`

**Comment by Alanscut** [comment] 2020-04-23 02:48
@jeremypeters See issue #5444 .

**Comment by jeremypeters** [comment] 2020-04-23 12:39
If the steps in the documentation result in an error, then it is wrong and needs updating.

**Comment by marwahaha** [comment] 2020-05-13 02:14
duplicate of #5444

**Closed by marwahaha** 2020-05-13 02:14 UTC
Labels: Up-For-Grabs
