### ISSUE TITLE
Problems with momentjs in Meteor 1.0.4.1

### ISSUE THREAD

**Issue by benmgreene** [moment/moment#2285] opened 2015-03-19 22:14 UTC
CC: @dandv 

Both myself and another Meteor/momentjs user have encountered problems with the most recent Meteor upgrade.  Here's the existing SO:

http://stackoverflow.com/questions/29135488/momentjs-with-meteor-doesnt-seem-to-work-on-server-side/29135787

**Comment by c316** [comment] 2015-03-19 22:50
+1

**Comment by theduke** [comment] 2015-03-21 09:15
+1

**Comment by iStefo** [comment] 2015-03-23 13:48
+1

The global `moment` is working again after downgrading to 1.0.3.2 via `meteor update --release 1.0.3.2`.

**Comment by miri-am** [comment] 2015-03-24 09:59
+1 ```TypeError: Property 'moment' of object #<Object> is not a function```

**Comment by jaskinn** [comment] 2015-03-26 04:03
+1

**Comment by jaskinn** [comment] 2015-03-26 04:41
I was getting this behaviour when I was incorrectly returning from logging in. For me at least it was my error.

**Comment by jbbower** [comment] 2015-03-26 20:47
+1

**Comment by c316** [comment] 2015-03-26 20:59
@jaskinn that was my thought too, but now the problem seems to have resurfaced. I'm not sure what might be causing it to work, and then not work. Currently though it doesn't work at all.

**Comment by c316** [comment] 2015-03-26 21:03
Also, even if I run from the Meteor shell I see a problem. If I run
`> moment()`
I get
`TypeError: Property 'moment' of object #<Object> is not a function`

**Comment by theduke** [comment] 2015-03-26 21:26
It is intermittent for me true. 
Sometimes on startup it works for one request, then it does not. 
On the shell, it is always undefined.

**Comment by c316** [comment] 2015-03-26 21:30
I was running at 1.0.5 and still have the problem. I ran `meteor --release 1.0.3.2`, then I couldn't get the shell to come up so I couldn't test it from the shell....

**Comment by dan335** [comment] 2015-03-28 05:14
I'm getting this also.

**Comment by benmgreene** [comment] 2015-03-31 17:35
I just upgraded Meteor to 1.0.5, and the issue may have gone away for me. If you try upgrading your own apps, please post below if it resolves the issue for you as well. Thanks!

**Comment by c316** [comment] 2015-03-31 20:36
No. It seems like it goes away, but if an uncaught error hits the server it stops working. Even after restarting the app it still doesn't work.

**Comment by jbbower** [comment] 2015-03-31 20:40
I have upgraded to 1.0.5 and it does not seem to go away. It does not always seem to be a problem (I have had the moment object available correctly in a few sporadic instances), but it more often than not does not work.

**Comment by benmgreene** [comment] 2015-03-31 20:45
Yeah, I’ve seen weirdness too.  I’ve experienced dramatic weirdness when I tweak my `.meteor/packages` file, but I haven’t yet established a pattern.

**Comment by benmgreene** [comment] 2015-04-01 13:46
Has anyone else noticed that having `meteor shell` running may be the cause of this error? It seems lately that everything runs smoothly until I open a shell, and then *poof*, it breaks. Close the shell, restart meteor, and it works again.

**Comment by jbbower** [comment] 2015-04-01 14:26
I have not tested when there is no shell, but I can say that having `meteor shell` does not ALWAYS cause this problem. In my comments above when I mentioned I had sporadically seen the `moment` object available I was working in the meteor shell.

**Comment by jamgold** [comment] 2015-04-01 16:07
In Meteor 1.1 this is still seems broken with moments:moment@2.9.0
```
± meteor shell       

Welcome to the server-side interactive shell!

Tab completion is enabled for global variables.

Type .reload to restart the server and the shell.
Type .exit to disconnect from the server and leave the shell.
Type .help for additional help.

> Package['momentjs:moment']
{ moment: undefined }
> 
```

**Comment by jamgold** [comment] 2015-04-01 16:40
As @benmgreene noted, this happens when being connected via `meteor shell`. After initially adding the package, a subsequent [meteor] server restart clears the global variable `moment`.

When not connected to the `shell` all works as expected.

**Comment by emmanuelbuah** [comment] 2015-04-01 19:08
Yep. Same here.

**Comment by jbbower** [comment] 2015-04-01 19:39
It seems that if I call `moment()` in any of my Meteor startup code on the server before I launch a shell, I then always (read "in the dozen times I tried") have `moment

**Comment by jamgold** [comment] 2015-04-01 19:48
@jbbower doesn't seem to work here. As soon as I connect via shell, and a server restart happens, the global `moment` variable is undefined

**Comment by jbbower** [comment] 2015-04-01 19:56
@jamgold, noted, thank you. I changed my comment so it doesn't lead anyone in the wrong direction.

**Comment by c316** [comment] 2015-04-01 21:36
Is anyone else here using a server side route with Iron Router? I feel like I've narrowed in on the problem, but wanted to see if this is unique to me or if others are also running with a server side route. Seems like something to do with the middleware stack used by iron router.

**Comment by jamgold** [comment] 2015-04-01 21:45
@c316 I am using server side routes in my test code, but after disabling them `meteor shell` still turns the global `moment` object to undefined after a code push

**Comment by c316** [comment] 2015-04-01 21:53
@jamgold I really can't seem to narrow in on the problem here and I think from the forums, to the Meteor issue to stackoverflow, that seems to be the theme of this issue, elusive....

**Comment by artisonian** [comment] 2015-04-01 23:29
https://github.com/meteor/meteor/issues/4010

Just to cross-reference this with an issue I opened for Meteor 1.0.4+

**Comment by chrisbolin** [comment] 2015-04-10 16:56
both https://github.com/meteor/meteor/issues/4010 and https://github.com/meteor/meteor/issues/4109 are closed now, but this problem remains. Should we have a separate issue open with Meteor?

**Comment by artisonian** [comment] 2015-04-10 17:51
`meteor shell` works fine with both Underscore and Moment for me (using the `devel` branch). Do you have another reproduction recipe?

**Comment by chrisbolin** [comment] 2015-04-10 18:08
nice! I haven't tested with Meteor's development branch yet, but I'll take your word for it. Thanks for the update!

**Comment by gwendall** [comment] 2015-04-21 21:42
+1

**Comment by Ehrs** [comment] 2015-06-23 17:01
+1

**Comment by Ehrs** [comment] 2015-06-23 17:03
+1 
`meteor 1.1.0.2` and `jeeeyul:moment-with-langs`  `2.8.3`  `Moment with locales`

**Comment by spencern** [comment] 2015-08-10 20:42
Any new updates on this? I'm running into it with `meteor 1.1.0.3` `momentjs:moment 2.10.6` and `momentjs:twix 0.7.0`

**Comment by AdamBrodzinski** [comment] 2015-08-31 19:06
+1 shutting down meteor shell and re-starting Meteor fixes it.

**Comment by artisonian** [comment] 2015-08-31 19:38
Fixed in https://github.com/meteor/meteor/commit/da87051f3498f3b121b66d38d7d6d970052e43a9 and https://github.com/meteor/meteor/commit/8a578e954b0a31a5e0418b42bfbb37399aae8395, but probably won't land until Meteor v1.2.

**Comment by mj1856** [comment] 2015-10-09 22:33
It looks like the current version of Meteor is now 1.2.0.2.  Can someone please verify the issue is fixed?  Thanks.

**Comment by abernix** [comment] 2015-10-10 07:25
Yes, the meteor shell/momentjs conflict is no longer happening for me in Meteor 1.2.0.2 – both of the commits referenced by @artisonian did land in Meteor 1.2.  This was always a Meteor problem with the server shell being involved, as far as I'm aware.

**Comment by mj1856** [comment] 2015-10-10 17:51
Thanks.

**Closed by mj1856** 2015-10-10 17:51 UTC
Labels: Troubleshooting
