### ISSUE TITLE
Locale en-SG is capitalized differently

### ISSUE THREAD

**Issue by mydea** [moment/moment#5024] opened 2019-03-04 08:03 UTC
**Describe the bug**

While all locales are always lowercased (e.g. `en-au`, `fr-ca`, ...), `en-SG` is capitalized. This is unexpected and makes automatic handling of locales harder than it needs to be. Also, e.g. `moment.locale('en-sg')` does not work, although it would be reasonable to expect it to.

**To Reproduce**

See all locales via `moment.locales()` - all are lowercased, except for `en-SG`.

**Expected behavior**
`en-SG` should be renamed to `en-sg`

**Moment-specific environment**

* This happens on moment@2.24

**Comment by kylekatarnls** [comment] 2019-03-04 09:13
I already warned about this when merged: https://github.com/moment/moment/pull/4951#issuecomment-464076691. But no reaction yet, thanks for the PR.

**Comment by beyb00lsky** [comment] 2019-03-04 21:29
hey, can I give it a try?

**Comment by beyb00lsky** [comment] 2019-03-04 21:30
hi, can I fix this?

**Comment by PN-linshifeng** [comment] 2019-03-05 02:35
bug：moment().format('YYYY-MM-DD HH:MM:SS') =》"2019-03-05 10:03:79"  SS>59

**Comment by ashsearle** [comment] 2019-03-05 12:11
@PN-linshifeng irrelevant to this issue and not a bug: use `mm:ss`, not `MM:SS`

**Comment by rostacik** [comment] 2019-03-08 19:34
I just wanted to open a ticket so at least I will post a link to play with for maintainers : 

[jsfiddle](https://jsfiddle.net/rostacik/yf7p9g3m/17/)

**Closed** 2020-05-12 12:57 UTC

**Comment by Jaxsun** [comment] 2020-06-04 22:23
I am seeing warnings from webpack about this locale's casing. I haven't attempted a minimal reproduction as of yet however.

```
WARNING in ./node_modules/moment/locale/en-SG.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* /home/jaxsun.mccarthy/project/web/node_modules/moment/locale/en-SG.js
    Used by 2 module(s), i. e.
    /home/jaxsun.mccarthy/project/web/node_modules/moment/locale sync /^\.\/.*$/
* /home/jaxsun.mccarthy/project/web/node_modules/moment/locale/en-sg.js
    Used by 2 module(s), i. e.
    /home/jaxsun.mccarthy/project/web/node_modules/moment/locale sync /^\.\/.*$/
 @ ./node_modules/moment/locale/en-SG.js
 @ ./node_modules/moment/locale sync ^\.\/.*$
 @ ./node_modules/moment/moment.js
```

This is with moment 2.26.0

**Comment by Jaxsun** [comment] 2020-06-04 23:20
I think I resolved this warning for myself locally. It seems like yarn may have mistakenly kept both files after a version upgrade since they only differed by case or something like that. After clearing my yarn cache and deleting node_modules the issue disappeared.

**Comment by peterchaula** [comment] 2020-11-25 06:46
@Jaxsun, that is a bug in yarn then. What version of yarn were you on when you had this issue?

**Comment by Jaxsun** [comment] 2021-02-01 23:16
@peterchaula I am currently on 1.22.5, I think I'm on the same version I was in June, but cannot be 100% sure. Sorry for the late reply. I haven't had this issue recur since I commented on this ticket.
