### ISSUE TITLE
.diff method returns wrong value for days

### ISSUE THREAD

**Issue by aminkh17** [moment/moment#4992] opened 2019-02-10 15:45 UTC
**Describe the bug**
The diff for `days` method while expected return value for 1 on all time-zones but it gets 0 only for the mentioned dates below in the specific time-zone (Tehran).
Differences days between 23 March and 22 March.

**To Reproduce**
1. Set your timezone to +3:30 Tehran
2. Execute the following statement

```
var days = moment("2019-03-23").diff("2019-03-22", 'days'); 
console.log(days); // Must be 1 but return 0

```
http://jsfiddle.net/t7qzp8m9/

**Expected behavior**
Must return 1 but it returns 0

**Screenshots**
Attached
![image](https://user-images.githubusercontent.com/6000852/52535688-769a3600-2d8c-11e9-9f41-a417a15dffb4.png)

**Desktop (please complete the following information):**
 - OS: All
 - Browser All
 - Version All

**Smartphone (please complete the following information):**
 - Device: All
 - OS: All
 - Browser All
 - Version All

**Moment-specific environment**

* The time zone setting of the machine the code is running on
* The time and date at which the code was run

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
```
VM76731:1 Sun Feb 10 2019 19:12:52 GMT+0330 (Iran Standard Time)
VM76731:2 2/10/2019, 7:12:52 PM
VM76731:3 -210
VM76731:4 Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
VM76731:5 2.22.1

**Additional context**
NA

**Comment by waseemahmad31** [comment] 2019-02-10 19:23
You are facing this issue because In Iran on 22 March 2019, 00:00:00 clocks are turned forward 1 hour to 22 March 2019, 01:00:00 local daylight time instead. So technically difference between "2019-03-23 00:00:00" and "2019-03-22 00:00:00" will be less than 1 day (24 hours). this is whay you are getting "0".

**Comment by aminkh17** [comment] 2019-02-12 14:51
It's kind of funny and maybe correct technically, however, the date difference is 1 when you see 23 and 22. I added  1 hour to it and become returning value 1.
`var days = moment("2019-03-23 1:00").diff("2019-03-22 1:00", 'days');`

**Comment by marwahaha** [comment] 2020-05-17 12:11
closing as duplicate of https://github.com/moment/moment/issues/5118

**Closed by marwahaha** 2020-05-17 12:11 UTC
