### ISSUE TITLE
week calculation differs other way around

### ISSUE THREAD

**Issue by Morriz** [moment/moment#2413] opened 2015-06-10 09:13 UTC
```
moment().year(2015).week(1).endOf('week')
Moment {_isAMomentObject: true, _isUTC: false, _locale: Locale, _d: Sun Jan 11 2015 23:59:59 GMT+0100 (CET)}
moment().year(2015).week(1).startOf('week')
Moment {_isAMomentObject: true, _isUTC: false, _locale: Locale, _d: Mon Jan 05 2015 00:00:00 GMT+0100 (CET)}
moment.unix(1420830600)
Moment {_isAMomentObject: true, _i: 1420830600000, _isUTC: false, _locale: Locale, _d: Fri Jan 09 2015 20:10:00 GMT+0100 (CET)}
moment.unix(1420830600).week()
2
```

**Comment by Morriz** [comment] 2015-06-10 09:15
The date is definitely in week 1, but moment.unix thinks it's week 2

**Comment by Morriz** [comment] 2015-06-10 09:44
I got it to work by telling moment that week 1 should contain jan 1st:

doy: 1

YAY!

**Comment by Morriz** [comment] 2015-06-10 09:45
weird tho....feels like I made two separate entities within moment work together...feels wrong

**Comment by mj1856** [comment] 2015-06-14 00:00
Sorry, but I cannot reproduce.  No matter what I try, I don't get Monday Jan 5th for the start of week 1.

What locale and version are you using?

```javascript
console.log(moment.version);
console.log(moment.locale());
```

**Comment by Morriz** [comment] 2015-06-14 08:36
Sry, forgot: nl_NL

**Comment by mj1856** [comment] 2015-06-14 17:48
And version?

**Comment by Morriz** [comment] 2015-06-14 19:25
Ah, yes, that is 2.10.3

**Comment by mj1856** [comment] 2015-06-15 00:06
Sorry, but I still can't reproduce.  I've set my time zone and moment locale for the Netherlands, and still I get different dates than you showed.

![image](https://cloud.githubusercontent.com/assets/1396388/8151072/10b85260-1303-11e5-9751-a40f5587320c.png)

What OS and browser are you using?

**Comment by mj1856** [comment] 2015-06-15 00:07
Also, I would expect Jan 9 to fall on week 2, so it's the early part of the problem that is concerning, not the later.

**Comment by maggiepint** [comment] 2016-04-01 01:04
Closing since it has been quite a while and this hasn't been reproduced. Feel free to re-open with us if you want to.

**Closed by maggiepint** 2016-04-01 01:04 UTC
Labels: Troubleshooting
