### ISSUE TITLE
diff between two different dates is the same number of days

### ISSUE THREAD

**Issue by codeHatcher** [moment/moment#5131] opened 2019-06-04 06:25 UTC
**Describe the bug**
When I look at the diff duration in days between 3-11-19 and 3-1-19 vs 3-10-19 and 3-1-19 I get the same number of days (9)

**To Reproduce**
1. Go to https://jsfiddle.net/wtyzmbk9/3/
2. You will see the diff days calculation for each is 9 days

**Expected behavior**
For two different date diff durations I expect to get a different number of days. I expect one to be 10 days

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: macOS and JsFiddle

**Moment-specific environment**

* The time zone setting of the machine the code is running on
PDT
* The time and date at which the code was run
11:20pm
* Other libraries in use (TypeScript, Immutable.js, etc)
JavaScript 1.7 via JSFiddle
Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
---
Mon Jun 03 2019 23:21:39 GMT-0700 (Pacific Daylight Time)
(index):45 6/3/2019, 11:21:39 PM
(index):46 420
(index):47 Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Mobile Safari/537.36
(index):48 2.24.0
```

**Additional context**
I read on the website the difference between date math and time math so I realize this may just be flat out not a concern. Although in this case, I am not sure if there should be that inconsistency. I read on another issue that you were trying to make this work for the most common use-case, age-gating, which this would seem to fail for. As an aside, if someone has a good "date math" JS library that would be really helpful as well

**Comment by marwahaha** [comment] 2019-06-10 07:49
Hi! Thanks for filing this issue! 

It's probably related to daylight savings on March 10 2019 in the US, since there are only (9*24 + 23) hours difference between March 1 and March 11.

Humanize also takes care of it, but it doesn't help with your use case:
```
moment.duration(originDate.diff(date2)).humanize()
"9 days"
moment.duration(originDate.diff(date1)).humanize()
"10 days"
```

**Comment by marwahaha** [comment] 2019-06-10 07:57
closing as duplicate of https://github.com/moment/moment/issues/5118

**Closed by marwahaha** 2019-06-10 07:57 UTC
