### ISSUE TITLE
Wrong week dates for 2017

### ISSUE THREAD

**Issue by BartVanBeurden** [moment/moment#3911] opened 2017-04-13 12:47 UTC
**Description of the Issue and Steps to Reproduce:**

Start of / end of week is wrong for 2017 (using custom locale)

When using a locale where:
- first day of week = 1 (monday)
- first day of year = 1 (january 1st)

I expect week 1 of 2017 to start on 2016-12-26 (monday) and end on 2017-01-01.  
In reality, week 1 of 2017 starts on 2017-01-02 and ends on 2017-01-08.

**Code to reproduce:**

```
moment.locale("test", {
    parentLocale: "en",
    week: {
        dow: 1,
        doy: 1
    }
});

moment().locale("test").set("week", 1).startOf("week") // should be 2016-12-26
moment().locale("test").set("week", 1).endOf("week") // should be 2017-01-01
```

This is either a bug or the documentation is wrong on how dow / doy works.

**Environment:**

Chrome 57 on Windows  
Firefox 52 on Windows

**Other information that may be helpful:**

- Time Zone: UTC +01:00 (DST)
- Date: 2017-04-13 14:43

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```
Thu Apr 13 2017 14:44:12 GMT+0200 (Romance Standard Time) 
13/4/2017 14:44:12 
-120 
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0 
2.18.1
```

**Comment by shlangus** [comment] 2017-04-17 08:13
It's correct that the first week of 2017 starts on 2nd Jan.
> The  first  calendar  week  of  a  year  is  that  one  which  includes  the  first  Thursday  of  that  year
[See ISO 8601-2004 (part 2.2.10) for details](http://dotat.at/tmp/ISO_8601-2004_E.pdf)

**Comment by BartVanBeurden** [comment] 2017-04-17 14:28
You're talking about isoWeek.

I'm talking about week, specifically with a locale where dow = 1 and doy = 1.

**Comment by butterflyhug** [comment] 2017-04-17 15:40
It looks like the documentation is inconsistent about the behavior of dow and doy:

http://momentjs.com/docs/#/i18n/changing-locale/:
```js
    week : {
        dow : 1, // Monday is the first day of the week.
        doy : 4  // The week that contains Jan 4th is the first week of the year.
    }
```

http://momentjs.com/docs/#/i18n/locale-data/:
```js
localeData.firstDayOfWeek();  // 0-6 (Sunday to Saturday)
localeData.firstDayOfYear();  // 0-15 this and the first day of week are used
                              // to determine which is the first week of the
                              // year. dow == 1 and doy == 4 means week starts
                              // Monday and first week that has Thursday is the
                              // first week of the year (but doy is NOT simply
                              // Thursday).
```

I don't *think* these two descriptions are equivalent.

@ichernev Do you know offhand what the intended behavior is?  I suspect the latter description is more accurate, but I don't know for sure.

**Comment by mj1856** [comment] 2017-04-17 16:15
We've been through this discussion before.  There's an open docs issue at moment/moment.js#279.

**Comment by danielbartsch** [comment] 2017-08-23 07:45
What about the wrong tests [here](https://github.com/moment/moment/blob/develop/src/test/moment/week_year.js#L86-L96)?

**Comment by ichernev** [comment] 2017-12-22 04:47
A few lines of code answer a lot of questions:

```javascript
// start-of-first-week - start-of-year
function firstWeekOffset(year, dow, doy) {
    var // first-week day -- which january is always in the first week (4 for iso, 1 for other)
        fwd = 7 + dow - doy,
        // first-week day local weekday -- which local weekday is fwd
        fwdlw = (7 + createUTCDate(year, 0, fwd).getUTCDay() - dow) % 7;

    return -fwdlw + fwd - 1;
}
```

Now, what the hell is `dow` and `doy` -- I don't know. Maybe for a major release we can fix this madness and have doy be the weekday that determines the first week, now it is just the 2 numbers that you put in the formula above.

**Comment by marwahaha** [comment] 2018-04-04 08:33
Closing since there is plenty of discussion in https://github.com/moment/momentjs.com/issues/279

**Closed by marwahaha** 2018-04-04 08:33 UTC
Labels: Discussion, Documentation
