### ISSUE TITLE
ISO regex does not support only years

### ISSUE THREAD

**Issue by hartman** [moment/moment#4156] opened 2017-09-04 14:32 UTC
**Description of the Issue and Steps to Reproduce:**
While looking into parsedDateParts, I noticed that when creating a date with just a year, parsedDateParts is not filled with the year. Some investigation shows, that this is because in order to parse this date, moment.js has to fallback to createFromInputFallback(). Apparently years only is not recognised by the ISO regex'es of moment.js As createFromInputFallback is deprecated, this seems like a problem to me.

Especially 4 digit years seems like part of the minimal expected support set for ISO dates (especially, since it does seem to support extended years aka. ±YYYYYY). The regexes probably should be corrected for this.

```
> moment('1926').parsingFlags().parsedDateParts
< [] (0)
> moment('1926').isValid()
< true
> moment('1926').year()
< 1926
```

Direct test of the two regexes
```
"2016".match( /^\s*((?:[+-]\d{6}|\d{4})-(?:\d\d-\d\d|W\d\d-\d|W\d\d|\d\d\d|\d\d))(?:(T| )(\d\d(?::\d\d(?::\d\d(?:[.,]\d+)?)?)?)([\+\-]\d\d(?::?\d\d)?|\s*Z)?)?$/ );
null
"2016".match( /^\s*((?:[+-]\d{6}|\d{4})(?:\d\d\d\d|W\d\d\d|W\d\d|\d\d\d|\d\d))(?:(T| )(\d\d(?:\d\d(?:\d\d(?:[.,]\d+)?)?)?)([\+\-]\d\d(?::?\d\d)?|\s*Z)?)?$/ );
null
```

**Environment:**
* Safari, 10.1.2 (12603.3.8)
* Mac OS 10.12.6 (16G29)

but also
* Firefox 54.0.1

**Other information that may be helpful:**
[Log] Mon Sep 04 2017 15:25:06 GMT+0200 (CEST)
[Log] 9/4/2017, 3:25:06 PM
[Log] -120
[Log] Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8
[Log] 2.18.1

**Comment by hartman** [comment] 2017-09-04 19:11
Fix:

```
> "2016".match( /^\s*((?:[+-]\d{6}|\d{4})(?:-(?:\d\d-\d\d|W\d\d-\d|W\d\d|\d\d\d|\d\d))?)(?:(T| )(\d\d(?::\d\d(?::\d\d(?:[.,]\d+)?)?)?)([\+\-]\d\d(?::?\d\d)?|\s*Z)?)?$/ );

< ["2016", "2016", undefined, undefined, undefined] (5)
```
and
```
> "2016".match( /^\s*((?:[+-]\d{6}|\d{4})(?:\d\d\d\d|W\d\d\d|W\d\d|\d\d\d|\d\d)?)(?:(T| )(\d\d(?:\d\d(?:\d\d(?:[.,]\d+)?)?)?)([\+\-]\d\d(?::?\d\d)?|\s*Z)?)?$/ );

< ["2016", "2016", undefined, undefined, undefined] (5)
```

**Comment by icambron** [comment] 2017-09-14 10:18
Year-only ISO dates are a little silly in Moment, since Moment only represents specific times; i.e. if this works, it will be because "2016" means exactly "2016-01-01T00:00:00.000", which probably not that useful. However, I'm not really against it and I think we take a PR.

**Comment by icambron** [comment] 2017-12-29 16:21
FWIW, I ended up adding support for this to Luxon

**Comment by marwahaha** [comment] 2018-03-05 08:44
I'm going to close as duplicate of #3918 .

Please re-open if this is not the case.

**Closed by marwahaha** 2018-03-05 08:44 UTC
Labels: Enhancement
