### ISSUE TITLE
Lack of RFC3339 support

### ISSUE THREAD

**Issue by mcandre** [moment/moment#5082] opened 2019-04-22 19:09 UTC
RFC3339 is a widely supported format for machine and human readable, ISO8601 compliant timestamps. However, moment.js offers neither premade functions nor premade pattern strings for encoding/decoding RFC3339.

Please fix this, so that moment.js can interoperate with this common format. Otherwise, users are tempted to roll their own code and introduce bugs.

**Comment by marwahaha** [comment] 2019-05-07 07:27
Thanks for opening this request.
Duplicate of #5045

**Closed by marwahaha** 2019-05-07 07:27 UTC
