### ISSUE TITLE
1 test failed. relative time:custom rounding (2721.3) 

### ISSUE THREAD

**Issue by verzil** [moment/moment#3832] opened 2017-03-14 05:24 UTC
### Client info
```
Date String   : Tue Mar 14 2017 01:23:36 GMT-0400 (EDT)
Locale String : 3/14/2017, 1:23:36 AM
Offset        : 240
User Agent    : Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3013.3 Safari/537.36
Moment Version: 2.17.1
```

====

### relative time:custom rounding (2721.3) 

Round down towards the nearest day

```javascript
// Expected in 30 days
// Actual   in a month
"in a month" === "in 30 days"
```

**Comment by icambron** [comment] 2017-03-16 01:26
Closing as a dupe of #3801

**Closed by icambron** 2017-03-16 01:26 UTC
