### ISSUE TITLE
When I use MacOS to switch the system language to Traditional Chinese, the language of the plugin package is garbled

### ISSUE THREAD

**Issue by Famer-Y** [moment/moment#5355] opened 2020-01-18 06:49 UTC
**Describe the bug**
When I use MacOS to switch the system language to Traditional Chinese, the language of the plugin package is garbled

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.6
 - Browser Chrome 
 - Version 79.0.3945.117

Please run the following code in your environment and include the output:
```
moment.js:4988 Uncaught SyntaxError: Invalid regular expression: missing /
```

**Comment by ashsearle** [comment] 2020-01-20 11:02
Which plugin?

**Comment by Famer-Y** [comment] 2020-01-21 13:29
moment.js

**Comment by Famer-Y** [comment] 2020-01-21 13:30
I used it in Chrome extension

**Comment by marwahaha** [comment] 2020-05-12 13:35
Hi! Thanks for filing this issue! Unfortunately, I can't reproduce this. Could you provide any other information?

**Comment by marwahaha** [comment] 2020-05-18 10:04
duplicate of https://github.com/moment/moment/issues/5355

**Closed by marwahaha** 2020-05-18 10:04 UTC
