### ISSUE TITLE
Issue when get timestamp from date

### ISSUE THREAD

**Issue by renatobezerra** [moment/moment#3681] opened 2016-12-26 21:27 UTC
I founded a issue when get timestamp from date.

When pick up a date from input text, it is subtracted 1 day from the date.

I try this:

moment('17/01/1981', 'DD/MM/YYYY').format('x')

In chrome (v55.0.2883.95 64-bit), I got 348548400000
In Safari (v 10.0.2), I got 348544800000. (Wrong).

**Comment by icambron** [comment] 2016-12-31 20:01
I couldn't reproduce this on Safari 10.0.2. I get 348555600000 which is right in my timezone. The two timestamps from your different browsers are off by exactly an hour (which in this case flips the date to the previous day). Does your locale have a DST that day perhaps that's being handled differently by the different browsers?

**Comment by icambron** [comment] 2017-01-06 00:15
Closing for age. If you have that info, tag me in the reply and I'll reopen.

**Closed by icambron** 2017-01-06 00:15 UTC
Labels: Troubleshooting
