### ISSUE TITLE
3 tests failed. locale:ja:calendar last week (1313.13) locale:ja:calendar last week (1313.14) locale:ja:calendar last week (1313.15) 

### ISSUE THREAD

**Issue by GMartigny** [moment/moment#4929] opened 2019-01-04 12:59 UTC
### Client info
```
Date String   : Fri Jan 04 2019 13:56:11 GMT+0100 (heure normale d’Europe centrale)
Locale String : 04/01/2019 à 13:56:11
Offset        : -60
User Agent    : Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
Moment Version: 2.23.0
```

====

### locale:ja:calendar last week (1313.13) 

Today - 6 days current time

```javascript
// Expected 先週土曜日 13:55
// Actual   土曜日 13:55
"土曜日 13:55" === "先週土曜日 13:55"
```

====

### locale:ja:calendar last week (1313.14) 

Today - 6 days beginning of day

```javascript
// Expected 先週土曜日 00:00
// Actual   土曜日 00:00
"土曜日 00:00" === "先週土曜日 00:00"
```

====

### locale:ja:calendar last week (1313.15) 

Today - 6 days end of day

```javascript
// Expected 先週土曜日 23:59
// Actual   土曜日 23:59
"土曜日 23:59" === "先週土曜日 23:59"
```

**Comment by marwahaha** [comment] 2019-01-17 09:41
Thanks for opening this request.

duplicate of https://github.com/moment/moment/issues/4920

**Closed by marwahaha** 2019-01-17 09:41 UTC
