### ISSUE TITLE
Invalid Date

### ISSUE THREAD

**Issue by Hybueno09** [moment/moment#5584] opened 2020-06-05 09:40 UTC
**Describe the bug**
The result of `moment('10:32:17 027').isValid()` is `false`. And `moment('10:32:17 027').format('HH:mm:ss SSS')` is `Invalid Date`.

Another case is that result of `moment('10:32:17 227').isValid()` is `true`. But the result of `moment('10:32:17 227').format('HH:mm:ss SSS')` is `10:32:17 000`.I think the result should be `10:32:17 227` or `Invalid Date` like above case.

**To Reproduce**

**Expected behavior**
The two case should be the same result

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome
 - Version 80

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())  is  Fri Jun 05 2020 17:38:49 GMT+0800 (中国标准时间)
console.log((new Date()).toLocaleString())  is 2020/6/5 下午5:39:15
console.log((new Date()).getTimezoneOffset()) is -480
console.log(navigator.userAgent) is Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.165 Electron/8.2.4 Safari/537.36
console.log(moment.version) is 2.24.0
```

**Comment by Alanscut** [comment] 2020-06-08 03:28
Hi Hybueno09, duplicate of #5314 and #5464 ， I have not found an effective solution 😿  .

**Comment by Alanscut** [comment] 2020-06-09 01:36
@Hybueno09 This is caused by the origin `Date` object, you should pass in `format` when instantiating `Moment`.
```javascript
moment('10:32:17 227', 'HH:mm:ss SSS').isValid()  // true
````
<img width="318" alt="issue" src="https://user-images.githubusercontent.com/21104054/84096485-9f8c1300-aa34-11ea-93f2-890b3d5b598e.png">

**Comment by Hybueno09** [comment] 2020-06-11 01:28
I see.So the problem it's not related with `moment`.
If that so ,I will close the issue

**Comment by marwahaha** [comment] 2020-06-11 21:17
I think that is the case. Thanks @Hybueno09

**Closed by marwahaha** 2020-06-11 21:17 UTC
Labels: Troubleshooting
