### ISSUE TITLE
Localized date with day and month (without year), or generic localized solution

### ISSUE THREAD

**Issue by f-aubert** [moment/moment#4689] opened 2018-07-03 11:11 UTC
I would need a localized variation of LL, but without year token.
In other word LLMD (localized month day), defined for example as D MMMM for 'fr' and MMMM D  for 'de'.

But it would soon be a nightmare to handle all kind of variation to localized formats, maybe generic syntax could be implemented:
LL^Y or something like that would remove all Y tokens from the standard LL
L[fr]=D MMMM,L[de]=MMMM D or something like that would on the fly choose select the corresponding format according to the current locale.

In my case I'm using moment via Angular Material (DatePicker), but this should concern all of moment usages. I'd gladly brainstorm / test with your team.

**Comment by ronnyroeller** [comment] 2018-10-08 12:40
+1

**Comment by ronnyroeller** [comment] 2018-10-08 12:41
For reference, here a similar request: https://github.com/moment/moment/issues/4325

**Comment by timhecker** [comment] 2018-10-31 13:33
Any idea about this?

**Comment by marwahaha** [comment] 2019-01-19 10:09
duplicate of https://github.com/moment/moment/issues/3341

**Closed by marwahaha** 2019-01-19 10:09 UTC
