### ISSUE TITLE
WARNING in ./node_modules/.2.19.0@moment/src/lib/locale/locales.js Module not found: Error: Can't resolve './locale'

### ISSUE THREAD

**Issue by fengxinming** [moment/moment#4228] opened 2017-10-11 03:04 UTC
WARNING in ./node_modules/.2.19.0@moment/src/lib/locale/locales.js
Module not found: Error: Can't resolve './locale' in 'D:\demows\h5-travel-plus\node_modules\.2.19.0@moment\src\lib\locale'

plugins: [
    new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/)
]

**Comment by saurabhnemade** [comment] 2017-10-11 04:31
@	fengxinming

Duplicate of #4218 .
`npm install moment@2.18.1` will fix it for now.

**Comment by mengcan555** [comment] 2017-10-11 05:23
package.json里锁定版本吧 "moment": "2.18.1",

**Comment by ekiliqua** [comment] 2017-10-11 06:37
Yes, i have the same problem and i fix it uninstalling last version and installing 2.18.1.

**Comment by joseneto-fixeads** [comment] 2017-10-11 09:55
I back to 2.18.1 and fixed

**Comment by mfazul** [comment] 2017-10-11 11:39
I also faced same issue and reverted to 2.18.1, why this is not fixed in latest version?

**Comment by johannesjo** [comment] 2017-10-11 13:07
I would assume that this related to #4042 [bugfix] "Make auto locale loading for node not mess webpack"

**Comment by mj1856** [comment] 2017-10-11 15:02
Dup #4216

**Closed by mj1856** 2017-10-11 15:02 UTC

**Comment by guohuihuiguo** [comment] 2019-04-23 07:30
我降到了2.18.1 依然报这个错误，大家是如何解决的呢
