### ISSUE TITLE
2.19.0 error ci 

### ISSUE THREAD

**Issue by smokezp** [moment/moment#4230] opened 2017-10-11 12:24 UTC
2.19.0 
[36mfront-compile_1     |[0m WARNING in ./~/moment/src/lib/locale/locales.js
[36mfront-compile_1     |[0m Module not found: Error: Can't resolve './locale' in '/app/node_modules/moment/src/lib/locale'
[36mfront-compile_1     |[0m  @ ./~/moment/src/lib/locale/locales.js 65:16-60
[36mfront-compile_1     |[0m  @ ./~/moment/src/lib/locale/locale.js
[36mfront-compile_1     |[0m  @ ./~/moment/src/moment.js
[36mfront-compile_1     |[0m  @ ./resources/assets/js/bootstrap.js
[36mfront-compile_1     |[0m  @ ./resources/assets/js/vendor.js
2.18.0 work fine
check it

**Comment by johannesjo** [comment] 2017-10-11 12:54
This occurs when building with webpack (v2+).

**Comment by Alexintosh** [comment] 2017-10-11 13:29
@johannesjo I've got the same with v3+, which version are you using?

**Comment by johannesjo** [comment] 2017-10-11 13:34
I tried 2.5.0 and 3.6.0.

This is probably a duplicate of #4228.

**Comment by mj1856** [comment] 2017-10-11 15:02
Dup #4216

**Closed by mj1856** 2017-10-11 15:02 UTC
