### ISSUE TITLE
Business days (work days) would be a helpful unit for date manipulation

### ISSUE THREAD

**Issue by chevalierc** [moment/moment#3106] opened 2016-04-12 14:07 UTC
Business days (work days) would be a helpful unit for date manipulation

`new moment().add(14, 'work-days')`

**Comment by maggiepint** [comment] 2016-04-13 02:50
Duplicate of #1947. We would accept a pull request.

Also worth noting that there are a couple plugins floating around that do this.

**Closed by maggiepint** 2016-04-13 02:50 UTC
