### ISSUE TITLE
Error after updating to 2.11.0

### ISSUE THREAD

**Issue by PhilPJL** [moment/moment#2870] opened 2016-01-07 09:29 UTC
![capture](https://cloud.githubusercontent.com/assets/271656/12166876/d5450cf8-b520-11e5-9ce8-227245d63120.PNG)
![capture1](https://cloud.githubusercontent.com/assets/271656/12166877/d547d33e-b520-11e5-90bb-d2f94b814817.PNG)

Currently using 2.10.6 as part of Bootstrap.VS.Datetimepicker.CSS.
After updating to 2.11.0 I get the attached error.

**Comment by gokussx4** [comment] 2016-01-07 13:57
I am seeing the same problem. 2.10.6 worked fine but now the check to see if a module is loaded throws a module is undefined exception.

**Comment by mwoodbri** [comment] 2016-01-07 15:20
Duplicate of #2862

**Comment by ichernev** [comment] 2016-01-07 19:01
Will be fixed in 2.11.1 soon

**Closed by ichernev** 2016-01-07 19:01 UTC
