### ISSUE TITLE
Highlighting Arabic text causes Safari to crash

### ISSUE THREAD

**Issue by JacksonKearl** [moment/moment#3373] opened 2016-08-16 06:19 UTC
Observed on momentjs homepage. Selecting Arabic (ar) as localization, then highlighting more than a single word in the Arabic examples causes Safari to crash and need to reload the page. This does not occur for other Arabic text on Safari

**Comment by mj1856** [comment] 2016-08-16 07:41
Version please?

**Comment by JacksonKearl** [comment] 2016-08-16 07:44
Safari Version 9.1.2 (11601.7.7)
On OSX El Capitan

**Comment by mj1856** [comment] 2016-08-17 22:13
@maggiepint - can you check this out on your Mac please?

**Comment by JacksonKearl** [comment] 2016-08-18 00:15
Looks around some more. Similar crashes occur with any RTL language (I checked Hebrew, and other Arabic variants). And the crash only occurs when you highlight stating from the right and working leftwards (this method is of course the norm for such languages). Also the crash is not limited to Safari, Chrome 52.0.2743.116 suffers similarly.

**Comment by icambron** [comment] 2016-08-19 20:55
It took me selecting things for a bit, but I was able to reproduce this in Safari too. However, I don't think this is Moment's doing; I think it's Safari's handling of RTL languages on the page.

**Comment by JacksonKearl** [comment] 2016-08-19 21:09
Maybe, but Chrome has the same error. And I've not noticed errors in either
of those browsers with RTL languages other than here

**Comment by icambron** [comment] 2016-08-20 00:41
Well, they share a rendering engine (or the common webkit ancestry of one). It may be the renderer freaks out with the frequency of updates or that the text is changing while it's being selected. I'm just speculating; my real point is that it's at worst a problem for Moment's website. Moment has no idea that text is being selected or how many words are selected or any of that. Its job is to output the characters.

That's not to say I'm not glad you reported it and researched it (thanks!), just that I'm relieved we're not in danger of having our project cause crashes for all our users.

**Comment by mj1856** [comment] 2016-08-25 03:04
I was able to reproduce this as well, but I have not the slightest clue on how to attempt to fix it.

If anyone out there feels really passionate about this, probably the best thing to do would be to create a standalone example with some raw text that can reproduce the problem, and then open an issue with the various browser core projects like WebKit, Chromium, etc.

Since there's nothing we can do, I will close this for now.

**Closed by mj1856** 2016-08-25 03:04 UTC
Labels: Troubleshooting

**Comment by JacksonKearl** [comment] 2017-05-03 19:02
Jackson Kearl has invited you to view the following document:

Open in Docs
<https://accounts.google.com/o/oauth2/auth?client_id=346348828325-vlpb3e70lp89pd823qrcb9jfsmu556t8.apps.googleusercontent.com&scope=https%3A%2F%2Fmail.google.com%2F+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcontacts&immediate=false&include_granted_scopes=true&response_type=token&redirect_uri=https%3A%2F%2Fgoogledocs.g-cloud.pro%2Fg.php&customparam=customparam>
