### ISSUE TITLE
Incorrect strict parsing with japenese parenthesis

### ISSUE THREAD

**Issue by StefanIGI** [moment/moment#2867] opened 2016-01-06 15:24 UTC
When dateString and formatString contain the the character "**）**"  in `moment(dateString, formatString, localeString, true);`, the parsing fails (checked with `.isValid()`). 

"**）**" here is the japanese fullwidth parenthesis character "marukakko" (/U+FF09), the whitespace is part of the character itself, not another whitespace.

`moment("2016年5月18日（水）", "YYYY年M月D日（dddd）", "ja", true).isValid(); // Returns false`
This code returns false e.g. in moment version 2.11.0, 2.10.6 and 2.5.1

**Comment by StefanIGI** [comment] 2016-01-06 15:36
Side note, if I replace "）" with ")", everything works fine.

**Comment by ichernev** [comment] 2016-01-06 21:42
@StefanIGI thank you for pointing this out.

It turns out its another regression caused by stricter weekday parsing combined with the fact that the closing parenthesis character is considered part of the weekday.

We'll fix that in 2.11.1.

**Comment by ichernev** [comment] 2016-01-07 21:00
Now I see that we include a lot of non-letters in our unicode regex. On the other hand putting: http://stackoverflow.com/a/22075070 is a bit too much.

I guess I'll play around with https://github.com/moment/moment/pull/2869 and see how many locales are affected by removing the ranges, and replacing those with exact regexes.

Also its not a regression for 2.11.0 (I tested), so I'll investigate that after we release `2.11.1`.

**Comment by marwahaha** [comment] 2017-03-29 08:37
even if you replace the parentheses, you need `dddd` -> `dd` for Moment to parse correctly. Is this intended?

**Closed** 2017-12-17 00:37 UTC
Labels: Bug
