### ISSUE TITLE
moment.max() with inconsistent behavior, if one input is undefined

### ISSUE THREAD

**Issue by SchulteMarkus** [moment/moment#4934] opened 2019-01-07 12:44 UTC
I discovered from my point of view inconsistent behavior in the [moment.max()](https://github.com/moment/moment/blob/develop/src/lib/moment/min-max.js#L59)-function, if one input variable is undefined.

From https://jsfiddle.net/v49gbfkj/1/

```
var now = moment(),
    future = now.clone().add(1, 'month'),
    past = now.clone().subtract(1, 'month');
var notdefined;

var maxFuture = moment.max(notdefined, future);
console.log(maxFuture.format('LLLL'));

var maxPast1 = moment.max(notdefined, past);
console.log(maxPast1);

moment.max(past, notdefined); // error
```

Result is:
1. maxFuture => as expected (value of _var future_)
2. maxPast => undefined (referenced to #3386, I think)
3. last command "error" => Uncaught TypeError: Cannot read property 'isValid' of undefined (referenced to #4316, I think)

**Expected behavior**
- 2nd result should be in my opinion value of _var past_. Or, for being consistent, 1st result should be _undefined_, too.
- 3rd result should be the same as the 2nd one

**Use case**
You might wonder about my use case, here it is (pseudo code):

```
var ultimateMaxMoment;
someLoop {
    var loopMoment = <some-moment>;
    ultimateMax = moment.max(ultimateMax, loopMax);
}
```

_In some cases_, the use case works fine.

**moment.min()**

From what I can see in the source, code, I expect moment.min() to have similar problems.

**Comment by ichernev** [comment] 2019-01-10 15:33
All methods that deal with moment-like objects treat undefined as now. That's how it works. Its not pretty, but its a fact.

As stated in the other issue, we could change this in the next major release.

**Comment by marwahaha** [comment] 2019-01-19 08:54
@ichernev - This example shows `moment.max()` doesn't handle `undefined` as `moment()` in all places. Sometimes there's an error, sometimes not...

**Comment by marwahaha** [comment] 2020-05-18 08:50
duplicate of https://github.com/moment/moment/issues/3386

**Closed by marwahaha** 2020-05-18 08:50 UTC
Labels: Breaking change
