### ISSUE TITLE
1 test failed. relative time:custom rounding (2721.3) 

### ISSUE THREAD

**Issue by bbangkwan** [moment/moment#3841] opened 2017-03-16 05:25 UTC
### Client info
```
Date String   : Thu Mar 16 2017 14:25:06 GMT+0900 (대한민국 표준시)
Locale String : 2017. 3. 16. 오후 2:25:06
Offset        : -540
User Agent    : Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36
Moment Version: 2.17.1
```

====

### relative time:custom rounding (2721.3) 

Round down towards the nearest day

```javascript
// Expected in 30 days
// Actual   in a month
"in a month" === "in 30 days"
```

**Comment by marwahaha** [comment] 2017-03-16 05:30
Thanks for making an issue.

This is a duplicate of #3801

**Closed by marwahaha** 2017-03-16 05:30 UTC
