### ISSUE TITLE
endof returns wrong number of days in case of 94 , 1994 

### ISSUE THREAD

**Issue by codeRoSU** [moment/moment#3634] opened 2016-12-01 13:15 UTC
**Description of the Issue and Steps to Reproduce:**

*month = 'april'*
*year = '1994'*
*year = '94'*

**Environment:**

*Examples: Node.JS 6.3.2 on Ubuntu 16.0.4*
This example will print all the wrong date;

```js


const moment = require('moment');
let month = 'april';

for(let i = -20000 ; 20000 > i ; i++){
    let year = `${i}`;
    var rest = moment(`${month}-${year}`,'MMMM-YYYY').endOf('month').get('D')
  
  if(rest == 1){
      console.log(rest,year)
  }
}
```

**Other information that may be helpful:**
```js
moment("1993-04-01T00:00:00.000")
moment("1994-04-01T01:00:00.000") gets extra hour.
```

If you are reporting an issue, please run the following code in the environment you are using and include the output:

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Comment by icambron** [comment] 2016-12-04 17:08
I can't reproduce this. This looks fine for me:

```js
> moment('April 1994', 'MMMM YYYY').endOf('month').date()
30
```

Admittedly, I'm on Node 6.6.0 on OSX, but I'd be surprised if that's the difference. What time zone is your computer set to? If you set `TZ=etc/utc` as env var, do you still see the issue?

I don't know what you mean by this:

```js
moment("1994-04-01T01:00:00.000") gets extra hour.
```

I mean, I see that the string sets the time to 1 hour, but I don't understand what you mean to communicate by that.

**Comment by flakolefluk** [comment] 2016-12-05 13:53
Couldn't reproduce your issue, everything seems to work fine. Node:6.2.2 Ubuntu 16.04 LTS

**Comment by maggiepint** [comment] 2016-12-12 22:22
Closing as this has not been reproduced.

**Closed by maggiepint** 2016-12-12 22:22 UTC
Labels: Troubleshooting
