### ISSUE TITLE
2.25.1 has backward compatibility issues

### ISSUE THREAD

**Issue by Karthik-Shanmugasundaram** [moment/moment#5508] opened 2020-05-04 10:24 UTC
we are experiencing backward compatibility issues with 2.25.1, when reverted to 2.24.0... it is good.

1) "export 'isMoment' (imported as 'moment') was not found in 'moment'

2) ./node_modules/moment/src/lib/locale/locales.js
Module not found: Error: Can't resolve './locale' in '/node_modules/moment/src/lib/locale'

**Comment by romanzipp** [comment] 2020-05-04 10:57
Duplicate of #5497

**Comment by Mokette** [comment] 2020-05-04 11:45
Also duplicate of https://github.com/moment/moment/issues/5506, https://github.com/moment/moment/issues/5507

**Comment by sandfrozen** [comment] 2020-05-04 12:19
This error occurs in **moment 2.25.1**:
Object.localMoment Uncaught error handled globally. TypeError: a is not a function

Temp solution: "moment": "2.24.0"

**Comment by buffcode** [comment] 2020-05-04 12:21
Let's be optimistic ;)
`^2.24 <2.25 || ^2.26`

**Comment by ichernev** [comment] 2020-05-04 12:30
2.25.2 will fix this, but it will also include all locales in the bundle, unless you explicitly say in your configuration that you don't want that.

**Closed by ichernev** 2020-05-04 12:30 UTC
