### ISSUE TITLE
Add ISO parsing for year only strings

### ISSUE THREAD

**Issue by honestserpent** [moment/moment#4050] opened 2017-06-30 06:54 UTC
**Description of the Issue and Steps to Reproduce:**

Moment does not handle year only Strings eg. '2017' and throws a deprecation warning and says "that's not an ISO string".

I think it would be useful feature to have.

I open this issue on suggestion from @icambron in [issue 4048 (closed)](https://github.com/moment/moment/issues/4048)

**Comment by marwahaha** [comment] 2017-12-29 07:11
I'm going to close this as a duplicate of #4156 - there's more discussion over there.

**Closed by marwahaha** 2017-12-29 07:11 UTC
Labels: Enhancement
