### ISSUE TITLE
Bug: Incorrect toISOString(true) in node.js

### ISSUE THREAD

**Issue by wdetac** [moment/moment#4487] opened 2018-03-09 07:23 UTC
I am in +8 time zone.
I am using moment version 2.20.1 and node 9.4.0.
Local time is 2018-03-09 15:17:28 now.

Actual output:

    moment().toISOString(true); //2018-03-09T07:17:28.678+08:00

Expected output:

    moment().toISOString(true); //2018-03-09T15:17:28.678+08:00

**Comment by ashsearle** [comment] 2018-03-11 17:34
This sounds like a duplicate of issue #4390.

Can you check that this is fixed in 2.21.0.

**Comment by wdetac** [comment] 2018-03-12 03:56
My fault, thanks yes it is perfectly fixed after the update, thanks.

**Closed** 2018-03-12 03:57 UTC
