### ISSUE TITLE
TypeScript definitions for TS>=3.1 are missing in the latest version (v2.25.0)

### ISSUE THREAD

**Issue by hossam-magdy** [moment/moment#5491] opened 2020-05-01 13:31 UTC
**Describe the bug**
Upgrading from 2.24.0 to 2.25.0 results into undefined typings due to introducing typesVersions field in package.json pointing to `ts3.1-typings/*`: [commit: f9e9fe](https://github.com/moment/moment/blob/2.25.0/package.json#L29-L34) while the dir `ts3.1-typings/` is completely missing from the package build 📦 ([`scripts/npm_prepublish.sh`](https://github.com/moment/moment/blob/2.25.0/scripts/npm_prepublish.sh#L32-L43))

**To Reproduce**
1. `npm install moment@2.25.0`
2. `import moment from 'moment';`
3. Use the latest TypeScript version, currently `3.8.3` (or any version >=3.1)

**Expected behavior**
Include `ts3.1-typings/` dir in the package build

**Screenshots**
![Screenshot 2020-05-01 at 15 28 48](https://user-images.githubusercontent.com/17128077/80808760-8172fd80-8bc0-11ea-94b6-4f9693d76a90.png)

**Comment by rvanlaarhoven** [comment] 2020-05-01 13:46
I think you're referring to the incorrect version numbers. `2.25.0` introduced the issue. Downgrading to `2.24.0` is a workaround for now.

**Comment by rvanlaarhoven** [comment] 2020-05-01 13:47
Duplicate of https://github.com/moment/moment/issues/5486 by the way.

**Comment by hossam-magdy** [comment] 2020-05-01 17:36
UPDATE:
This commit https://github.com/moment/moment/commit/6e324334a50c262b5836618c3baf229081e1ec8e is supposed to fix the issue, but it is not yet released... looking forward to version >= `2.25.1`!

**Comment by ichernev** [comment] 2020-05-01 18:56
2.25.1 released.

**Closed by ichernev** 2020-05-01 18:56 UTC

**Comment by TheFastCat** [comment] 2020-05-01 19:25
errors remains with 2.25.1 installed

**Comment by Blackbaud-RakeshGarg** [comment] 2020-05-01 23:13
errors remain even 2.25.1
