### ISSUE TITLE
some kind of bug

### ISSUE THREAD

**Issue by ethanj** [moment/moment#2883] opened 2016-01-09 18:36 UTC
After wrestling with moment for a day, I believe I found a bug, which I reduced to the following simple example:

moment('1/1/15').valueOf() == moment.utc('1/1/15').valueOf()

moment('1/1/15').month(11).valueOf() == moment.utc('1/1/15').month(11).valueOf()

and 
moment('11/1/15').valueOf() == moment.utc('11/1/15').valueOf()

BUT...
moment('11/1/15').month(11).valueOf() != moment.utc('11/1/15').month(11).valueOf()

How can the valueOf two moments be equal, but calling month(11) on them makes them diverge?

**Comment by Anongnito** [comment] 2016-01-09 19:01
They all are equal to me. What exactly did you do to get the last example not to be equal?
![image](https://cloud.githubusercontent.com/assets/6831623/12217793/2f3af130-b703-11e5-9deb-d8bef35db080.png)

**Comment by mj1856** [comment] 2016-01-09 19:59
Probably DST related.  What country and time zone are you in?

Also, you should lot parse locale-specific formats without providing a format specifier.  Doing so reverts the parsing behavior to your browser's, and throws a warning to the console.

**Comment by ethanj** [comment] 2016-01-09 20:00
the same issue happens independent of format.. if i use unixtime for instance

**Comment by ethanj** [comment] 2016-01-09 20:01
i am PST in Los Angeles. But like the example shows, the valueOf the moments are the same, so how could DST matter after that point?

**Comment by ethanj** [comment] 2016-01-09 20:02
Here is another version of the same bug, showing the values:

foo = moment('1/1/15')
foo.valueOf()
 1420099200000
foo.month(11).valueOf()
 1448956800000

foo = moment.utc('1/1/15')
foo.valueOf()
 1420099200000
foo.month(11).valueOf()
 1448956800000



foo = moment('11/1/15')
foo.valueOf()
 1446361200000
foo.month(11).valueOf()
 1448956800000

foo = moment.utc('11/1/15')
foo.valueOf()
 1446361200000
foo.month(11).valueOf()
 1448953200000

**Comment by ethanj** [comment] 2016-01-09 20:05
and here it is with just numbers, no formatting:

foo = moment(1446361200000)
foo.valueOf()
1446361200000
foo.month(11).valueOf()
1448956800000

foo = moment.utc(1446361200000)
foo.valueOf()
1446361200000
foo.month(11).valueOf()
1448953200000

**Comment by mj1856** [comment] 2016-01-09 20:06
Nevermind, not DST related.  It's because months passed to the `month` function are 0-11, not 1-12 like they are when in a string.  This is expected.

**Comment by ethanj** [comment] 2016-01-09 20:06
anongnito.. I am literally just pasting the above directly into chrome debugger

**Comment by ethanj** [comment] 2016-01-09 20:07
I know months are 0-11.. I am passing 11, so why is it expected to be different?

**Comment by ethanj** [comment] 2016-01-09 20:09
the thing to notice is the last value of each section:
1448956800000
1448953200000

These should be the same

**Comment by ethanj** [comment] 2016-01-09 20:15
oh and BTW, you can pass 0-N to month, it is not limited to 11. In fact I am using it successfully in this way to iterate months (after working around this bug).

**Comment by mj1856** [comment] 2016-01-09 20:28
The value you're passing in is in November.  When you call `month(11)`, you're setting it to December.  Of course the resulting values will be different.  Perhaps looking at the fully formatted output will help you understand:

![image](https://cloud.githubusercontent.com/assets/1396388/12218161/bd4403c6-b6dc-11e5-849d-0f8989502c2c.png)

Also consider:

![image](https://cloud.githubusercontent.com/assets/1396388/12218173/2bbdb77a-b6dd-11e5-98c9-6f9ba4ef5ea1.png)

Even without the call to `month(11)`, they're not equal because the source values aren't equal.  The time in UTC is not the same as the same local time.

![image](https://cloud.githubusercontent.com/assets/1396388/12218177/49c4b7e6-b6dd-11e5-83d1-ca2136df2436.png)

**Comment by mj1856** [comment] 2016-01-09 20:32
Also, now that I run your examples from the very top of this post through moment, all four are inequal.  You stated the first three were equal, but they are not.

![image](https://cloud.githubusercontent.com/assets/1396388/12218187/c2298dc4-b6dd-11e5-8d36-f3f33b089d1c.png)

**Comment by Anongnito** [comment] 2016-01-09 20:33
If I get it right, you are using the American date format MM DD YY. 
By using the date 1/1/15, 1 = January, months are read from 0 to 11, so 0 in theory should be January.

###### First Example
foo = moment('1/1/15')
foo.valueOf()
**1420070400000**
foo.month(0).valueOf()
**1420070400000**

###### Second Example

foo = moment('11/1/15')
foo.valueOf()
1446336000000
foo.month(10).valueOf()
1446336000000

As you can see, it's the same. The correlation between actual real-life month date and the one written in code is -1. January is 0 and December is 11.

**Comment by mj1856** [comment] 2016-01-09 20:35
@Anongnito - Are you in a `+00:00` time zone, like the UK?

**Comment by Anongnito** [comment] 2016-01-09 20:36
@mj1856 Yes, I am in the UK, that would explain why the are equal for me.

**Comment by mj1856** [comment] 2016-01-09 20:39
Exactly.  UTC can only be equivalent to local time, if the local time is aligned with UTC.  @Anongnito would get `false` if evaluating a date in the summer while the UK is on BST (`+01:00`).   @ethanj should get `false` at any time, being in the US Pacific time zone.

And the month/day vs day/month format order is indeed problematic also, which is why you MUST specify a format string.  `moment('1/1/15','M/D/YY')`, not `moment('1/1/15')`.

**Comment by ethanj** [comment] 2016-01-09 20:42
I get this in the debugger:

moment('1/1/15').month(11).valueOf() == moment.utc('1/1/15').month(11).valueOf()
true

**Comment by ethanj** [comment] 2016-01-09 20:45
so yes there is some format issue with that one...

moment('1/1/15','M/D/YY' ).month(11).valueOf() == moment.utc('1/1/15', 'M/D/YY').month(11).valueOf()
false

I will create examples using just numbers so we avoid that as a factor.. one sec...

**Comment by ethanj** [comment] 2016-01-09 20:50
so can we agree about the following:

foo = moment(1446361200000)
foo.valueOf()
 1446361200000

foo = moment.utc(1446361200000)
foo.valueOf()
 1446361200000

if i understand the docs correctly, utc does not affect the internal representation, which is why the above are equal? In other words, valueOf() is timezone and DST independent?

**Comment by ethanj** [comment] 2016-01-09 20:52
this translates to:

moment(1446361200000).valueOf() == moment.utc(1446361200000).valueOf()
true

**Comment by mj1856** [comment] 2016-01-09 20:57
Yes, you are correct that `valueOf` is just the UTC-based raw timestamp, regardless of mode.  The difference comes in when you *parse* the string in input vs local mode.

**Comment by ethanj** [comment] 2016-01-09 20:59
but here is what i get:

moment(1446361200000).month(1).valueOf() == moment.utc(1446361200000).month(1).valueOf()
false
moment(1446361200000).month(2).valueOf() == moment.utc(1446361200000).month(2).valueOf()
false
moment(1446361200000).month(3).valueOf() == moment.utc(1446361200000).month(3).valueOf()
true
moment(1446361200000).month(4).valueOf() == moment.utc(1446361200000).month(4).valueOf()
true
moment(1446361200000).month(5).valueOf() == moment.utc(1446361200000).month(5).valueOf()
true
moment(1446361200000).month(6).valueOf() == moment.utc(1446361200000).month(6).valueOf()
true
moment(1446361200000).month(7).valueOf() == moment.utc(1446361200000).month(7).valueOf()
true
moment(1446361200000).month(8).valueOf() == moment.utc(1446361200000).month(8).valueOf()
true
moment(1446361200000).month(9).valueOf() == moment.utc(1446361200000).month(9).valueOf()
true
moment(1446361200000).month(10).valueOf() == moment.utc(1446361200000).month(10).valueOf()
true
moment(1446361200000).month(11).valueOf() == moment.utc(1446361200000).month(11).valueOf()
false
moment(1446361200000).month(12).valueOf() == moment.utc(1446361200000).month(12).valueOf()
false
moment(1446361200000).month(13).valueOf() == moment.utc(1446361200000).month(13).valueOf()
false
moment(1446361200000).month(14).valueOf() == moment.utc(1446361200000).month(14).valueOf()
false
moment(1446361200000).month(15).valueOf() == moment.utc(1446361200000).month(15).valueOf()
true

**Comment by mj1856** [comment] 2016-01-09 21:00
I don't see how you get `true` for that first example, unless your time zone is UTC or UK or something.  Is this browser code, or running on the server?  What version of browser/environment/moment?

Here's my output on the latest chrome with latest moment on windows in Pacific time zone:

![image](https://cloud.githubusercontent.com/assets/1396388/12218331/aff9d81c-b6e1-11e5-8618-37e8b153c027.png)

**Comment by ethanj** [comment] 2016-01-09 21:01
moment.version
"2.6.0"
navigator.appVersion
"5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36"

**Comment by mj1856** [comment] 2016-01-09 21:02
I have to board a plane, but feel free to continue the troubleshooting without me.  Try the current version (2.11.1) instead of 2.6.0.  You may be experiencing something we fixed already.

**Comment by ethanj** [comment] 2016-01-09 21:03
enjoy the ride

**Comment by Anongnito** [comment] 2016-01-09 22:42
@ethanj Did you have the same issue with 2.6.0?

**Comment by mj1856** [comment] 2016-01-10 22:14
Ok, I was able to reproduce it in older versions.  I tracked it down to #1983, which was fixed with #2001 in moment 2.8.4.

**Closed by mj1856** 2016-01-10 22:14 UTC
Labels: Troubleshooting

**Comment by mj1856** [comment] 2016-01-10 22:42
That bug explains the differences with the original question, using the m/d/y format without a format qualifier, which falls back to the date constructor.

The other thing that came up in this discussion was starting with a timestamp, then getting different results on which month was set.  This is actually not a bug at all.  Consider:

```javascript
for (var i = 0; i <= 11; i++) {
  var t = 1446361200000;
  var b = moment(t).month(i).valueOf() == moment.utc(t).month(i).valueOf();
  console.log (i + ':  ' + b);
}
```

When run in the Pacific time zone, it will return `true` only for months 3 through 10. Why?  Because:

```javascript
moment(1446361200000).format()  // "2015-11-01T00:00:00-07:00"
```
Since the offset is `-07:00`, you can change the month to any other month where the 1st at midnight also uses `-07:00` and it will be equivalent to changing to the same month in UTC:

```javascript
moment(1446361200000).month(3).format()      // "2015-04-01T00:00:00-07:00"
moment.utc(1446361200000).month(3).format()  // "2015-04-01T07:00:00+00:00"
```

But when summer is over, DST ends and Pacific time returns to `-08:00`, so the same operation doesn't line up:

```javascript
moment(1446361200000).month(11).format()      // "2015-12-01T00:00:00-08:00"
moment.utc(1446361200000).month(11).format()  // "2015-12-01T07:00:00+00:00"
```

Since midnight in -8 doesn't align with 7am in UTC, then you get `false` for the comparison.

**Comment by ethanj** [comment] 2016-01-10 22:50
while it may be true that this is not a bug, it seems to me that the library does not implement a common sense version of stuff so that one can easily iterate months... I will post the code that led me to this in a bit...

**Comment by mj1856** [comment] 2016-01-10 22:58
The library is doing the correct thing, I think perhaps your assumptions may be off.  I'll be happy to look at your code to help.

Keep in mind that DST is a PITA with stuff like this.  Moment is correctly taking DST into account to determine the offset for the target value. Switching months will attempt to keep the same year, day, hour, minute, second, and millisecond as the original value, and will do so within the context of the mode that it's currently operating in.  Since the source value is 7AM in UTC, and UTC doesn't do DST, then all results will also be in 7AM UTC.  But the value is 12AM in Pacific time, then switching months will still end up at 12AM in Pacific, regardless of whether Pacific is at -7 or -8.  It's screwy, but that's just how time works.

I said "attempt" in the last paragraph, because if you switch to a time that doesn't exist (such as during a spring-forward transition), or a day that doesn't exist (because you were near the end of the month and months have different lengths), then the other values might be adjusted.

**Comment by ethanj** [comment] 2016-01-10 23:18
yes, you are correct... I figured out from whence the confusion stemmed...
    curdate = moment.utc('11/1/15', 'MM/D/YY');
    curdate = moment.utc(1446361200000);

these are not equal in terms of valueOf()
so the issue likely was a result of not using the format on parse in an earlier version, and assuming the numeric value was correct.

thanks for your help!
Ethan

**Comment by mj1856** [comment] 2016-01-11 00:12
No problem.  Glad to help!
