### ISSUE TITLE
wrong days count by diff

### ISSUE THREAD

**Issue by fb-eye** [moment/moment#5587] opened 2020-06-09 04:31 UTC
`console.log(moment.duration(moment('2020-06-09 00:00:00').diff(moment('2012-01-18 00:00:00'))).days()); // 21, should be 22`

"version": "2.26.0"

**Comment by Alanscut** [comment] 2020-06-09 08:41
duplicate of #2928, This is related to the `bubble` function.

**Comment by marwahaha** [comment] 2020-06-12 00:27
closing as duplicate

**Comment by marwahaha** [comment] 2020-06-12 00:27
Thanks @fb-eye

**Closed by marwahaha** 2020-06-12 00:27 UTC
