### ISSUE TITLE
1 test failed. create:string with format (timezone offset) (2705.4) 

### ISSUE THREAD

**Issue by DecKen** [moment/moment#4311] opened 2017-11-20 02:16 UTC
### Client info
```
Date String   : Mon Nov 20 2017 10:15:07 GMT+0800 (CST)
Locale String : 2017/11/20 上午10:15:07
Offset        : -480
User Agent    : Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
Moment Version: 2.19.2
```

====

### create:string with format (timezone offset) (2705.4) 

parse timezone offset in utc

```javascript
// Expected NaN
// Actual   NaN
NaN === NaN
```

**Comment by ashsearle** [comment] 2017-11-20 19:19
Looks like a duplicate of #4251 

What does the `(2705.4)` reference refer to?

The actual vs expected demonstrates normal JavaScript behaviour: `NaN === NaN` evaluates to `false`.

**Comment by marwahaha** [comment] 2017-12-11 06:26
closing as duplicate of #4251 

I think the numbering refers to the 4th test here:
https://github.com/moment/moment/blob/develop/src/test/moment/create.js#L348-L360

**Closed by marwahaha** 2017-12-11 06:26 UTC
