### ISSUE TITLE
Incorrect timezone considerations

### ISSUE THREAD

**Issue by th3fallen** [moment/moment#4785] opened 2018-09-21 17:34 UTC
**Description of the Issue and Steps to Reproduce:**
Moment is configured in America/Asuncion timezone (-4) calculations are wrong when adding days.

moment example https://runkit.com/embed/1r62d83amq7x
yet luxon handles this correctly
https://runkit.com/embed/t49achvensqf

*Please include the values of all variables used.*

**Environment:**

*Examples: Chrome 49 on OSX, Internet Explorer 10 on Windows 7, Node.JS 4.4.4 on Ubuntu 16.0.4*
Chrome Latest, OSX, node LTS, React
*Both the browser and the OS are important to us, particularly if you have an unsual environment like an IOT application.*

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on CST or EST
* The time and date at which the code was run America/Asuncion
* Other libraries in use (TypeScript, Immutable.js, etc) moment-timezone in this case immutable.js are in the codebase but not relevant to this

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
America/Asuncion
VM25952:13 Fri Sep 21 2018 13:34:12 GMT-0400 (Eastern Daylight Time)
VM25952:14 9/21/2018, 1:34:12 PM
VM25952:15 240
VM25952:16 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
VM25952:17 2.22.1
```

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Comment by marwahaha** [comment] 2018-12-28 10:18
We need more information here to make any changes.

**Comment by marwahaha** [comment] 2019-01-19 09:32
This is interesting. I'm going to close as duplicate of #4743

**Closed by marwahaha** 2019-01-19 09:32 UTC
Labels: Up-For-Grabs
