### ISSUE TITLE
warning and error

### ISSUE THREAD

**Issue by XdCareWy** [moment/moment#4124] opened 2017-08-17 02:30 UTC
## description

> I use momentjs in my project. There is some questions. momentjsV2.18.1
`moment().add("day", 1);`
` moment().add(1, "day");`
![_008](https://user-images.githubusercontent.com/17895933/29393548-f3ac85b4-8336-11e7-8226-2ed5d376ff03.png)

**Comment by ashsearle** [comment] 2017-08-17 07:54
This is described [in the docs](https://momentjs.com/docs/#/manipulating/add/):

> Before version 2.8.0, the moment#add(String, Number) syntax was also supported. It has been deprecated in favor of moment#add(Number, String).

i.e. use `moment().add(1, "day");`

**Comment by ForsakenHarmony** [comment] 2017-08-18 21:10
it doesn't matter, it always gets detected as deprecated

**Comment by ashsearle** [comment] 2017-08-19 15:09
Which IDE, and are you coding with some sort of data-typing support (e.g. TypeScript?)

**Comment by ForsakenHarmony** [comment] 2017-08-19 15:24
pure js in webstorm

**Comment by ashsearle** [comment] 2017-08-19 17:53
WebStorm is using the TypeScript definitions bundled with moment.  I _think_ the fact it's marking all calls to `moment().add` as deprecated is due to a bug in WebStorm.

**Comment by icambron** [comment] 2017-08-21 16:13
I don't know much about typescript, but the deprecation looks right to me:

```js
   add(amount?: DurationInputArg1, unit?: DurationInputArg2): Moment;
    /**
     * @deprecated reverse syntax
     */
    add(unit: unitOfTime.DurationConstructor, amount: number|string): Moment;
```

i.e. one set of parameters is deprecated the other is not. If that's where Webstorm is getting that warning from, it sounds like a bug in Webstorm to me too.

**Comment by icambron** [comment] 2017-08-21 16:16
I'm going to close this. If it turns out there's something wrong with the Typescript declaration, we'll of course take a patch. If I'm wrong in some other way, @ me and I'll reopen.

**Comment by KKSzymanowski** [comment] 2017-09-22 12:56
I'm experiencing the same issue in PhpStorm. Is there any way around it?
I'm using PhpStorm 2017.2.4 and moment 2.18.1.

**Comment by icambron** [comment] 2017-09-22 13:52
Not that I know of. From the discussion above and my glance at the code, it seems like a bug in your editor. Perhaps its authors can help.

**Comment by KKSzymanowski** [comment] 2017-09-22 13:56
Yeah, apparently this has been already submited to Jetbrains issue tracker: https://youtrack.jetbrains.com/issue/WEB-28076

**Comment by icambron** [comment] 2017-09-22 15:10
@KKSzymanowski That issue seems to imply that if we flipped the order of the declarations in the typescript file, we'd get around the issue. I guess we'd take that change.

**Comment by KKSzymanowski** [comment] 2017-09-22 15:21
@icambron I'm afraid it won't work. When I change the order of declarations the deprecation warnings remain the same, even after IDE restart.
`Right click -> Go to -> Declaration` always points to the deprecated format.

Deprecated format however gives a warning about type mismatch:
![image](https://user-images.githubusercontent.com/13980973/30751723-5fcba2c6-9fba-11e7-9a7f-248bf3ac1d5b.png)

**Comment by ForsakenHarmony** [comment] 2017-09-22 17:22
Webstorm bug, only way to "fix" it would be removing the deprecated version

**Comment by G-Rath** [comment] 2017-10-03 23:15
@icambron actually, it's related to *documentation*.

As soon as I add 

```
      /**
       *
       * @param {moment.DurationInputArg1} amount
       * @param {moment.DurationInputArg2} unit
       * @returns {moment.Moment}
       */
```
(Which I just had generated automatically by WebStorm), WebStorm locks onto it and doesn't have any issues.

http://puu.sh/xPo1d/b1579d9489.png

**Comment by icambron** [comment] 2017-10-04 00:29
Weird. OK. I guess we'd take a PR adding blank doc stub to the non-deprecated one.

**Comment by ashsearle** [comment] 2017-10-05 08:18
@icambron note that @G-Rath suggestion removes the deprecation warning for both versions of `add()` - i.e. it's equivalent to removing the `@deprecated` comment (but only impacts IntelliJ IDEs.)

**Comment by Liero** [comment] 2019-10-24 08:25
I can confirm the same behavior in VS Code 1.39.2:
![image](https://user-images.githubusercontent.com/3494407/67467178-9a668900-f648-11e9-807f-a2734583a5da.png)

**Comment by nithil** [comment] 2020-06-23 06:57
@icambron Following screenshots are from latest VS Code(1.46.0)

![Screen Shot 2020-06-23 at 12 21 36](https://user-images.githubusercontent.com/31035540/85370489-6bdcdd00-b54c-11ea-994c-bdcff4f96dbe.png)

![Screen Shot 2020-06-23 at 12 22 51](https://user-images.githubusercontent.com/31035540/85370479-68e1ec80-b54c-11ea-813b-3c8618b80013.png)

**Comment by marwahaha** [comment] 2020-09-15 01:01
This seems like an issue in Webstorm.

**Closed by marwahaha** 2020-09-15 01:01 UTC
Labels: TypeScript

**Comment by bsell93** [comment] 2021-06-21 19:57
Still experiencing this issue in VSCode and with SonarLint. My guess is there an issue with vscode and others not handling overrides appropriately.
