### ISSUE TITLE
moment.fromNow() returns "Invalid date" even though .isValid() is true

### ISSUE THREAD

**Issue by SamusAranX** [moment/moment#4614] opened 2018-05-07 09:54 UTC
**Description of the Issue and Steps to Reproduce:**

I'm using a custom version of MomentJS 2.20.1 where I removed all locales but the German one: https://gist.github.com/SamusAranX/4df8b46fa49b09af1a657cf877e51666

I tried updating to the most recent version (2.22.1), but it exhibits the exact same problem:
For some reason, `.fromNow()` just stopped working.

```
var m = moment("2018-05-07 11:40:30");
m.fromNow(); // returns "Invalid date"

var m2 = moment([2018, 5, 7]);
m2.fromNow(); // returns "Invalid date" as well
```

Curiously, `.isValid()` returns true with both dates.

Am I doing something wrong? Those dates look good to me.

**Environment:**

Safari 11.1 and Chrome 66 on macOS 10.13.4

```
Mon May 07 2018 11:50:47 GMT+0200 (CEST)
5/7/2018, 11:50:47 AM
-120
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15
2.20.1
```

**Comment by galinkyuchukov** [comment] 2018-05-29 22:06
Have same problem in nodejs! In a browser - no issues!

**Comment by ichernev** [comment] 2018-06-27 21:28
I tried this on slightly updated safari and macos and I don't see the issue with moment 2.22.2. Can you please verify?

**Comment by marwahaha** [comment] 2019-01-17 11:14
closing as dupe of https://github.com/moment/moment/issues/4802, but worrisome that many people are reporting this...

**Closed by marwahaha** 2019-01-17 11:14 UTC
