### ISSUE TITLE
1 test failed. week year:week numbers 2012/2013 (2446.7) 

### ISSUE THREAD

**Issue by gmobi-lixing** [moment/moment#3302] opened 2016-07-14 01:42 UTC
### Client info
```
Date String   : Thu Jul 14 2016 09:41:34 GMT+0800 (ä¸­å½æ åæ¶é´)
Locale String : 2016/7/14 上午9:41:34
Offset        : -480
User Agent    : Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36
```

====

### week year:week numbers 2012/2013 (2446.7) 

```javascript
// Expected 53
// Actual   52
52 === 53
```

**Comment by mtimofiiv** [comment] 2016-07-14 10:15
Confirming this issue. For example, in 2016, week 28 is [July 11th - 17th](http://weeknumber.net/28) but:

```
> moment('2016', 'YYYY').week(28).toString()
'Fri Jul 08 2016 00:00:00 GMT+0200'
> moment('2016', 'YYYY').week(28).weekday(1).toString()
'Mon Jul 04 2016 00:00:00 GMT+0200'

```

**Comment by icambron** [comment] 2016-07-20 02:40
@mtimofiiv That's a different issue than the OP's and is not a bug. This is what you should be comparing to that website's output:

```js
moment('2016', 'GGGG').isoWeek(28).startOf('isoweek').format('LL'); //=> "July 11, 2016"
```

The isoWeekday() vs weekday() thing is simple enough; the latter is a localized version, whereas the `iso*` methods deal with the most commonly accepted standard (that website seems to use ISO weeks too). Also note that you need to be really careful with stuff like `moment('2016', 'YYYY')` because that parses to Jan 1, which may be in a different week year than you mean! So don't do this:

```js
moment('2016', 'YYYY').isoWeek(28).startOf('isoweek').format('LL'); //=> "July 6, 2015"
//note the 2015!
```

The OP's issue is a failing test, meaning that somehow in the OP's timezone Moment isn't doing something the way it thinks it ought to. I'm not sure why that is. I suspect the same tests would pass for you, though.

**Comment by icambron** [comment] 2016-07-21 02:03
Closing this in favor of #2998

**Closed by icambron** 2016-07-21 02:03 UTC

**Comment by mtimofiiv** [comment] 2016-07-21 09:42
Thanks for the tip, @icambron!
