### ISSUE TITLE
month year and day functions accept NaN as a value.

### ISSUE THREAD

**Issue by boris-marinov** [moment/moment#5292] opened 2019-11-15 12:18 UTC
**Describe the bug**
Month year and day functions accept NaN as a value. Date seems valid but it's actually broken when such values are passed.

**To Reproduce**
```
> moment().month(NaN).format()
< "-0NaN--NaN--NaNT-NaN:-NaN:-NaN+00:00"

> moment().month(NaN).isValid()
< true

> moment().year(NaN).isValid()
< true
```
**Expected behavior**
The date should show as invalid.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
N/A 

**Moment-specific environment**
N/A

Please run the following code in your environment and include the output:
```
Fri Nov 15 2019 14:16:30 GMT+0200 (Eastern European Standard Time)
VM399:2 11/15/2019, 2:16:30 PM
VM399:3 -120
VM399:4 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
```

**Additional context**
Seems crucial, because the year function of invalid dates return NaN, so if you do something like:
```
validDate.month(inValidDate.month())
```
This will break the validDate.

**Comment by ODAVING** [comment] 2019-11-23 21:39
I can fix this issue, np!

**Comment by marwahaha** [comment] 2020-05-12 13:44
related to #5146

**Comment by marwahaha** [comment] 2020-05-18 08:52
duplicate of ahttps://github.com/moment/moment/issues/3071

**Closed by marwahaha** 2020-05-18 08:52 UTC
Labels: Forgiving parsing
